import ZiskFv.Compliance.ConstructionSub
import ZiskFv.Compliance.ConstructionAnd
import ZiskFv.Compliance.ConstructionLogic
import ZiskFv.Compliance.ConstructionCompare
import ZiskFv.Compliance.ConstructionIType
import ZiskFv.Compliance.ConstructionShift
import ZiskFv.Compliance.ConstructionAdd
import ZiskFv.Compliance.ConstructionWAlu
import ZiskFv.Compliance.ConstructionLui
import ZiskFv.Compliance.ConstructionAuipc
import ZiskFv.Compliance.ConstructionMulw
import ZiskFv.Compliance.ConstructionMulhu
import ZiskFv.Compliance.ConstructionDivu
import ZiskFv.Compliance.ConstructionDivuw
import ZiskFv.Compliance.ConstructionRemu
import ZiskFv.Compliance.ConstructionRemuw
import ZiskFv.Compliance.ConstructionStore
import ZiskFv.Compliance.ConstructionLoad
import ZiskFv.Compliance.ConstructionBranch
import ZiskFv.Compliance.ConstructionJump
import ZiskFv.Compliance
import ZiskFv.Compliance.Defects
import ZiskFv.Compliance.TraceLevelExport.Base
import ZiskFv.Compliance.TraceLevelExport.RowDataAluShift
import ZiskFv.Compliance.TraceLevelExport.RowDataArithMem
import ZiskFv.Compliance.TraceLevelExport.RowDataControl
import ZiskFv.Compliance.TraceLevelExport.EnvOf
import ZiskFv.Compliance.TraceLevelExport.StepStrongAluArith
import ZiskFv.Compliance.TraceLevelExport.StepStrongControlStore
import ZiskFv.Compliance.TraceLevelExport.StepStrongLoadMext
import ZiskFv.Compliance.TraceLevelExport.StepStrongSignedM
import ZiskFv.Compliance.TraceLevelExport.RowDataSplit

namespace ZiskFv.Compliance

open ZiskFv.Trusted
open ZiskFv.Airs.Main
open ZiskFv.Airs.Mem (Valid_Mem)
open ZiskFv.EquivCore.Promises
open ZiskFv.Channels.MemoryBusBytes (byteAt)
open ZiskFv.AirsClean.FullEnsemble (mainOfTable)
open ZiskFv.Tactics.ALUITypeArchetype (itype_imm_subset_holds_main)
open Interaction

-- The M-extension row-computing defs are reducible/semireducible; structure-field
-- elaboration would otherwise whnf-reduce the full per-row ArithMul/ArithDiv
-- computation (a runaway). `seal` blocks that locally without touching the
-- committed construction proofs (which keep the defs as-is in their oleans).
seal mulwArow mulhuArow divuArow divuwArow remuArow remuwArow

set_option maxHeartbeats 8000000
-- 63-deep `← ...` array literals in the generators below desugar to nested
-- monadic binds; raise the elaborator recursion limit so they fit.
set_option maxRecDepth 100000

/-! ## Strong sum + dispatcher + top-level strengthened export

This file is dominated by 63-arm-per-opcode blocks that are uniform modulo the
opcode name.  Rather than spell out 63 near-identical arms eight times over, the
arms are GENERATED by a handful of local `elab` commands (see the `Codegen`
section below).  Each generator splices an array of constructor /
match-alternative / tactic-alternative `Syntax` nodes — built by folding over the
shared `dispatchOps` opcode list — into a single quoted declaration, then
`elabCommand`s the result.  The expansion is *meaning-identical* to the
hand-written arms (same declaration names, same elaborated types, same proof
terms), so `Lean.collectAxioms` sees no change and every downstream consumer /
trust baseline is byte-stable.

`StepFaithful` (the one block whose per-arm *equality* genuinely differs per
opcode) is generated from an explicit per-op table that pins exactly what varies:
the Sail instruction (+ its operand projections), whether a `writeReg nextPC`
prelude wraps it, and which channel-balance RHS shape it equals.  Everything else
(the `do`-prelude, `state_effect_via_channels`, the bus triple, `sailTrace i`) is
shared template.

Hygiene note: the generated declarations are declared by raw `mkIdent` name so
they are reachable by their real names; for the same reason, every *reference*
to one generated decl from another (and to the auto-bound `numInstructions`) is
spliced via `mkIdent`.  Shared *local* binders (`ziskTrace`, `i`, `c`, …) are
written literally and stay consistent because all quotations within one `elab`
share a macro scope. -/

section Codegen
open Lean Elab Command

/-- The 63 RV64IM opcodes, in canonical dispatch (= `ZiskStep` constructor) order.
    Drives every fully-uniform block: `ZiskStep`, `StrongRowConstructionData`,
    `RowDecode`, `InputsAgree`, `toFull`, `stepFaithful_of_evidence`. -/
private def dispatchOps : Array String :=
  #["sub", "and", "or", "xor", "slt", "sltu", "andi", "ori", "xori", "slti",
    "sltiu", "sll", "srl", "sra", "slli", "srli", "srai", "add", "addi", "subw",
    "addw", "addiw", "sllw", "srlw", "sraw", "slliw", "srliw", "sraiw", "mul",
    "mulh", "mulhsu", "mulw", "mulhu", "div", "rem", "divw", "remw", "divu",
    "divuw", "remu", "remuw", "beq", "bne", "blt", "bge", "bltu", "bgeu", "lui",
    "auipc", "jal", "jalr", "sb", "sh", "sw", "sd", "ld", "lbu", "lhu", "lwu",
    "lb", "lh", "lw", "fence"]

/-- A per-row classification carrying the honest residual binders for ALL 63 RV64IM
    arms, each strengthened to the channel-balance / env-constructed form.  One arm
    per opcode: `| <op> (d : RowData_<op> ziskTrace sailTrace i) : …`. -/
elab "gen_StrongRowConstructionData" : command => do
  let ni := mkIdent `numInstructions
  let srcd := mkIdent `StrongRowConstructionData
  let ctors ← dispatchOps.mapM fun op => do
    let nm := mkIdent (Name.mkSimple op)
    let rdId := mkIdent (Name.mkSimple ("RowData_" ++ op))
    `(Lean.Parser.Command.ctor|
        | $nm:ident (d : $rdId ziskTrace sailTrace i) : $srcd ziskTrace sailTrace i)
  elabCommand (← `(inductive $srcd
      (ziskTrace : AcceptedZiskTrace $ni)
      (sailTrace : SailTrace ziskTrace.numInstructions)
      (i : Fin ziskTrace.numInstructions) where
      $ctors:ctor*))

/-- The per-row claim sum: `| <op> (c : Claim_<op> ziskTrace i) : ZiskStep …`. -/
elab "gen_ZiskStep" : command => do
  let ni := mkIdent `numInstructions
  let zstep := mkIdent `ZiskStep
  let ctors ← dispatchOps.mapM fun op => do
    let nm := mkIdent (Name.mkSimple op)
    let claimId := mkIdent (Name.mkSimple ("Claim_" ++ op))
    `(Lean.Parser.Command.ctor|
        | $nm:ident (c : $claimId ziskTrace i) : $zstep ziskTrace i)
  elabCommand (← `(inductive $zstep
      (ziskTrace : AcceptedZiskTrace $ni)
      (i : Fin ziskTrace.numInstructions) where
      $ctors:ctor*))

/-- `RowDecode`: per-claim circuit-checkable decode payload.
    `| .<op> c => Decode_<op> ziskTrace i c`. -/
elab "gen_RowDecode" : command => do
  let ni := mkIdent `numInstructions
  let zstep := mkIdent `ZiskStep
  let alts ← dispatchOps.mapM fun op => do
    let nm := mkIdent (Name.mkSimple op)
    let decId := mkIdent (Name.mkSimple ("Decode_" ++ op))
    `(Lean.Parser.Term.matchAltExpr| | .$nm:ident c => $decId ziskTrace i c)
  elabCommand (← `(def $(mkIdent `RowDecode) (ziskTrace : AcceptedZiskTrace $ni)
      (i : Fin ziskTrace.numInstructions) : $zstep ziskTrace i → Type
      $alts:matchAlt*))

/-- `InputsAgree`: per-claim cross-world inputs payload.
    `| .<op> c => Inputs_<op> ziskTrace sailTrace i c`. -/
elab "gen_InputsAgree" : command => do
  let ni := mkIdent `numInstructions
  let zstep := mkIdent `ZiskStep
  let alts ← dispatchOps.mapM fun op => do
    let nm := mkIdent (Name.mkSimple op)
    let inId := mkIdent (Name.mkSimple ("Inputs_" ++ op))
    `(Lean.Parser.Term.matchAltExpr| | .$nm:ident c => $inId ziskTrace sailTrace i c)
  elabCommand (← `(def $(mkIdent `InputsAgree) (ziskTrace : AcceptedZiskTrace $ni)
      (sailTrace : SailTrace ziskTrace.numInstructions)
      (i : Fin ziskTrace.numInstructions) : $zstep ziskTrace i → Type
      $alts:matchAlt*))

/-- `toFull`: assemble the strengthened `StrongRowConstructionData` from a claim
    and its decode/inputs payloads.
    `| .<op> c, rd, ia => .<op> (toRowData_<op> c rd ia)`. -/
elab "gen_toFull" : command => do
  let ni := mkIdent `numInstructions
  let zstep := mkIdent `ZiskStep
  let rdec := mkIdent `RowDecode
  let iagr := mkIdent `InputsAgree
  let srcd := mkIdent `StrongRowConstructionData
  let alts ← dispatchOps.mapM fun op => do
    let nm := mkIdent (Name.mkSimple op)
    let toRd := mkIdent (Name.mkSimple ("toRowData_" ++ op))
    `(Lean.Parser.Term.matchAltExpr|
        | .$nm:ident c, rd, ia => .$nm:ident ($toRd c rd ia))
  elabCommand (← `(def $(mkIdent `toFull) (ziskTrace : AcceptedZiskTrace $ni)
      (sailTrace : SailTrace ziskTrace.numInstructions)
      (i : Fin ziskTrace.numInstructions) (zs : $zstep ziskTrace i)
      (rd : $rdec ziskTrace i zs) (ia : $iagr ziskTrace sailTrace i zs) :
      $srcd ziskTrace sailTrace i :=
    match zs, rd, ia with $alts:matchAlt*))

/-- `StepNoKnownDefectOn`: the per-row defect-exclusion obligation.

    The 55 non-defect arms are the uniform `EnvNoKnownDefectFor` selector-∀
    obligation (generated below), each pinned to that arm's `OpEnvelope`
    constructor(s).  Five arms (`add`, `addi`, `lb`, `lh`, `lw`) carry a
    non-trivial selector constructor list; the other 50 select on their own
    single constructor.

    The 8 defect arms (`mul mulh mulhsu div rem divw remw fence`) are the
    EXCEPTION: they ask for the GENUINE `NoKnownDefect` of the SPECIFIC env built
    from the row's honest-shape pins (the selector-∀ shape would be FALSE for
    those — a malicious row matches the selector but is NOT `NoKnownDefect`).
    That obligation is SATISFIABLE for an honest row (see `RowData_<op>` /
    `stepStrong_<op>`); the env is `<op>EnvOf ziskTrace sailTrace i d`. -/
elab "gen_StepNoKnownDefectOn" : command => do
  let ni := mkIdent `numInstructions
  let srcd := mkIdent `StrongRowConstructionData
  -- one `EnvNoKnownDefectFor` arm, selecting on the given OpEnvelope ctor list
  let mkEnvArm (op : String) (sels : List String) :
      CommandElabM (TSyntax ``Lean.Parser.Term.matchAltExpr) := do
    let nm := mkIdent (Name.mkSimple op)
    let selAlts0 ← sels.toArray.mapM fun s => do
      let cid := mkIdent (Name.mkSimple s)
      `(Lean.Parser.Term.matchAltExpr| | .$cid:ident .. => True)
    let selAlts := selAlts0.push (← `(Lean.Parser.Term.matchAltExpr| | _ => False))
    `(Lean.Parser.Term.matchAltExpr| | .$nm:ident _ =>
        EnvNoKnownDefectFor
          (state := sailTrace i)
          (m := ZiskFv.AirsClean.FullEnsemble.mainOfTable ziskTrace.program ziskTrace.mainTable)
          (r := i.val) (fun env => match env with $selAlts:matchAlt*))
  let env (op : String) := mkEnvArm op [op]
  -- the genuine-`NoKnownDefect` defect arm: env is `<op>EnvOf ziskTrace sailTrace i d`
  let defect (op : String) : CommandElabM (TSyntax ``Lean.Parser.Term.matchAltExpr) := do
    let nm := mkIdent (Name.mkSimple op)
    let envFn := mkIdent (Name.mkSimple (op ++ "EnvOf"))
    `(Lean.Parser.Term.matchAltExpr| | .$nm:ident d =>
        Defects.NoKnownDefect ($envFn ziskTrace sailTrace i d))
  -- the 63 arms (StepNoKnownDefectOn's own order); built as actions then run via
  -- `mapM id` to avoid the deep `← …` array-literal desugaring.
  let alts ← (#[
    env "sub", env "and", env "or", env "xor", env "slt", env "sltu",
    env "andi", env "ori", env "xori", env "slti", env "sltiu",
    env "sll", env "srl", env "sra", env "slli", env "srli", env "srai",
    mkEnvArm "add" ["add_via_binary", "add_via_binaryadd"],
    mkEnvArm "addi" ["addi_via_binary", "addi_via_binaryadd"],
    env "subw", env "addw", env "addiw", env "sllw", env "srlw", env "sraw",
    env "slliw", env "srliw", env "sraiw", env "jalr",
    env "beq", env "bne", env "blt", env "bge", env "bltu", env "bgeu",
    defect "mul", defect "mulh", defect "mulhsu",
    defect "div", defect "rem", defect "divw", defect "remw",
    env "mulw", env "mulhu", env "divu", env "divuw", env "remu", env "remuw",
    env "lui", env "auipc", env "jal",
    env "sb", env "sh", env "sw", env "sd",
    env "ld", env "lbu", env "lhu", env "lwu",
    mkEnvArm "lb" ["lb_via_static_match"],
    mkEnvArm "lh" ["lh_via_static_match"],
    mkEnvArm "lw" ["lw_via_static_match"],
    defect "fence"] : Array (CommandElabM (TSyntax ``Lean.Parser.Term.matchAltExpr))).mapM id
  elabCommand (← `(def $(mkIdent `StepNoKnownDefectOn)
      (ziskTrace : AcceptedZiskTrace $ni)
      (sailTrace : SailTrace ziskTrace.numInstructions) (i : Fin ziskTrace.numInstructions) :
      $srcd ziskTrace sailTrace i → Prop
      $alts:matchAlt*))

/-- `StepFaithful`: the strengthened per-step conclusion (the channel-balance
    `state_effect_via_channels` form) keyed on the row archetype.  Unlike the
    other blocks, the per-op *equality* genuinely differs, so this is generated
    from an explicit table pinning exactly what varies per opcode:
      • the Sail instruction term (with its operand projections off `c`),
      • whether a `writeReg nextPC` prelude wraps the execute, and
      • the channel-balance RHS shape (`busSub`/`busSt`/`busLd` triple, the
        `c.bus` triple, the `eRdLui` single-channel form, or the empty form). -/
elab "gen_StepFaithful" : command => do
  let ni := mkIdent `numInstructions
  let zstep := mkIdent `ZiskStep
  -- RHS shapes ----------------------------------------------------------------
  let busRhs (fn : String) : CommandElabM (TSyntax `term) := do
    let f := mkIdent (Name.mkSimple fn)
    `(ZiskFv.Channels.state_effect_via_channels
        ⟨($f ziskTrace i c.execRow).exec_row,
         [($f ziskTrace i c.execRow).e0, ($f ziskTrace i c.execRow).e1,
          ($f ziskTrace i c.execRow).e2]⟩ (sailTrace i))
  let cbusRhs : CommandElabM (TSyntax `term) :=
    `(ZiskFv.Channels.state_effect_via_channels
        ⟨c.bus.exec_row, [c.bus.e0, c.bus.e1, c.bus.e2]⟩ (sailTrace i))
  let eRdRhs : CommandElabM (TSyntax `term) :=
    `(ZiskFv.Channels.state_effect_via_channels
        ⟨c.execRow, [eRdLui ziskTrace i]⟩ (sailTrace i))
  let emptyRhs : CommandElabM (TSyntax `term) :=
    `(ZiskFv.Channels.state_effect_via_channels ⟨c.exec_row, []⟩ (sailTrace i))
  -- one arm: `| .<op> c => <lhs> = <rhs>`.  `instrM`/`rhsM` are passed as
  -- actions (no `←`) so the 63-entry table below is a flat array of actions.
  let mkArm (op : String) (writePC : Bool)
      (instrM rhsM : CommandElabM (TSyntax `term)) :
      CommandElabM (TSyntax ``Lean.Parser.Term.matchAltExpr) := do
    let nm := mkIdent (Name.mkSimple op)
    let instr ← instrM
    let rhs ← rhsM
    let lhs ← if writePC then
        `((do
          Sail.writeReg Register.nextPC
            (Sail.BitVec.addInt (← Sail.readReg Register.PC) 4)
          LeanRV64D.Functions.execute $instr) (sailTrace i))
      else
        `(execute_instruction $instr (sailTrace i))
    `(Lean.Parser.Term.matchAltExpr| | .$nm:ident c => $lhs = $rhs)
  let alts ← (#[
    mkArm "sub"  true  `(instruction.RTYPE (c.r2, c.r1, c.rd, rop.SUB))  (busRhs "busSub"),
    mkArm "and"  true  `(instruction.RTYPE (c.r2, c.r1, c.rd, rop.AND))  (busRhs "busSub"),
    mkArm "or"   true  `(instruction.RTYPE (c.r2, c.r1, c.rd, rop.OR))   (busRhs "busSub"),
    mkArm "xor"  true  `(instruction.RTYPE (c.r2, c.r1, c.rd, rop.XOR))  (busRhs "busSub"),
    mkArm "slt"  true  `(instruction.RTYPE (c.r2, c.r1, c.rd, rop.SLT))  (busRhs "busSub"),
    mkArm "sltu" true  `(instruction.RTYPE (c.r2, c.r1, c.rd, rop.SLTU)) (busRhs "busSub"),
    mkArm "andi" true  `(instruction.ITYPE (c.imm, c.r1, c.rd, iop.ANDI))  (busRhs "busSub"),
    mkArm "ori"  true  `(instruction.ITYPE (c.imm, c.r1, c.rd, iop.ORI))   (busRhs "busSub"),
    mkArm "xori" true  `(instruction.ITYPE (c.imm, c.r1, c.rd, iop.XORI))  (busRhs "busSub"),
    mkArm "slti" true  `(instruction.ITYPE (c.imm, c.r1, c.rd, iop.SLTI))  (busRhs "busSub"),
    mkArm "sltiu" true `(instruction.ITYPE (c.imm, c.r1, c.rd, iop.SLTIU)) (busRhs "busSub"),
    mkArm "sll"  false `(instruction.RTYPE (c.r2, c.r1, c.rd, rop.SLL))  (busRhs "busSub"),
    mkArm "srl"  false `(instruction.RTYPE (c.r2, c.r1, c.rd, rop.SRL))  (busRhs "busSub"),
    mkArm "sra"  false `(instruction.RTYPE (c.r2, c.r1, c.rd, rop.SRA))  (busRhs "busSub"),
    mkArm "slli" false `(instruction.SHIFTIOP (c.shamt, c.r1, c.rd, sop.SLLI)) (busRhs "busSub"),
    mkArm "srli" false `(instruction.SHIFTIOP (c.shamt, c.r1, c.rd, sop.SRLI)) (busRhs "busSub"),
    mkArm "srai" false `(instruction.SHIFTIOP (c.shamt, c.r1, c.rd, sop.SRAI)) (busRhs "busSub"),
    mkArm "add"  true  `(instruction.RTYPE (c.r2, c.r1, c.rd, rop.ADD))  (busRhs "busSub"),
    mkArm "addi" true  `(instruction.ITYPE (c.imm, c.r1, c.rd, iop.ADDI))  (busRhs "busSub"),
    mkArm "subw" true  `(instruction.RTYPEW (c.r2, c.r1, c.rd, ropw.SUBW)) (busRhs "busSub"),
    mkArm "addw" true  `(instruction.RTYPEW (c.r2, c.r1, c.rd, ropw.ADDW)) (busRhs "busSub"),
    mkArm "addiw" true `(instruction.ADDIW (c.imm, c.r1, c.rd))           (busRhs "busSub"),
    mkArm "sllw" false `(instruction.RTYPEW (c.r2, c.r1, c.rd, ropw.SLLW)) (busRhs "busSub"),
    mkArm "srlw" false `(instruction.RTYPEW (c.r2, c.r1, c.rd, ropw.SRLW)) (busRhs "busSub"),
    mkArm "sraw" false `(instruction.RTYPEW (c.r2, c.r1, c.rd, ropw.SRAW)) (busRhs "busSub"),
    mkArm "slliw" false `(instruction.SHIFTIWOP (c.slliw_input.shamt, c.r1, c.rd, sopw.SLLIW)) (busRhs "busSub"),
    mkArm "srliw" false `(instruction.SHIFTIWOP (c.srliw_input.shamt, c.r1, c.rd, sopw.SRLIW)) (busRhs "busSub"),
    mkArm "sraiw" false `(instruction.SHIFTIWOP (c.sraiw_input.shamt, c.r1, c.rd, sopw.SRAIW)) (busRhs "busSub"),
    mkArm "mul" true
        `(instruction.MUL
            (c.r2, c.r1, c.rd,
             { result_part := VectorHalf.Low
               signed_rs1 := c.srs1
               signed_rs2 := c.srs2 })) cbusRhs,
    mkArm "mulh" true
        `(instruction.MUL
            (c.r2, c.r1, c.rd,
             { result_part := VectorHalf.High
               signed_rs1 := .Signed
               signed_rs2 := .Signed })) cbusRhs,
    mkArm "mulhsu" true
        `(instruction.MUL
            (c.r2, c.r1, c.rd,
             { result_part := VectorHalf.High
               signed_rs1 := .Signed
               signed_rs2 := .Unsigned })) cbusRhs,
    mkArm "div"  true  `(instruction.DIV (c.r2, c.r1, c.rd, false))  cbusRhs,
    mkArm "rem"  true  `(instruction.REM (c.r2, c.r1, c.rd, false))  cbusRhs,
    mkArm "divw" true  `(instruction.DIVW (c.r2, c.r1, c.rd, false)) cbusRhs,
    mkArm "remw" true  `(instruction.REMW (c.r2, c.r1, c.rd, false)) cbusRhs,
    mkArm "mulw" true  `(instruction.MULW (c.r2, c.r1, c.rd))        (busRhs "busSub"),
    mkArm "mulhu" true
        `(instruction.MUL
            (c.r2, c.r1, c.rd,
             { result_part := VectorHalf.High
               signed_rs1 := .Unsigned
               signed_rs2 := .Unsigned })) (busRhs "busSub"),
    mkArm "divu"  true `(instruction.DIV (c.r2, c.r1, c.rd, true))  (busRhs "busSub"),
    mkArm "divuw" true `(instruction.DIVW (c.r2, c.r1, c.rd, true)) (busRhs "busSub"),
    mkArm "remu"  true `(instruction.REM (c.r2, c.r1, c.rd, true))  (busRhs "busSub"),
    mkArm "remuw" true `(instruction.REMW (c.r2, c.r1, c.rd, true)) (busRhs "busSub"),
    mkArm "beq"  false `(instruction.BTYPE (c.imm, c.r2, c.r1, bop.BEQ))  emptyRhs,
    mkArm "bne"  false `(instruction.BTYPE (c.imm, c.r2, c.r1, bop.BNE))  emptyRhs,
    mkArm "blt"  false `(instruction.BTYPE (c.imm, c.r2, c.r1, bop.BLT))  emptyRhs,
    mkArm "bge"  false `(instruction.BTYPE (c.imm, c.r2, c.r1, bop.BGE))  emptyRhs,
    mkArm "bltu" false `(instruction.BTYPE (c.imm, c.r2, c.r1, bop.BLTU)) emptyRhs,
    mkArm "bgeu" false `(instruction.BTYPE (c.imm, c.r2, c.r1, bop.BGEU)) emptyRhs,
    mkArm "lui"   false `(instruction.UTYPE (c.imm, c.rd, uop.LUI))   eRdRhs,
    mkArm "auipc" false `(instruction.UTYPE (c.imm, c.rd, uop.AUIPC)) eRdRhs,
    mkArm "jal"   false `(instruction.JAL (c.imm, c.rd))              eRdRhs,
    mkArm "jalr"  true  `(instruction.JALR (c.imm, c.rs1, c.rd))      eRdRhs,
    mkArm "sb" false
        `(instruction.STORE
            (c.sb_input.imm, regidx.Regidx c.sb_input.r2, regidx.Regidx c.sb_input.r1, 1))
        (busRhs "busSt"),
    mkArm "sh" false
        `(instruction.STORE
            (c.sh_input.imm, regidx.Regidx c.sh_input.r2, regidx.Regidx c.sh_input.r1, 2))
        (busRhs "busSt"),
    mkArm "sw" false
        `(instruction.STORE
            (c.sw_input.imm, regidx.Regidx c.sw_input.r2, regidx.Regidx c.sw_input.r1, 4))
        (busRhs "busSt"),
    mkArm "sd" false
        `(instruction.STORE
            (c.sd_input.imm, regidx.Regidx c.sd_input.r2, regidx.Regidx c.sd_input.r1, 8))
        (busRhs "busSt"),
    mkArm "ld" false
        `(instruction.LOAD
            (c.ld_input.imm, regidx.Regidx c.ld_input.r1, regidx.Regidx c.ld_input.rd, false, 8))
        (busRhs "busLd"),
    mkArm "lbu" false
        `(instruction.LOAD
            (c.lbu_input.imm, regidx.Regidx c.lbu_input.r1, regidx.Regidx c.lbu_input.rd, true, 1))
        (busRhs "busLd"),
    mkArm "lhu" false
        `(instruction.LOAD
            (c.lhu_input.imm, regidx.Regidx c.lhu_input.r1, regidx.Regidx c.lhu_input.rd, true, 2))
        (busRhs "busLd"),
    mkArm "lwu" false
        `(instruction.LOAD
            (c.lwu_input.imm, regidx.Regidx c.lwu_input.r1, regidx.Regidx c.lwu_input.rd, true, 4))
        (busRhs "busLd"),
    mkArm "lb" false
        `(instruction.LOAD
            (c.lb_input.imm, regidx.Regidx c.lb_input.r1, regidx.Regidx c.lb_input.rd, false, 1))
        (busRhs "busLd"),
    mkArm "lh" false
        `(instruction.LOAD
            (c.lh_input.imm, regidx.Regidx c.lh_input.r1, regidx.Regidx c.lh_input.rd, false, 2))
        (busRhs "busLd"),
    mkArm "lw" false
        `(instruction.LOAD
            (c.lw_input.imm, regidx.Regidx c.lw_input.r1, regidx.Regidx c.lw_input.rd, false, 4))
        (busRhs "busLd"),
    mkArm "fence" false
        `(instruction.FENCE (c.fm, c.fenceP, c.fenceS, c.rs, c.rd)) emptyRhs
    ] : Array (CommandElabM (TSyntax ``Lean.Parser.Term.matchAltExpr))).mapM id
  elabCommand (← `(def $(mkIdent `StepFaithful)
      (ziskTrace : AcceptedZiskTrace $ni)
      (sailTrace : SailTrace ziskTrace.numInstructions) (i : Fin ziskTrace.numInstructions) :
      $zstep ziskTrace i → Prop
      $alts:matchAlt*))

/-- `stepFaithful_of_evidence`: per-row dispatch to the matching strengthened step
    theorem.  `| <op> c => exact stepStrong_<op> ziskTrace sailTrace i
    (toRowData_<op> c rd ia) h_known`. -/
elab "gen_stepFaithful_of_evidence" : command => do
  let ni := mkIdent `numInstructions
  let zstep := mkIdent `ZiskStep
  let rdec := mkIdent `RowDecode
  let iagr := mkIdent `InputsAgree
  let snkd := mkIdent `StepNoKnownDefect
  let sfaith := mkIdent `StepFaithful
  let alts ← dispatchOps.mapM fun op => do
    let nm := mkIdent (Name.mkSimple op)
    let ss := mkIdent (Name.mkSimple ("stepStrong_" ++ op))
    let toRd := mkIdent (Name.mkSimple ("toRowData_" ++ op))
    `(Lean.Parser.Tactic.inductionAlt|
        | $nm:ident c => exact $ss ziskTrace sailTrace i ($toRd c rd ia) h_known)
  elabCommand (← `(theorem $(mkIdent `stepFaithful_of_evidence)
      (ziskTrace : AcceptedZiskTrace $ni)
      (sailTrace : SailTrace ziskTrace.numInstructions)
      (i : Fin ziskTrace.numInstructions) (zs : $zstep ziskTrace i)
      (rd : $rdec ziskTrace i zs) (ia : $iagr ziskTrace sailTrace i zs)
      (h_known : $snkd ziskTrace sailTrace i zs rd ia) :
      $sfaith ziskTrace sailTrace i zs := by
    cases zs with $alts:inductionAlt*))

end Codegen

-- Generated, in dependency order (see the `Codegen` section above).  Each
-- invocation expands to the hand-written 63-arm block it replaces.
gen_StrongRowConstructionData
gen_ZiskStep
gen_RowDecode
gen_InputsAgree
gen_toFull
gen_StepNoKnownDefectOn

/-- The strengthened per-step conclusion: the channel-balance
    (`state_effect_via_channels`) form — the OLD global theorem's per-arm
    conclusion — keyed on the row archetype. -/
def StepNoKnownDefect (ziskTrace : AcceptedZiskTrace numInstructions) (sailTrace : SailTrace ziskTrace.numInstructions)
    (i : Fin ziskTrace.numInstructions) (zs : ZiskStep ziskTrace i)
    (rd : RowDecode ziskTrace i zs) (ia : InputsAgree ziskTrace sailTrace i zs) : Prop :=
  StepNoKnownDefectOn ziskTrace sailTrace i (toFull ziskTrace sailTrace i zs rd ia)

gen_StepFaithful
gen_stepFaithful_of_evidence

end ZiskFv.Compliance
