#!/usr/bin/env python3
"""Regenerate `trust/baseline-axioms.txt` from the live tree.

Walks every file in `trust/allowed-axiom-files.txt`, parses each top-level
axiom / opaque / constant declaration, hashes the **source-text block**
that defines it, and writes a sorted baseline file. Run this after a
legitimate trust-surface change, then commit the updated baseline in the
same PR as the change.

This is a V1 implementation: the hash is over source text. It catches
adds/removes/renames AND any whitespace- or statement-altering edit.
V2 (a Lake executable) will hash the elaborated type instead, so
whitespace-only edits don't show up.
"""
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
ALLOWED_FILES = ROOT / "trust/allowed-axiom-files.txt"
# Output path is overridable for the check-baseline temp-file flow.
BASELINE = Path(sys.argv[1]) if len(sys.argv) > 1 else (ROOT / "trust/baseline-axioms.txt")

# Match the start of an axiom-shaped declaration:
#   axiom <name>
#   opaque <name>
#   constant <name>
DECL_HEAD = re.compile(
    r"^(?P<indent>\s*)(?P<kind>axiom|opaque|constant)\s+(?P<name>[A-Za-z_][A-Za-z0-9_']*)"
)
# Lines that mark the start of a NEW top-level decl (we stop the block here).
NEXT_DECL = re.compile(
    r"^\s*(axiom|opaque|constant|theorem|lemma|def|example|abbrev|"
    r"namespace|end\b|class|instance|structure|inductive|@\[)"
)


def read_allowed() -> list[Path]:
    out = []
    for raw in ALLOWED_FILES.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        out.append(ROOT / line)
    return out


def parse_blocks(path: Path):
    """Yield (kind, name, start_line_1based, block_text) tuples.

    Skips Lean block comments `/- ... -/` and doc-comments `/-- ... -/`
    (which nest), and line comments `--`. Without this, prose like
    "the axiom directly asserts..." inside a docstring is misparsed
    as a top-level declaration.
    """
    text = path.read_text()
    lines = text.splitlines(keepends=False)
    i = 0
    block_depth = 0  # Lean block comments nest

    while i < len(lines):
        ln = lines[i]
        # Update comment depth for THIS line, character by character
        # (cheaply: count occurrences). Lean comments: `/-` opens, `-/` closes.
        # Order-of-occurrence matters; do a tiny scan.
        idx = 0
        L = len(ln)
        line_starts_in_comment = block_depth > 0
        while idx < L - 1:
            if block_depth > 0:
                if ln[idx] == "-" and ln[idx + 1] == "/":
                    block_depth -= 1
                    idx += 2
                    continue
            else:
                if ln[idx] == "/" and ln[idx + 1] == "-":
                    block_depth += 1
                    idx += 2
                    continue
                if ln[idx] == "-" and ln[idx + 1] == "-":
                    # line comment: skip rest of line
                    break
            idx += 1
        # If the line started inside a comment, skip it for decl detection.
        if line_starts_in_comment:
            i += 1
            continue
        m = DECL_HEAD.match(ln)
        if not m:
            i += 1
            continue
        # Defensive: also require that the matched line is not inside a
        # comment that opened ON this line.
        # We already scanned; if block_depth ended >0, the decl-head text
        # is part of a doc-comment that started later on the line — but
        # that's exotic. Skip if uncertain.
        kind = m.group("kind")
        name = m.group("name")
        start = i + 1
        block = [ln]
        j = i + 1
        # Consume the block until the next blank line or top-level decl.
        # Don't bother tracking comment depth inside the block — once
        # the block parses we hash whatever's there.
        while j < len(lines):
            ln_j = lines[j]
            if ln_j.strip() == "":
                break
            if NEXT_DECL.match(ln_j) and not ln_j.startswith(" "):
                break
            block.append(ln_j)
            j += 1
        text_block = "\n".join(block).rstrip() + "\n"
        yield (kind, name, start, text_block)
        i = j


def main() -> int:
    allowed = read_allowed()
    records = []
    for f in allowed:
        if not f.exists():
            print(f"warning: allowed file does not exist: {f}", file=sys.stderr)
            continue
        rel = str(f.relative_to(ROOT))
        for kind, name, start, block in parse_blocks(f):
            digest = hashlib.sha256(block.encode("utf-8")).hexdigest()[:16]
            records.append((rel, start, kind, name, digest))
    records.sort(key=lambda r: (r[0], r[1]))

    with BASELINE.open("w") as fp:
        fp.write(
            "# Auto-generated by trust/scripts/regenerate.py — do not edit by hand.\n"
            "# Run `trust/scripts/regenerate.sh` after any legitimate trust-surface change.\n"
            "# Format: <sha256-prefix>  <file>:<line>  <kind>  <name>\n"
            "#\n"
            f"# Total entries: {len(records)}\n"
            "#\n"
        )
        for rel, start, kind, name, digest in records:
            fp.write(f"{digest}  {rel}:{start}  {kind:8s}  {name}\n")

    try:
        rel = BASELINE.relative_to(ROOT)
    except ValueError:
        rel = BASELINE
    print(f"wrote {len(records)} entries to {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
