#!/usr/bin/env python3
"""Render the active theorem-side DefectId count.

This is deliberately separate from the axiom baselines: a defect exclusion is
a visible claim boundary, not trusted code. The checked count makes additions
to that boundary explicit in review without turning the ledger into an
allowlist.
"""

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "ZiskFv/Compliance/Defects.lean"

source = SOURCE.read_text(encoding="utf-8")
try:
    body = source.split("inductive DefectId where", 1)[1].split("deriving", 1)[0]
except IndexError as exc:
    raise SystemExit("could not find DefectId declaration") from exc

count = len(re.findall(r"^\s*\|\s+[A-Za-z_][A-Za-z0-9_]*\s*$", body, re.MULTILINE))
if count == 0:
    raise SystemExit("DefectId has no constructors")

print("# Active theorem-side DefectId count; generated by")
print("# trust/scripts/regenerate-defect-count.py")
print(count)
