import ZiskFv.AirsClean.ArithMul.Spec
import Clean.Circuit.Basic
import ZiskFv.Channels.OperationBus

/-!
# ArithMul circuit operations (the `main` field of the Component)

The 9 boolean flag constraints on the Arith AIR's MUL view plus the
11 carry-chain constraints (constraints 6/7/8 + 31..38 from the
extraction layer), then the operation bus `OpBusChannel.push`.
Mirrors each `assertZero` call to a `constraint_N_every_row` body in
`build/extraction/Extraction/Arith.lean`, with `Circuit.main … (column := N)`
substituted by the corresponding named accessor on the `ArithMulRow`.

AUTO-GENERATED by `tools/pil-extract` (`clean-component` subcommand),
view-restricted to the MUL-mode constraint slice — do not hand-edit.
The bus push is reconstructed from the proves-side `gsum_debug_data`
hint (Arith AIR, `bus_id = 5000`) and is slot-for-slot faithful to
the hand-written reference `Airs/Arith/Mul.lean::opBus_row_Arith`.

The lookup against `ArithTable` (which enforces division of mode
flags into the actual MUL/DIV/MULU/etc. operation) is at the
opcode-equiv level, consuming the existing `arith_table_*`
trust-ledger axioms (class #6b) — it is **not** part of this
Component's `Spec`/`soundness`, so no `StaticTable` is built here.

## Trust note

No axioms. Pure operational declaration.
-/

namespace ZiskFv.AirsClean.ArithMul

open Goldilocks
open Circuit (assertZero)
open ZiskFv.Channels.OperationBus (OpBusChannel)

@[circuit_norm]
def main (row : Var ArithMulRow FGL) : Circuit FGL Unit := do
  -- 9 boolean flag constraints.
  assertZero (row.flags.na * (1 - row.flags.na))
  assertZero (row.flags.nb * (1 - row.flags.nb))
  assertZero (row.flags.nr * (1 - row.flags.nr))
  assertZero (row.flags.np * (1 - row.flags.np))
  assertZero (row.flags.sext * (1 - row.flags.sext))
  assertZero (row.flags.m32 * (1 - row.flags.m32))
  assertZero (row.flags.div * (1 - row.flags.div))
  assertZero (row.flags.main_div * (1 - row.flags.main_div))
  assertZero (row.flags.main_mul * (1 - row.flags.main_mul))
  -- Constraint 6: fab − ((1 − 2·na) − 2·nb + 4·na·nb) = 0.
  assertZero (row.carries.fab
    - ((1 - 2 * row.flags.na) - 2 * row.flags.nb
       + 4 * row.flags.na * row.flags.nb))
  -- Constraint 7: na_fb − na·(1 − 2·nb) = 0.
  assertZero (row.carries.na_fb - row.flags.na * (1 - 2 * row.flags.nb))
  -- Constraint 8: nb_fa − nb·(1 − 2·na) = 0.
  assertZero (row.carries.nb_fa - row.flags.nb * (1 - 2 * row.flags.na))
  -- Constraint 31.
  assertZero (row.carries.fab * row.chunks.a_0 * row.chunks.b_0
              - row.chunks.c_0
              + 2 * row.flags.np * row.chunks.c_0
              + row.flags.div * row.chunks.d_0
              - 2 * row.flags.nr * row.chunks.d_0
              - row.carries.carry_0 * 65536)
  -- Constraint 32.
  assertZero (row.carries.fab * row.chunks.a_1 * row.chunks.b_0
              + row.carries.fab * row.chunks.a_0 * row.chunks.b_1
              - row.chunks.c_1
              + 2 * row.flags.np * row.chunks.c_1
              + row.flags.div * row.chunks.d_1
              - 2 * row.flags.nr * row.chunks.d_1
              + row.carries.carry_0
              - row.carries.carry_1 * 65536)
  -- Constraint 33.
  assertZero (row.carries.fab * row.chunks.a_2 * row.chunks.b_0
              + row.carries.fab * row.chunks.a_1 * row.chunks.b_1
              + row.carries.fab * row.chunks.a_0 * row.chunks.b_2
              + row.chunks.a_0 * row.carries.nb_fa * row.flags.m32
              + row.chunks.b_0 * row.carries.na_fb * row.flags.m32
              - row.chunks.c_2
              + 2 * row.flags.np * row.chunks.c_2
              + row.flags.div * row.chunks.d_2
              - 2 * row.flags.nr * row.chunks.d_2
              - row.flags.np * row.flags.div * row.flags.m32
              + row.flags.nr * row.flags.m32
              + row.carries.carry_1
              - row.carries.carry_2 * 65536)
  -- Constraint 34.
  assertZero (row.carries.fab * row.chunks.a_3 * row.chunks.b_0
              + row.carries.fab * row.chunks.a_2 * row.chunks.b_1
              + row.carries.fab * row.chunks.a_1 * row.chunks.b_2
              + row.carries.fab * row.chunks.a_0 * row.chunks.b_3
              + row.chunks.a_1 * row.carries.nb_fa * row.flags.m32
              + row.chunks.b_1 * row.carries.na_fb * row.flags.m32
              - row.chunks.c_3
              + 2 * row.flags.np * row.chunks.c_3
              + row.flags.div * row.chunks.d_3
              - 2 * row.flags.nr * row.chunks.d_3
              + row.carries.carry_2
              - row.carries.carry_3 * 65536)
  -- Constraint 35.
  assertZero (row.carries.fab * row.chunks.a_3 * row.chunks.b_1
              + row.carries.fab * row.chunks.a_2 * row.chunks.b_2
              + row.carries.fab * row.chunks.a_1 * row.chunks.b_3
              + row.flags.na * row.flags.nb * row.flags.m32
              + row.chunks.b_0 * row.carries.na_fb * (1 - row.flags.m32)
              + row.chunks.a_0 * row.carries.nb_fa * (1 - row.flags.m32)
              - row.flags.np * row.flags.m32 * (1 - row.flags.div)
              - row.flags.np * (1 - row.flags.m32) * row.flags.div
              + row.flags.nr * (1 - row.flags.m32)
              - row.chunks.d_0 * (1 - row.flags.div)
              + 2 * row.flags.np * row.chunks.d_0 * (1 - row.flags.div)
              + row.carries.carry_3
              - row.carries.carry_4 * 65536)
  -- Constraint 36.
  assertZero (row.carries.fab * row.chunks.a_3 * row.chunks.b_2
              + row.carries.fab * row.chunks.a_2 * row.chunks.b_3
              + row.chunks.b_1 * row.carries.na_fb * (1 - row.flags.m32)
              + row.chunks.a_1 * row.carries.nb_fa * (1 - row.flags.m32)
              - row.chunks.d_1 * (1 - row.flags.div)
              + row.chunks.d_1 * 2 * row.flags.np * (1 - row.flags.div)
              + row.carries.carry_4
              - row.carries.carry_5 * 65536)
  -- Constraint 37.
  assertZero (row.carries.fab * row.chunks.a_3 * row.chunks.b_3
              + row.chunks.a_2 * row.carries.nb_fa * (1 - row.flags.m32)
              + row.chunks.b_2 * row.carries.na_fb * (1 - row.flags.m32)
              - row.chunks.d_2 * (1 - row.flags.div)
              + 2 * row.flags.np * row.chunks.d_2 * (1 - row.flags.div)
              + row.carries.carry_5
              - row.carries.carry_6 * 65536)
  -- Constraint 38.
  assertZero (65536 * row.flags.na * row.flags.nb * (1 - row.flags.m32)
              + row.chunks.a_3 * row.carries.nb_fa * (1 - row.flags.m32)
              + row.chunks.b_3 * row.carries.na_fb * (1 - row.flags.m32)
              - 65536 * row.flags.np * (1 - row.flags.div) * (1 - row.flags.m32)
              - row.chunks.d_3 * (1 - row.flags.div)
              + 2 * row.flags.np * row.chunks.d_3 * (1 - row.flags.div)
              + row.carries.carry_6)
  -- Bus emission: Arith pushes its proves-side tuple onto operation bus 5000.
  -- Reconstructed from the proves-side `gsum_debug_data` hint;
  -- slot-for-slot faithful to `Airs/Arith/Mul.lean::opBus_row_Arith`
  -- (the `multiplicity` slot is carried separately by Clean's channel).
  OpBusChannel.push
    { op := row.flags.op
      a_lo := ((row.chunks.a_0) + (row.chunks.a_1 * 65536))
      a_hi := ((row.chunks.a_2) + (row.chunks.a_3 * 65536))
      b_lo := ((row.chunks.b_0) + (row.chunks.b_1 * 65536))
      b_hi := ((row.chunks.b_2) + (row.chunks.b_3 * 65536))
      c_lo := ((row.chunks.c_0) + (row.chunks.c_1 * 65536))
      c_hi := row.flags.bus_res1
      flag := 0
      main_step := 0
      extended_arg := 0
      extra_args_0 := 0 }

/-- The elaborated circuit for ArithMul's `main` — 20 `assertZero`
    constraints (9 boolean flags + 11 carry-chain) + the op-bus push,
    no fresh witnesses (`localLength = 0`, `unit` output). Lives here
    (next to `main`) rather than in `Circuit.lean` so the completeness
    axiom (`Completeness.lean`, whose type mentions this) can be
    declared without an import cycle. -/
@[reducible] def arithMulElaborated : ElaboratedCircuit FGL ArithMulRow unit where
  name := "ArithMul"
  main := main
  localLength _ := 0
  output _ _ := ()
  channelsWithRequirements := [OpBusChannel.toRaw]

end ZiskFv.AirsClean.ArithMul
