import ZiskFv.AirsClean.ArithMul.Spec
import ZiskFv.AirsClean.ArithTable
import ZiskFv.AirsClean.RangeTables
import Clean.Circuit.Basic
import ZiskFv.Channels.OperationBus

/-!
# ArithMul circuit operations (the `main` field of the Component)

The 11 MUL-mode carry-chain constraints (named-form `6/7/8` + `31..38`
from the extraction layer — exactly `Airs/Arith/Mul.lean::mul_carry_chain_holds`)
of ZisK's Arith AIR, then the operation bus `OpBusChannel.push`.
Mirrors each `assertZero` call to a `constraint_N_every_row` body in
`build/extraction/Extraction/Arith.lean`, with `Circuit.main … (column := N)`
substituted by the corresponding named accessor on the `ArithMulRow`.

AUTO-GENERATED by `tools/pil-extract` (`clean-component` subcommand),
view-restricted to the MUL-mode carry-chain constraint slice — do not
hand-edit. A narrower faithful view is sound: it constrains a subset
of the AIR's `assertZero`s. The bus push is reconstructed from the
proves-side `gsum_debug_data` hint (Arith AIR, `bus_id = 5000`) and is
slot-for-slot faithful to `Airs/Arith/Mul.lean::opBus_row_Arith`.

The Arith AIR's 9 boolean flag constraints and the lookup against the
74-row `ArithTable` are at the opcode-equiv level — the boolean flags
via `Airs/Arith/Mul.lean::mul_mode_booleans`, the ArithTable via the
`arith_table_*` class-#6b axioms. Neither is part of this Component's
`Spec`/`soundness`, so no `StaticTable` is built here.

## Trust note

No axioms. Pure operational declaration.
-/

namespace ZiskFv.AirsClean.ArithMul

open Goldilocks
open Circuit (assertZero lookup)
open ZiskFv.AirsClean.RangeTables
open ZiskFv.Channels.OperationBus (OpBusChannel OpBusMessage)

/-- Primary MUL/MULW op-bus message: low result in the `c[]` chunks. -/
@[reducible]
def primaryOpBusMessageExpr (row : Var ArithMulRow FGL) :
    OpBusMessage (Expression FGL) :=
  { op := row.flags.op
    a_lo := row.chunks.a_0 + row.chunks.a_1 * 65536
    a_hi := row.chunks.a_2 + row.chunks.a_3 * 65536
    b_lo := row.chunks.b_0 + row.chunks.b_1 * 65536
    b_hi := row.chunks.b_2 + row.chunks.b_3 * 65536
    c_lo := row.chunks.c_0 + row.chunks.c_1 * 65536
    c_hi := row.flags.bus_res1
    flag := 0
    main_step := 0
    extended_arg := 0
    extra_args_0 := 0 }

/-- Secondary MULH/MULHU/MULHSU op-bus message: high result in `d[]`. -/
@[reducible]
def secondaryOpBusMessageExpr (row : Var ArithMulRow FGL) :
    OpBusMessage (Expression FGL) :=
  { op := row.flags.op
    a_lo := row.chunks.a_0 + row.chunks.a_1 * 65536
    a_hi := row.chunks.a_2 + row.chunks.a_3 * 65536
    b_lo := row.chunks.b_0 + row.chunks.b_1 * 65536
    b_hi := row.chunks.b_2 + row.chunks.b_3 * 65536
    c_lo := row.chunks.d_0 + row.chunks.d_1 * 65536
    c_hi := row.flags.bus_res1
    flag := 0
    main_step := 0
    extended_arg := 0
    extra_args_0 := 0 }

@[circuit_norm]
def main (row : Var ArithMulRow FGL) : Circuit FGL Unit := do
  -- Constraint 6: fab − ((1 − 2·na) − 2·nb + 4·na·nb) = 0.
  assertZero (row.carries.fab
    - ((1 - 2 * row.flags.na) - 2 * row.flags.nb
       + 4 * row.flags.na * row.flags.nb))
  -- Constraint 7: na_fb − na·(1 − 2·nb) = 0.
  assertZero (row.carries.na_fb - row.flags.na * (1 - 2 * row.flags.nb))
  -- Constraint 8: nb_fa − nb·(1 − 2·na) = 0.
  assertZero (row.carries.nb_fa - row.flags.nb * (1 - 2 * row.flags.na))
  -- Constraint 31.
  assertZero (row.carries.fab * row.chunks.a_0 * row.chunks.b_0
              - row.chunks.c_0
              + 2 * row.flags.np * row.chunks.c_0
              + row.flags.div * row.chunks.d_0
              - 2 * row.flags.nr * row.chunks.d_0
              - row.carries.carry_0 * 65536)
  -- Constraint 32.
  assertZero (row.carries.fab * row.chunks.a_1 * row.chunks.b_0
              + row.carries.fab * row.chunks.a_0 * row.chunks.b_1
              - row.chunks.c_1
              + 2 * row.flags.np * row.chunks.c_1
              + row.flags.div * row.chunks.d_1
              - 2 * row.flags.nr * row.chunks.d_1
              + row.carries.carry_0
              - row.carries.carry_1 * 65536)
  -- Constraint 33.
  assertZero (row.carries.fab * row.chunks.a_2 * row.chunks.b_0
              + row.carries.fab * row.chunks.a_1 * row.chunks.b_1
              + row.carries.fab * row.chunks.a_0 * row.chunks.b_2
              + row.chunks.a_0 * row.carries.nb_fa * row.flags.m32
              + row.chunks.b_0 * row.carries.na_fb * row.flags.m32
              - row.chunks.c_2
              + 2 * row.flags.np * row.chunks.c_2
              + row.flags.div * row.chunks.d_2
              - 2 * row.flags.nr * row.chunks.d_2
              - row.flags.np * row.flags.div * row.flags.m32
              + row.flags.nr * row.flags.m32
              + row.carries.carry_1
              - row.carries.carry_2 * 65536)
  -- Constraint 34.
  assertZero (row.carries.fab * row.chunks.a_3 * row.chunks.b_0
              + row.carries.fab * row.chunks.a_2 * row.chunks.b_1
              + row.carries.fab * row.chunks.a_1 * row.chunks.b_2
              + row.carries.fab * row.chunks.a_0 * row.chunks.b_3
              + row.chunks.a_1 * row.carries.nb_fa * row.flags.m32
              + row.chunks.b_1 * row.carries.na_fb * row.flags.m32
              - row.chunks.c_3
              + 2 * row.flags.np * row.chunks.c_3
              + row.flags.div * row.chunks.d_3
              - 2 * row.flags.nr * row.chunks.d_3
              + row.carries.carry_2
              - row.carries.carry_3 * 65536)
  -- Constraint 35.
  assertZero (row.carries.fab * row.chunks.a_3 * row.chunks.b_1
              + row.carries.fab * row.chunks.a_2 * row.chunks.b_2
              + row.carries.fab * row.chunks.a_1 * row.chunks.b_3
              + row.flags.na * row.flags.nb * row.flags.m32
              + row.chunks.b_0 * row.carries.na_fb * (1 - row.flags.m32)
              + row.chunks.a_0 * row.carries.nb_fa * (1 - row.flags.m32)
              - row.flags.np * row.flags.m32 * (1 - row.flags.div)
              - row.flags.np * (1 - row.flags.m32) * row.flags.div
              + row.flags.nr * (1 - row.flags.m32)
              - row.chunks.d_0 * (1 - row.flags.div)
              + 2 * row.flags.np * row.chunks.d_0 * (1 - row.flags.div)
              + row.carries.carry_3
              - row.carries.carry_4 * 65536)
  -- Constraint 36.
  assertZero (row.carries.fab * row.chunks.a_3 * row.chunks.b_2
              + row.carries.fab * row.chunks.a_2 * row.chunks.b_3
              + row.chunks.b_1 * row.carries.na_fb * (1 - row.flags.m32)
              + row.chunks.a_1 * row.carries.nb_fa * (1 - row.flags.m32)
              - row.chunks.d_1 * (1 - row.flags.div)
              + row.chunks.d_1 * 2 * row.flags.np * (1 - row.flags.div)
              + row.carries.carry_4
              - row.carries.carry_5 * 65536)
  -- Constraint 37.
  assertZero (row.carries.fab * row.chunks.a_3 * row.chunks.b_3
              + row.chunks.a_2 * row.carries.nb_fa * (1 - row.flags.m32)
              + row.chunks.b_2 * row.carries.na_fb * (1 - row.flags.m32)
              - row.chunks.d_2 * (1 - row.flags.div)
              + 2 * row.flags.np * row.chunks.d_2 * (1 - row.flags.div)
              + row.carries.carry_5
              - row.carries.carry_6 * 65536)
  -- Constraint 38.
  assertZero (65536 * row.flags.na * row.flags.nb * (1 - row.flags.m32)
              + row.chunks.a_3 * row.carries.nb_fa * (1 - row.flags.m32)
              + row.chunks.b_3 * row.carries.na_fb * (1 - row.flags.m32)
              - 65536 * row.flags.np * (1 - row.flags.div) * (1 - row.flags.m32)
              - row.chunks.d_3 * (1 - row.flags.div)
              + 2 * row.flags.np * row.chunks.d_3 * (1 - row.flags.div)
              + row.carries.carry_6)
  -- Bus emission: Arith pushes its proves-side tuple onto operation bus 5000.
  -- Reconstructed from the proves-side `gsum_debug_data` hint;
  -- slot-for-slot faithful to `Airs/Arith/Mul.lean::opBus_row_Arith`
  -- (the `multiplicity` slot is carried separately by Clean's channel).
  OpBusChannel.push (primaryOpBusMessageExpr row)


/-- Lookup-aware ArithMul circuit path. This appends the full 15-column
    `arith_table_assumes` ROM lookup and the `bus_res1` mux constraint
    (constraint 46, `arith.pil:262`) after the existing carry-chain/op-bus
    component body. The current load-bearing carry-chain component remains
    unchanged until Compliance supplies this lookup evidence globally. -/
@[circuit_norm]
def mainWithArithTable (row : Var ArithMulRow FGL) : Circuit FGL Unit := do
  main row
  -- Constraint 46 (`arith.pil:262`): bus_res1 − (sext·4294967295 +
  --   (1 − m32)·((1 − main_mul − main_div)·(d_2 + d_3·65536)
  --              + main_mul·(c_2 + c_3·65536)
  --              + main_div·(a_2 + a_3·65536))) = 0.
  -- Mirror of `constraint_46_every_row` in `Extraction/Arith.lean:165`.
  assertZero (row.flags.bus_res1
    - (row.flags.sext * 4294967295
      + (1 - row.flags.m32) * (
          (1 - row.flags.main_mul - row.flags.main_div)
              * (row.chunks.d_2 + row.chunks.d_3 * 65536)
          + row.flags.main_mul * (row.chunks.c_2 + row.chunks.c_3 * 65536)
          + row.flags.main_div
              * (row.chunks.a_2 + row.chunks.a_3 * 65536))))
  lookup (Table.fromStatic ArithTable.arithTable) (arithTableRow row)
  -- Sixteen `bits(16)` chunk column range lookups (`arith.pil:18-21`).
  -- These are shared across signed and unsigned Arith rows, so they are
  -- sound to include in the SHARED component: real arith rows always
  -- have 16-bit a/b/c/d chunks.
  lookup (Table.fromStatic rangeTable16) row.chunks.a_0
  lookup (Table.fromStatic rangeTable16) row.chunks.a_1
  lookup (Table.fromStatic rangeTable16) row.chunks.a_2
  lookup (Table.fromStatic rangeTable16) row.chunks.a_3
  lookup (Table.fromStatic rangeTable16) row.chunks.b_0
  lookup (Table.fromStatic rangeTable16) row.chunks.b_1
  lookup (Table.fromStatic rangeTable16) row.chunks.b_2
  lookup (Table.fromStatic rangeTable16) row.chunks.b_3
  lookup (Table.fromStatic rangeTable16) row.chunks.c_0
  lookup (Table.fromStatic rangeTable16) row.chunks.c_1
  lookup (Table.fromStatic rangeTable16) row.chunks.c_2
  lookup (Table.fromStatic rangeTable16) row.chunks.c_3
  lookup (Table.fromStatic rangeTable16) row.chunks.d_0
  lookup (Table.fromStatic rangeTable16) row.chunks.d_1
  lookup (Table.fromStatic rangeTable16) row.chunks.d_2
  lookup (Table.fromStatic rangeTable16) row.chunks.d_3
  -- Seven `ARITH_RANGE_CARRY` signed-carry range lookups (`arith.pil:17,280`).
  -- `carry[]` is declared as `bits(64, signed)` and range-checked with the
  -- single ARITH_RANGE_CARRY type = the signed-carry range. The
  -- `signedCarryRangeTable.Spec t = (t.val < 983041 ∨ GL_prime − 983040 ≤ t.val)`
  -- holds for EVERY Arith row: unsigned carries are < 2^17 < 983041 (first
  -- disjunct) and signed carries satisfy the disjunction by construction.
  -- Sound to include in the SHARED component — no vacuity.
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_0
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_1
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_2
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_3
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_4
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_5
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_6

/-- Lookup-aware ArithMul path for the sixteen `bits(16)` chunk columns.
    This models the column-level PIL declarations at `arith.pil:18-21`.
    It is kept separate from the carry-chain component and from the
    `arith_range_table_assumes` lookups so consumers can retire the generic
    range-bus dependency slice by slice. -/
@[circuit_norm]
def mainWithChunkRanges (row : Var ArithMulRow FGL) : Circuit FGL Unit := do
  main row
  lookup (Table.fromStatic rangeTable16) row.chunks.a_0
  lookup (Table.fromStatic rangeTable16) row.chunks.a_1
  lookup (Table.fromStatic rangeTable16) row.chunks.a_2
  lookup (Table.fromStatic rangeTable16) row.chunks.a_3
  lookup (Table.fromStatic rangeTable16) row.chunks.b_0
  lookup (Table.fromStatic rangeTable16) row.chunks.b_1
  lookup (Table.fromStatic rangeTable16) row.chunks.b_2
  lookup (Table.fromStatic rangeTable16) row.chunks.b_3
  lookup (Table.fromStatic rangeTable16) row.chunks.c_0
  lookup (Table.fromStatic rangeTable16) row.chunks.c_1
  lookup (Table.fromStatic rangeTable16) row.chunks.c_2
  lookup (Table.fromStatic rangeTable16) row.chunks.c_3
  lookup (Table.fromStatic rangeTable16) row.chunks.d_0
  lookup (Table.fromStatic rangeTable16) row.chunks.d_1
  lookup (Table.fromStatic rangeTable16) row.chunks.d_2
  lookup (Table.fromStatic rangeTable16) row.chunks.d_3

/-- Lookup-aware ArithMul path for the seven unsigned carry columns. This
    models the `bits(17)` range needed by unsigned MUL/MULHU carry-chain
    consumers without using the legacy generic range bus. -/
@[circuit_norm]
def mainWithUnsignedCarryRanges (row : Var ArithMulRow FGL) : Circuit FGL Unit := do
  main row
  lookup (Table.fromStatic rangeTable17) row.carries.carry_0
  lookup (Table.fromStatic rangeTable17) row.carries.carry_1
  lookup (Table.fromStatic rangeTable17) row.carries.carry_2
  lookup (Table.fromStatic rangeTable17) row.carries.carry_3
  lookup (Table.fromStatic rangeTable17) row.carries.carry_4
  lookup (Table.fromStatic rangeTable17) row.carries.carry_5
  lookup (Table.fromStatic rangeTable17) row.carries.carry_6

/-- Lookup-aware ArithMul path for the seven signed/W carry columns. This
    models the `ARITH_RANGE_CARRY` signed-range membership used by signed
    MUL-family and W-mode carry-chain consumers without using the legacy
    signed range-bus axiom. -/
@[circuit_norm]
def mainWithSignedCarryRanges (row : Var ArithMulRow FGL) : Circuit FGL Unit := do
  main row
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_0
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_1
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_2
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_3
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_4
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_5
  lookup (Table.fromStatic signedCarryRangeTable) row.carries.carry_6


/-- Lookup-aware elaboration for the next C3/C4 stage. It is intentionally
    separate from `arithMulElaborated` so existing carry-chain consumers do
    not acquire a new caller-supplied lookup promise before Compliance has
    a global source for it. -/
@[reducible] def arithMulWithArithTableElaborated :
    ElaboratedCircuit FGL ArithMulRow unit where
  name := "ArithMulWithArithTable"
  main := mainWithArithTable
  localLength _ := 0
  output _ _ := ()
  channelsWithRequirements := [OpBusChannel.toRaw]

/-- Lookup-aware elaboration exposing the chunk-column range lookups from
    `mainWithChunkRanges`. Kept out of the base carry-chain component so no
    existing theorem gains a new premise implicitly. -/
@[reducible] def arithMulWithChunkRangesElaborated :
    ElaboratedCircuit FGL ArithMulRow unit where
  name := "ArithMulWithChunkRanges"
  main := mainWithChunkRanges
  localLength _ := 0
  output _ _ := ()
  channelsWithRequirements := [OpBusChannel.toRaw]

/-- Lookup-aware elaboration exposing unsigned carry range lookups. Kept
    separate from `arithMulElaborated` and chunk ranges so consumers opt in
    only when replacing a concrete legacy range-bus dependency. -/
@[reducible] def arithMulWithUnsignedCarryRangesElaborated :
    ElaboratedCircuit FGL ArithMulRow unit where
  name := "ArithMulWithUnsignedCarryRanges"
  main := mainWithUnsignedCarryRanges
  localLength _ := 0
  output _ _ := ()
  channelsWithRequirements := [OpBusChannel.toRaw]

/-- Lookup-aware elaboration exposing signed/W carry range lookups. -/
@[reducible] def arithMulWithSignedCarryRangesElaborated :
    ElaboratedCircuit FGL ArithMulRow unit where
  name := "ArithMulWithSignedCarryRanges"
  main := mainWithSignedCarryRanges
  localLength _ := 0
  output _ _ := ()
  channelsWithRequirements := [OpBusChannel.toRaw]


/-- The elaborated circuit for ArithMul's `main` — 11 `assertZero`
    carry-chain constraints + the op-bus push, no fresh witnesses
    (`localLength = 0`, `unit` output). Lives here (next to `main`) so
    the `Circuit.lean` wrapper can reuse it without an import cycle. -/
@[reducible] def arithMulElaborated : ElaboratedCircuit FGL ArithMulRow unit where
  name := "ArithMul"
  main := main
  localLength _ := 0
  output _ _ := ()
  channelsWithRequirements := [OpBusChannel.toRaw]
  exposedChannels row _ :=
    expose OpBusChannel [OpBusChannel.pushed (primaryOpBusMessageExpr row)]
  channelsLawful := by
    simp only [circuit_norm, main, primaryOpBusMessageExpr, OpBusChannel]

end ZiskFv.AirsClean.ArithMul
