import ZiskFv.Completeness.Rv64im.SailDecode.Domain
import ZiskFv.Completeness.Rv64im.SailDecode.ConcatShapes
import ZiskFv.Completeness.Rv64im.SailDecode.EncodeFacts
import ZiskFv.Completeness.Rv64im.SailDecode.Containment

/-!
# Sail-derived RV64IM decode domain

This module is the checked-in Sail-domain bridge for RV completeness.  It names
the Sail raw-decode domain from the generated Sail decoder and proves the first
non-FENCE containment bridges into the existing RV64IM raw-shape surface.

The ZisK-side predicates still live behind `Rv.Interface`: the concrete
production decoder/lowering predicates are generated by the Aeneas harness.

This file is a thin aggregator: the declarations now live in the
`ZiskFv.Completeness.Rv64im.SailDecode.*` parts, re-exported here so the module
name `ZiskFv.Completeness.Rv64im.SailDecode` continues to provide every
declaration to existing consumers.
-/
