import Mathlib
import ZiskFv.Fundamentals.Goldilocks
import ZiskFv.Fundamentals.Transpiler

/-!
# Extracted arith_table data (Phase 6 Track P).

Mechanical extraction of `vendor/zisk/state-machines/arith/src/
arith_table_data.rs::ARITH_TABLE` (74 rows). The Rust constant is
itself generated by running PIL with `generate_table = 1` per
`arith_table.pil:228-253`. We hand-transcribe here to avoid
extending the Rust extractor; correctness is by-eye comparison
against the .rs source.

FLAGS column decoded per `arith_table.pil:209-211`:
  m32, div, na, nb, np, nr, sext, div_by_zero, div_overflow,
  main_mul, main_div, signed.
-/

namespace ZiskFv.Extraction.ArithTable

open ZiskFv.Trusted

/-- One row of `arith_table` — the structured form. -/
structure ArithTableRow where
  op : FGL
  m32 : Nat
  div : Nat
  na : Nat
  nb : Nat
  np : Nat
  nr : Nat
  sext : Nat
  div_by_zero : Nat
  div_overflow : Nat
  main_mul : Nat
  main_div : Nat
  signed : Nat
  range_ab : Nat
  range_cd : Nat
  deriving DecidableEq

/-- The 74-row arith_table extracted from
    `vendor/zisk/state-machines/arith/src/arith_table_data.rs`. -/
def arith_table : List ArithTableRow := [
  ⟨OP_MULU, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0⟩,
  ⟨OP_MULUH, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0⟩,
  ⟨OP_MULSUH, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1⟩,
  ⟨OP_MULSUH, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 6, 1⟩,
  ⟨OP_MULSUH, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 6, 2⟩,
  ⟨OP_MUL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 4, 1⟩,
  ⟨OP_MUL, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 7, 1⟩,
  ⟨OP_MUL, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 5, 1⟩,
  ⟨OP_MUL, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 8, 1⟩,
  ⟨OP_MUL, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 7, 2⟩,
  ⟨OP_MUL, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 5, 2⟩,
  ⟨OP_MULH, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 1⟩,
  ⟨OP_MULH, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 7, 1⟩,
  ⟨OP_MULH, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 5, 1⟩,
  ⟨OP_MULH, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 8, 1⟩,
  ⟨OP_MULH, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 7, 2⟩,
  ⟨OP_MULH, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 5, 2⟩,
  ⟨OP_MUL_W, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 11⟩,
  ⟨OP_MUL_W, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 14⟩,
  ⟨OP_DIVU, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0⟩,
  ⟨OP_DIVU, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0⟩,
  ⟨OP_REMU, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0⟩,
  ⟨OP_REMU, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0⟩,
  ⟨OP_DIV, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 4, 4⟩,
  ⟨OP_DIV, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 5, 4⟩,
  ⟨OP_DIV, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 8, 4⟩,
  ⟨OP_DIV, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 7, 7⟩,
  ⟨OP_DIV, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 5, 7⟩,
  ⟨OP_DIV, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 4, 8⟩,
  ⟨OP_DIV, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 7, 8⟩,
  ⟨OP_DIV, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 5, 8⟩,
  ⟨OP_DIV, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 7, 4⟩,
  ⟨OP_DIV, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 7, 8⟩,
  ⟨OP_DIV, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 8, 7⟩,
  ⟨OP_REM, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4, 4⟩,
  ⟨OP_REM, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 5, 4⟩,
  ⟨OP_REM, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 8, 4⟩,
  ⟨OP_REM, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 7, 7⟩,
  ⟨OP_REM, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 5, 7⟩,
  ⟨OP_REM, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 4, 8⟩,
  ⟨OP_REM, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 7, 8⟩,
  ⟨OP_REM, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 5, 8⟩,
  ⟨OP_REM, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 7, 4⟩,
  ⟨OP_REM, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 7, 8⟩,
  ⟨OP_REM, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 8, 7⟩,
  ⟨OP_DIVU_W, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 11, 0⟩,
  ⟨OP_DIVU_W, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 14, 0⟩,
  ⟨OP_DIVU_W, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 14, 0⟩,
  ⟨OP_REMU_W, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9⟩,
  ⟨OP_REMU_W, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 10⟩,
  ⟨OP_REMU_W, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 9⟩,
  ⟨OP_REMU_W, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 10⟩,
  ⟨OP_DIV_W, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 12, 12⟩,
  ⟨OP_DIV_W, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 13, 12⟩,
  ⟨OP_DIV_W, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 13, 15⟩,
  ⟨OP_DIV_W, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 12, 16⟩,
  ⟨OP_DIV_W, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 13, 16⟩,
  ⟨OP_DIV_W, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 16, 12⟩,
  ⟨OP_DIV_W, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 15, 15⟩,
  ⟨OP_DIV_W, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 15, 16⟩,
  ⟨OP_DIV_W, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 15, 12⟩,
  ⟨OP_DIV_W, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 15, 16⟩,
  ⟨OP_DIV_W, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 16, 15⟩,
  ⟨OP_REM_W, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 12, 12⟩,
  ⟨OP_REM_W, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 13, 12⟩,
  ⟨OP_REM_W, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 16, 12⟩,
  ⟨OP_REM_W, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 15, 15⟩,
  ⟨OP_REM_W, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 13, 15⟩,
  ⟨OP_REM_W, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 12, 16⟩,
  ⟨OP_REM_W, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 15, 16⟩,
  ⟨OP_REM_W, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 13, 16⟩,
  ⟨OP_REM_W, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 15, 12⟩,
  ⟨OP_REM_W, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 15, 16⟩,
  ⟨OP_REM_W, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 16, 15⟩
]

end ZiskFv.Extraction.ArithTable
