#!/usr/bin/env python3
"""Zero-dependency protobuf wire-format decoder for `build/zisk.pilout`.

Reader half of the extractor round-trip gate (issue #303). Hand-rolled from the
wire format rather than generated by `protoc`, for two reasons: the checker must
run on a bare `python3` with nothing installed, and a decoder sharing no code
with the Rust `prost` decoder the extractor uses cannot share a bug with it, so
a decode-side distortion cannot cancel against an extraction-side one.

Wire format, in full: a message body is a sequence of records, each a varint key
`(field_number << 3) | wire_type` followed by a payload whose shape depends on
the wire type -- 0 varint, 1 fixed 64-bit, 2 length-delimited (a varint byte
count then that many bytes), 5 fixed 32-bit. Wire types 3 and 4 (proto2 groups)
are not emitted by proto3 and are rejected. That is the whole generic layer: it
yields `field_number -> [raw value]`, an `int` for wire types 0/1/5 and `bytes`
for wire type 2, dropping no field number, including undeclared ones.

Decisions the wire format itself does not determine:

* Field meaning comes from tables transcribed by hand from
  `tools/pil-extract/proto/pilout.proto`. The "known" set per message is *every*
  field number that .proto declares, not just the ones read here, so an entry in
  `PilOut.unknown_fields()` means the file carries data this tree's schema does
  not describe -- drift the gate must surface, not swallow.
* proto3 omits scalars holding the default, so an absent scalar reads back as
  0 / b"" / "". Repeated numeric fields may be packed (one length-delimited blob
  of back-to-back varints) or unpacked (one record each); which one a writer
  chose is not something a reader may assume, so both are accepted.
* `sint32` fields are zigzag-encoded: signed n travels as `(n << 1) ^ (n >> 31)`.
  Read as a plain varint it yields a wrong, always non-negative number. The
  zigzag fields are exactly the four `rowOffset`s listed in `ZIGZAG_FIELDS` --
  precisely what separates a current-row reference from a next-row one, so
  misreading them would quietly invalidate the whole round-trip.
* `PilOut.baseField` is bytes with no declared byte order, so the order is
  calibrated from the file: whichever of the big- and little-endian readings
  equals the Goldilocks characteristic wins, and loading fails if neither does.
  `base_field_calibration` also reports whether the two readings differ, i.e.
  whether the test discriminates at all. The calibrated order is then what
  `decode_constant` applies to `Operand.Constant.value`.

Public API: `load(path) -> PilOut`; `PilOut.airs()`, `.num_challenges`,
`.base_field_prime`, `.base_field_byte_order`, `.symbols`, `.decode_constant()`,
`.unknown_fields()`; `Air.constraints/.expressions/.stage_widths/...`;
`Constraint.kind/.expression_idx/.debug_line/.offset_min/.offset_max`.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

GOLDILOCKS_PRIME = (1 << 64) - (1 << 32) + 1

WIRE_VARINT = 0
WIRE_64BIT = 1
WIRE_LEN = 2
WIRE_32BIT = 5


class WireFormatError(Exception):
    """The byte stream is not well-formed protobuf."""


class SchemaError(Exception):
    """The bytes decode, but do not fit the transcribed .proto schema."""


# ---------------------------------------------------------------- wire layer


def read_varint(buf: bytes, pos: int) -> tuple[int, int]:
    """Read a base-128 varint at `pos`; return (value, next position)."""
    result = 0
    shift = 0
    start = pos
    while True:
        if pos >= len(buf):
            raise WireFormatError(f"truncated varint at offset {start}")
        byte = buf[pos]
        pos += 1
        result |= (byte & 0x7F) << shift
        if byte < 0x80:
            return result, pos
        shift += 7
        if shift > 63:
            raise WireFormatError(f"varint exceeds 10 bytes at offset {start}")


def zigzag_decode(value: int) -> int:
    """Undo zigzag encoding; used by the sint32 fields only."""
    return (value >> 1) ^ -(value & 1)


def unpack_varints(blob: bytes) -> list[int]:
    """Read a packed repeated numeric field: back-to-back varints."""
    out: list[int] = []
    pos = 0
    while pos < len(blob):
        value, pos = read_varint(blob, pos)
        out.append(value)
    return out


def decode_message(buf: bytes) -> dict[int, list[int | bytes]]:
    """Split a message body into field_number -> [raw value], keeping unknowns."""
    fields: dict[int, list[int | bytes]] = {}
    pos = 0
    size = len(buf)
    while pos < size:
        key, pos = read_varint(buf, pos)
        field_num = key >> 3
        wire_type = key & 0x07
        if field_num == 0:
            raise WireFormatError(f"field number 0 at offset {pos}")
        value: int | bytes
        if wire_type == WIRE_VARINT:
            value, pos = read_varint(buf, pos)
        elif wire_type == WIRE_LEN:
            length, pos = read_varint(buf, pos)
            if pos + length > size:
                raise WireFormatError(f"truncated length-delimited field at offset {pos}")
            value = buf[pos : pos + length]
            pos += length
        elif wire_type in (WIRE_64BIT, WIRE_32BIT):
            width = 8 if wire_type == WIRE_64BIT else 4
            if pos + width > size:
                raise WireFormatError(f"truncated {width * 8}-bit field at offset {pos}")
            value = int.from_bytes(buf[pos : pos + width], "little")
            pos += width
        else:
            raise WireFormatError(f"unsupported wire type {wire_type} at offset {pos}")
        fields.setdefault(field_num, []).append(value)
    return fields


# -------------------------------------------------------------- schema layer


@dataclass
class Calibration:
    """Result of deciding `baseField`'s byte order from the file itself."""

    byte_order: str
    prime: int
    big_reading: int
    little_reading: int
    discriminates: bool
    raw: bytes


def base_field_calibration(base_field: bytes) -> Calibration:
    """Report which endianness of `baseField` yields the Goldilocks prime."""
    big = int.from_bytes(base_field, "big")
    little = int.from_bytes(base_field, "little")
    matches = [name for name, v in (("big", big), ("little", little)) if v == GOLDILOCKS_PRIME]
    if not matches:
        raise SchemaError(
            f"baseField {base_field.hex()} is neither big-endian ({big}) nor little-endian "
            f"({little}) equal to Goldilocks {GOLDILOCKS_PRIME}"
        )
    return Calibration(matches[0], GOLDILOCKS_PRIME, big, little, big != little, base_field)


class ParseContext:
    """Byte order, prime, and the running record of undeclared field numbers."""

    def __init__(self, calibration: Calibration) -> None:
        self.calibration = calibration
        self.byte_order = calibration.byte_order
        self.prime = calibration.prime
        self.unknown: dict[tuple[str, int], int] = {}

    def note_unknown(self, message: str, field_num: int) -> None:
        key = (message, field_num)
        self.unknown[key] = self.unknown.get(key, 0) + 1

    def decode_constant(self, blob: bytes) -> int:
        """Interpret `Operand.Constant.value` with the calibrated byte order.

        A field element arrives already reduced, so the range check is the
        stronger statement and reduction mod p is a no-op on anything passing
        it. An out-of-range constant is a decode failure, not something to fold
        quietly back into range.
        """
        value = int.from_bytes(blob, self.byte_order)
        if value >= self.prime:
            raise SchemaError(f"constant {blob.hex()} decodes to {value} >= p")
        return value


class View:
    """A decoded message body plus the field numbers its .proto declares."""

    __slots__ = ("ctx", "message", "fields")

    def __init__(
        self,
        ctx: ParseContext,
        message: str,
        body: bytes | dict[int, list[int | bytes]],
        known: Iterable[int],
    ) -> None:
        self.ctx = ctx
        self.message = message
        self.fields = decode_message(body) if isinstance(body, bytes) else body
        declared = set(known)
        for field_num in self.fields:
            if field_num not in declared:
                ctx.note_unknown(message, field_num)

    def has(self, num: int) -> bool:
        return num in self.fields

    def _last(self, num: int, numeric: bool, default):
        """Last occurrence of field `num` (the proto3 merge rule), type-checked."""
        values = self.fields.get(num)
        if not values:
            return default
        value = values[-1]
        if isinstance(value, int) is not numeric:
            raise SchemaError(
                f"{self.message} field {num}: expected {'numeric' if numeric else 'bytes'}"
            )
        return value

    def scalar_int(self, num: int, default: int = 0) -> int:
        return self._last(num, True, default)

    def scalar_sint(self, num: int, default: int = 0) -> int:
        raw = self._last(num, True, None)
        return default if raw is None else zigzag_decode(raw)

    def scalar_bytes(self, num: int, default: bytes = b"") -> bytes:
        return self._last(num, False, default)

    def scalar_str(self, num: int, default: str = "") -> str:
        raw = self._last(num, False, None)
        return default if raw is None else raw.decode("utf-8")

    def submessage(self, num: int) -> bytes | None:
        """A singular submessage field, refusing the repeated-occurrence case.

        proto3 says repeated occurrences of a singular submessage field *merge*;
        `_last` would take the last one instead. Rather than implement a merge
        rule no writer here exercises, and rather than diverge silently from the
        `prost` decoder the extractor uses, refuse: two occurrences of a
        singular submessage mean this reader and that one would disagree.
        """
        values = self.fields.get(num)
        if values and len(values) > 1:
            raise SchemaError(
                f"{self.message} field {num}: {len(values)} occurrences of a singular "
                f"submessage; proto3 merges these and this decoder does not"
            )
        return self._last(num, False, None)

    def repeated_uint(self, num: int) -> list[int]:
        """Repeated numeric field, accepting both packed and unpacked encodings."""
        out: list[int] = []
        for value in self.fields.get(num, []):
            out.append(value) if isinstance(value, int) else out.extend(unpack_varints(value))
        return out

    def repeated_bytes(self, num: int) -> list[bytes]:
        out: list[bytes] = []
        for value in self.fields.get(num, []):
            if isinstance(value, int):
                raise SchemaError(f"{self.message} field {num}: expected bytes")
            out.append(value)
        return out


# Field tables transcribed by hand from tools/pil-extract/proto/pilout.proto.
# Each set lists every field number the .proto declares for that message, so a
# field number outside it is schema drift and gets reported.
PILOUT_FIELDS = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}
AIRGROUP_FIELDS = {1, 2, 3}
AIRGROUP_VALUE_FIELDS = {1, 2}
AIR_FIELDS = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
AIR_VALUE_FIELDS = {1}
CUSTOM_COMMIT_FIELDS = {1, 2, 3}
SYMBOL_FIELDS = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
COL_FIELDS = {1}
EXPRESSION_IDX_FIELDS = {1}
GLOBAL_CONSTRAINT_FIELDS = {1, 2}

# Operand oneof tag -> (kind, message, {field number: attribute}).
OPERAND_KINDS: dict[int, tuple[str, str, dict[int, str]]] = {
    1: ("constant", "Operand.Constant", {1: "value_bytes"}),
    2: ("challenge", "Operand.Challenge", {1: "stage", 2: "idx"}),
    3: ("proof_value", "Operand.ProofValue", {1: "stage", 2: "idx"}),
    4: ("air_group_value", "Operand.AirGroupValue", {1: "idx"}),
    5: ("public_value", "Operand.PublicValue", {1: "idx"}),
    6: ("periodic_col", "Operand.PeriodicCol", {1: "idx", 2: "row_offset"}),
    7: ("fixed_col", "Operand.FixedCol", {1: "idx", 2: "row_offset"}),
    8: ("witness_col", "Operand.WitnessCol", {1: "stage", 2: "col_idx", 3: "row_offset"}),
    9: ("expression", "Operand.Expression", {1: "idx"}),
    10: ("air_value", "Operand.AirValue", {1: "idx"}),
    11: (
        "custom_col",
        "Operand.CustomCol",
        {1: "commit_id", 2: "stage", 3: "col_idx", 4: "row_offset"},
    ),
}

# The complete set of sint32 (zigzag) fields in the schema. Every other numeric
# field is a plain varint, and `Operand.Constant.value` is the only bytes one.
ZIGZAG_FIELDS = {
    ("Operand.PeriodicCol", 2),
    ("Operand.FixedCol", 2),
    ("Operand.WitnessCol", 3),
    ("Operand.CustomCol", 4),
}

# Transcription cross-check: the zigzag set and the rowOffset attributes must
# name the same four fields, or one of the two tables has drifted.
_ROW_OFFSETS = {
    (message, num)
    for _, message, spec in OPERAND_KINDS.values()
    for num, attr in spec.items()
    if attr == "row_offset"
}
if _ROW_OFFSETS != ZIGZAG_FIELDS:
    raise SchemaError(f"zigzag table {ZIGZAG_FIELDS} disagrees with rowOffsets {_ROW_OFFSETS}")

# Expression oneof tag -> (kind, message, operand field numbers).
EXPRESSION_OPS: dict[int, tuple[str, str, tuple[int, ...]]] = {
    1: ("add", "Expression.Add", (1, 2)),
    2: ("sub", "Expression.Sub", (1, 2)),
    3: ("mul", "Expression.Mul", (1, 2)),
    4: ("neg", "Expression.Neg", (1,)),
}

# Constraint oneof tag -> (kind, message, debugLine field number).
# EveryFrame puts debugLine at 4 because 2 and 3 carry the frame offsets.
CONSTRAINT_KINDS: dict[int, tuple[str, str, int]] = {
    1: ("first_row", "Constraint.FirstRow", 2),
    2: ("last_row", "Constraint.LastRow", 2),
    3: ("every_row", "Constraint.EveryRow", 2),
    4: ("every_frame", "Constraint.EveryFrame", 4),
}

SYMBOL_TYPES = (
    "IM_COL FIXED_COL PERIODIC_COL WITNESS_COL PROOF_VALUE AIR_GROUP_VALUE PUBLIC_VALUE "
    "PUBLIC_TABLE CHALLENGE AIR_VALUE CUSTOM_COL"
).split()


def _oneof(view: View, table: dict, what: str) -> int:
    """Return the single oneof tag set on `view`, or fail loudly."""
    present = [num for num in view.fields if num in table]
    if len(present) != 1:
        raise SchemaError(f"{what} oneof has {len(present)} arms set: {sorted(present)}")
    return present[0]


class Operand:
    """One leaf of a pilout expression tree; `kind` names the oneof arm taken.

    Every coordinate slot exists on every operand and reads 0 when the arm does
    not carry it, matching proto3's own defaulting; `kind` says which ones are
    meaningful. `value` is the decoded field element for constants, else None.
    """

    __slots__ = (
        "kind", "value", "value_bytes", "idx", "stage", "col_idx", "row_offset", "commit_id",
    )

    def __init__(self, ctx: ParseContext, body: bytes) -> None:
        view = View(ctx, "Operand", body, OPERAND_KINDS)
        tag = _oneof(view, OPERAND_KINDS, "Operand")
        kind, message, spec = OPERAND_KINDS[tag]
        inner = View(ctx, message, view.submessage(tag) or b"", spec)
        for slot in self.__slots__:
            setattr(self, slot, 0)
        self.kind = kind
        self.value = None
        self.value_bytes = b""
        for num, attr in spec.items():
            if attr == "value_bytes":
                self.value_bytes = inner.scalar_bytes(num)
            elif (message, num) in ZIGZAG_FIELDS:
                setattr(self, attr, inner.scalar_sint(num))
            else:
                setattr(self, attr, inner.scalar_int(num))
        if kind == "constant":
            self.value = ctx.decode_constant(self.value_bytes)

    def __repr__(self) -> str:
        if self.kind == "constant":
            return f"Operand(constant {self.value})"
        return (
            f"Operand({self.kind} idx={self.idx} stage={self.stage}"
            f" col={self.col_idx} off={self.row_offset})"
        )


class Expression:
    """A binary add/sub/mul or a unary neg over operands."""

    __slots__ = ("kind", "operands")

    def __init__(self, ctx: ParseContext, body: bytes) -> None:
        view = View(ctx, "Expression", body, EXPRESSION_OPS)
        tag = _oneof(view, EXPRESSION_OPS, "Expression")
        kind, message, operand_fields = EXPRESSION_OPS[tag]
        inner = View(ctx, message, view.submessage(tag) or b"", set(operand_fields))
        operands = []
        for num in operand_fields:
            blob = inner.submessage(num)
            if blob is None:
                raise SchemaError(f"{message} field {num}: operand missing")
            operands.append(Operand(ctx, blob))
        self.kind = kind
        self.operands = tuple(operands)

    @property
    def lhs(self) -> Operand:
        return self.operands[0]

    @property
    def rhs(self) -> Operand:
        return self.operands[1]

    def __repr__(self) -> str:
        return f"Expression({self.kind} {' '.join(repr(o) for o in self.operands)})"


class Constraint:
    """One polynomial identity: a root expression index plus where it applies."""

    __slots__ = ("kind", "expression_idx", "debug_line", "offset_min", "offset_max")

    def __init__(self, ctx: ParseContext, body: bytes) -> None:
        view = View(ctx, "Constraint", body, CONSTRAINT_KINDS)
        tag = _oneof(view, CONSTRAINT_KINDS, "Constraint")
        kind, message, debug_field = CONSTRAINT_KINDS[tag]
        declared = {1, 2, 3, 4} if kind == "every_frame" else {1, 2}
        inner = View(ctx, message, view.submessage(tag) or b"", declared)
        idx_blob = inner.submessage(1)
        if idx_blob is None:
            raise SchemaError(f"{message}: expressionIdx missing")
        idx_view = View(ctx, "Operand.Expression", idx_blob, EXPRESSION_IDX_FIELDS)
        self.kind = kind
        self.expression_idx = idx_view.scalar_int(1)
        self.debug_line = inner.scalar_str(debug_field) if inner.has(debug_field) else None
        self.offset_min = inner.scalar_int(2) if kind == "every_frame" else None
        self.offset_max = inner.scalar_int(3) if kind == "every_frame" else None

    def __repr__(self) -> str:
        frame = f" [{self.offset_min},{self.offset_max}]" if self.kind == "every_frame" else ""
        return f"Constraint({self.kind} expr={self.expression_idx}{frame})"


class GlobalConstraint:
    """A `PilOut.constraints` entry: an identity over signals, not over an AIR.

    Nothing in `tools/pil-extract` renders these, so none reaches Lean. It is
    decoded anyway so the report's denominator can name every polynomial
    identity the file carries, rather than only the ones inside AIRs.
    """

    __slots__ = ("expression_idx", "debug_line")

    def __init__(self, ctx: ParseContext, body: bytes) -> None:
        view = View(ctx, "GlobalConstraint", body, GLOBAL_CONSTRAINT_FIELDS)
        idx_blob = view.submessage(1)
        if idx_blob is None:
            raise SchemaError("GlobalConstraint: expressionIdx missing")
        idx_view = View(ctx, "GlobalOperand.Expression", idx_blob, EXPRESSION_IDX_FIELDS)
        self.expression_idx = idx_view.scalar_int(1)
        self.debug_line = view.scalar_str(2) if view.has(2) else None

    def __repr__(self) -> str:
        return f"GlobalConstraint(expr={self.expression_idx})"


class Symbol:
    """A named column or value, carrying the id that operands refer to."""

    def __init__(self, ctx: ParseContext, body: bytes) -> None:
        view = View(ctx, "Symbol", body, SYMBOL_FIELDS)
        self.name = view.scalar_str(1)
        self.air_group_id = view.scalar_int(2) if view.has(2) else None
        self.air_id = view.scalar_int(3) if view.has(3) else None
        self.type = view.scalar_int(4)
        self.id = view.scalar_int(5)
        self.stage = view.scalar_int(6) if view.has(6) else None
        self.dim = view.scalar_int(7)
        self.lengths = view.repeated_uint(8)
        self.commit_id = view.scalar_int(9) if view.has(9) else None
        self.debug_line = view.scalar_str(10) if view.has(10) else None

    @property
    def type_name(self) -> str:
        return SYMBOL_TYPES[self.type] if self.type < len(SYMBOL_TYPES) else f"TYPE_{self.type}"

    def __repr__(self) -> str:
        return f"Symbol({self.name} {self.type_name} id={self.id} stage={self.stage})"


class Air:
    """One AIR: its expression pool and the constraints rooted in it."""

    def __init__(self, ctx: ParseContext, body: bytes) -> None:
        view = View(ctx, "Air", body, AIR_FIELDS)
        self.name = view.scalar_str(1)
        # The .proto comments numRows as "log2(n)", but the file contradicts
        # that: every AIR carries a power of two in the 2^17..2^22 range, which
        # is the row count itself. Named for what the bytes hold.
        self.num_rows = view.scalar_int(2) if view.has(2) else None
        self.stage_widths = view.repeated_uint(5)
        self.expressions = [Expression(ctx, b) for b in view.repeated_bytes(6)]
        self.constraints = [Constraint(ctx, b) for b in view.repeated_bytes(7)]
        self.aggregable = bool(view.scalar_int(9))
        # Column payloads are out of scope for the polynomial-identity gate, and
        # this pilout stores none of them anyway (every size below reads 0), but
        # the bodies are still walked so undeclared fields inside them show up.
        self.periodic_col_sizes = [
            len(View(ctx, "PeriodicCol", b, COL_FIELDS).repeated_bytes(1))
            for b in view.repeated_bytes(3)
        ]
        self.fixed_col_sizes = [
            len(View(ctx, "FixedCol", b, COL_FIELDS).repeated_bytes(1))
            for b in view.repeated_bytes(4)
        ]
        # airValues and customCommits carry no operand data the round trip
        # needs, but their bodies are still decoded rather than merely counted:
        # an undeclared field inside one is schema drift, and a subtree nobody
        # walks is a subtree where drift cannot be seen.
        self.air_value_stages = [
            View(ctx, "AirValue", b, AIR_VALUE_FIELDS).scalar_int(1)
            for b in view.repeated_bytes(8)
        ]
        self.custom_commit_names = [
            View(ctx, "CustomCommit", b, CUSTOM_COMMIT_FIELDS).scalar_str(1)
            for b in view.repeated_bytes(10)
        ]

    @property
    def num_air_values(self) -> int:
        return len(self.air_value_stages)

    @property
    def num_custom_commits(self) -> int:
        return len(self.custom_commit_names)

    @property
    def num_fixed_cols(self) -> int:
        return len(self.fixed_col_sizes)

    @property
    def num_periodic_cols(self) -> int:
        return len(self.periodic_col_sizes)

    def kind_counts(self) -> dict[str, int]:
        counts = {kind: 0 for kind, _, _ in CONSTRAINT_KINDS.values()}
        for constraint in self.constraints:
            counts[constraint.kind] += 1
        return counts

    def __repr__(self) -> str:
        return f"Air({self.name} cons={len(self.constraints)} exprs={len(self.expressions)})"


class AirGroup:
    def __init__(self, ctx: ParseContext, body: bytes) -> None:
        view = View(ctx, "AirGroup", body, AIRGROUP_FIELDS)
        self.name = view.scalar_str(1)
        # Decoded, not counted, for the same reason as Air.airValues above.
        self.air_group_value_stages = [
            View(ctx, "AirGroupValue", b, AIRGROUP_VALUE_FIELDS).scalar_int(2)
            for b in view.repeated_bytes(2)
        ]
        self.airs = [Air(ctx, b) for b in view.repeated_bytes(3)]

    @property
    def num_air_group_values(self) -> int:
        return len(self.air_group_value_stages)


@dataclass
class AirRef:
    """An AIR with the coordinates the emitted Lean names are keyed by."""

    airgroup_name: str
    airgroup_idx: int
    air_name: str
    air_idx: int
    air: Air


class PilOut:
    def __init__(self, data: bytes, path: str | None = None) -> None:
        root = decode_message(data)
        base_field = root.get(2, [b""])[-1]
        if not isinstance(base_field, bytes):
            raise SchemaError("PilOut.baseField is not length-delimited")
        self.calibration = base_field_calibration(base_field)
        self.ctx = ParseContext(self.calibration)
        self.path = path
        view = View(self.ctx, "PilOut", root, PILOUT_FIELDS)
        self.name = view.scalar_str(1)
        self.air_groups = [AirGroup(self.ctx, b) for b in view.repeated_bytes(3)]
        self.num_challenges = view.repeated_uint(4)
        self.num_proof_values = view.repeated_uint(5)
        self.num_public_values = view.scalar_int(6)
        self.num_public_tables = len(view.repeated_bytes(7))
        self.num_global_expressions = len(view.repeated_bytes(8))
        self.global_constraints = [GlobalConstraint(self.ctx, b) for b in view.repeated_bytes(9)]
        self.num_hints = len(view.repeated_bytes(10))
        self.symbols = [Symbol(self.ctx, b) for b in view.repeated_bytes(11)]

    @property
    def num_global_constraints(self) -> int:
        return len(self.global_constraints)

    @property
    def base_field_prime(self) -> int:
        return self.calibration.prime

    @property
    def base_field_byte_order(self) -> str:
        return self.calibration.byte_order

    def decode_constant(self, blob: bytes) -> int:
        return self.ctx.decode_constant(blob)

    def airs(self) -> list[AirRef]:
        return [
            AirRef(group.name, group_idx, air.name, air_idx, air)
            for group_idx, group in enumerate(self.air_groups)
            for air_idx, air in enumerate(group.airs)
        ]

    def unknown_fields(self) -> list[tuple[str, int, int]]:
        """Undeclared (message, field number, occurrences), sorted for reporting."""
        return sorted((msg, num, count) for (msg, num), count in self.ctx.unknown.items())


def load(path: str | Path) -> PilOut:
    path = Path(path)
    return PilOut(path.read_bytes(), str(path))


# ------------------------------------------------------------------ reporting


def _main(argv: list[str]) -> int:
    default = Path(__file__).resolve().parents[2] / "build" / "zisk.pilout"
    path = Path(argv[1]) if len(argv) > 1 else default
    pilout = load(path)
    cal = pilout.calibration
    print(
        f"file                {path}\n"
        f"pilout name         {pilout.name!r}\n"
        f"baseField bytes     {cal.raw.hex()}\n"
        f"  big-endian        {cal.big_reading}\n"
        f"  little-endian     {cal.little_reading}\n"
        f"  goldilocks p      {GOLDILOCKS_PRIME}\n"
        f"calibrated order    {cal.byte_order}\n"
        f"calibration discriminates: {cal.discriminates}\n"
        f"prime               {pilout.base_field_prime}\n"
        f"numChallenges       {pilout.num_challenges}\n"
        f"numPublicValues     {pilout.num_public_values}\n"
        f"globals             expressions={pilout.num_global_expressions}"
        f" constraints={pilout.num_global_constraints} hints={pilout.num_hints}"
        f" publicTables={pilout.num_public_tables} symbols={len(pilout.symbols)}\n"
    )

    row = "{:<10} {:>3} {:<20} {:>6} {:>7} {:>7} {:>6} {:>5} {:>6} {:>6} {:>7}"
    header = row.format(
        "airgroup", "idx", "air", "cons", "exprs", "every", "first", "last", "frame",
        "fixed", "airval",
    )
    print(header)
    print("-" * len(header))
    totals = {kind: 0 for kind, _, _ in CONSTRAINT_KINDS.values()}
    total_cons = 0
    total_exprs = 0
    for ref in pilout.airs():
        counts = ref.air.kind_counts()
        for kind, count in counts.items():
            totals[kind] += count
        total_cons += len(ref.air.constraints)
        total_exprs += len(ref.air.expressions)
        print(row.format(
            ref.airgroup_name, ref.air_idx, ref.air_name,
            len(ref.air.constraints), len(ref.air.expressions),
            counts["every_row"], counts["first_row"], counts["last_row"],
            counts["every_frame"], ref.air.num_fixed_cols, ref.air.num_air_values,
        ))
    print("-" * len(header))
    print(row.format(
        "TOTAL", "", f"{len(pilout.airs())} airs", total_cons, total_exprs,
        totals["every_row"], totals["first_row"], totals["last_row"], totals["every_frame"], "", "",
    ))

    unusual = [
        (ref, i, c)
        for ref in pilout.airs()
        for i, c in enumerate(ref.air.constraints)
        if c.kind != "every_row"
    ]
    print(f"\nnon-every_row constraints: {len(unusual)}")
    for ref, i, constraint in unusual:
        frame = ""
        if constraint.kind == "every_frame":
            frame = f" offsets=[{constraint.offset_min},{constraint.offset_max}]"
        print(
            f"  {ref.airgroup_name}/{ref.air_name}[{ref.air_idx}] #{i} {constraint.kind}"
            f" expr={constraint.expression_idx}{frame} debugLine={constraint.debug_line!r}"
        )

    unknown = pilout.unknown_fields()
    print(f"unknown field numbers: {len(unknown)}")
    for message, field_num, count in unknown:
        print(f"  {message} field {field_num} x{count}")
    return 0


if __name__ == "__main__":
    sys.exit(_main(sys.argv))
