//! Phase 1 fixture emitter for `ZiskFv.GoldenTraces.Add`.
//!
//! Hardcodes the canonical `3 + 5 = 8` 64-bit ADD: rs1 = 3, rs2 = 5, rd = 8.
//! Emits a Lean file containing a concrete witness for the
//! `Valid_Main` / `Valid_BinaryAdd` ADD-subset constraints, along with a
//! `#eval`-checkable equality between the harness-derived `c`-packed value
//! and the expected sum.
//!
//! **Phase 1.5 plan.** Replace the hardcoded values below with a call to
//! `ProverClient::get_instance_trace(MAIN_INSTANCE_ID, ADD_ROW, 1, None)`
//! returning a `Vec<RowInfo>`, then map the row into the same fixture
//! shape. Probe program lives at `examples/fv-probes/add.rs` (to be
//! added). See `vendor/zisk/examples/sha-hasher/host/bin/execute.rs` for
//! the call pattern.

use anyhow::{Context, Result};
use clap::Parser;
use std::fs;
use std::path::PathBuf;

#[derive(Parser, Debug)]
#[command(
    name = "zisk-fv-harness",
    about = "Emit a ZiskFv golden-trace fixture for the canonical ADD row."
)]
struct Cli {
    /// Output path for the generated `.lean` fixture.
    #[arg(long, default_value = "ZiskFv/ZiskFv/GoldenTraces/Add.lean")]
    output: PathBuf,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    // Canonical ADD: rs1 = 3, rs2 = 5 → rd = 8.
    let a: u64 = 3;
    let b: u64 = 5;
    let c: u64 = a.wrapping_add(b);

    // Decompose into the column shape expected by Valid_Main / Valid_BinaryAdd.
    // Main columns are 32-bit lanes; BinaryAdd's are 16-bit chunks.
    let a_lo: u64 = a & 0xFFFF_FFFF;
    let a_hi: u64 = a >> 32;
    let b_lo: u64 = b & 0xFFFF_FFFF;
    let b_hi: u64 = b >> 32;
    let c_lo: u64 = c & 0xFFFF_FFFF;
    let c_hi: u64 = c >> 32;

    let a0_chunk = a_lo & 0xFFFF;
    let a1_chunk = a_lo >> 16;
    // (BinaryAdd's chunk reassembly: c_chunks[2k+1] * 65536 + c_chunks[2k] = c[k])
    let c0_chunk = c_lo & 0xFFFF;
    let c1_chunk = c_lo >> 16;
    let c2_chunk = c_hi & 0xFFFF;
    let c3_chunk = c_hi >> 16;

    // Carry-out: for 3 + 5 = 8, both carries are 0 (no overflow at 32-bit
    // lane boundary or the 64-bit boundary).
    let cout0: u64 = if (a_lo + b_lo) >= (1u64 << 32) { 1 } else { 0 };
    let cout1: u64 = if (a_hi + b_hi + cout0) >= (1u64 << 32) { 1 } else { 0 };

    let lean = render_lean(a, b, c, a_lo, a_hi, b_lo, b_hi, c_lo, c_hi,
                           a0_chunk, a1_chunk, c0_chunk, c1_chunk,
                           c2_chunk, c3_chunk, cout0, cout1);

    if let Some(parent) = cli.output.parent() {
        fs::create_dir_all(parent).ok();
    }
    fs::write(&cli.output, lean)
        .with_context(|| format!("failed to write {}", cli.output.display()))?;
    eprintln!("wrote {}", cli.output.display());
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn render_lean(
    a: u64, b: u64, c: u64,
    a_lo: u64, a_hi: u64, b_lo: u64, b_hi: u64, c_lo: u64, c_hi: u64,
    a0_chunk: u64, a1_chunk: u64,
    c0_chunk: u64, c1_chunk: u64, c2_chunk: u64, c3_chunk: u64,
    cout0: u64, cout1: u64,
) -> String {
    format!(
"import Mathlib

import ZiskFv.Fundamentals.Goldilocks
import ZiskFv.Spec.Add

/-!
Phase 1 golden-trace fixture: canonical 64-bit ADD `{a} + {b} = {c}`.

Generated by `tools/zisk-fv-harness` from hardcoded values; Phase 1.5
replaces this with `ProverClient::get_instance_trace` output. The shape
matches what a real ZisK Main row + BinaryAdd row would produce for the
RISC-V instruction sequence:

```asm
addi x1, x0, {a}
addi x2, x0, {b}
add  x3, x1, x2  -- this row's witness is captured below
```
-/

namespace ZiskFv.GoldenTraces.Add

open Goldilocks

-- 32-bit lane decomposition (Main AIR columns).
@[simp] def add_a_lo : FGL := {a_lo}
@[simp] def add_a_hi : FGL := {a_hi}
@[simp] def add_b_lo : FGL := {b_lo}
@[simp] def add_b_hi : FGL := {b_hi}
@[simp] def add_c_lo : FGL := {c_lo}
@[simp] def add_c_hi : FGL := {c_hi}

-- 16-bit chunk decomposition (BinaryAdd AIR columns).
@[simp] def chunk_a0 : FGL := {a0_chunk}
@[simp] def chunk_a1 : FGL := {a1_chunk}
@[simp] def chunk_c0 : FGL := {c0_chunk}
@[simp] def chunk_c1 : FGL := {c1_chunk}
@[simp] def chunk_c2 : FGL := {c2_chunk}
@[simp] def chunk_c3 : FGL := {c3_chunk}

-- Carry-out cells.
@[simp] def cout_0 : FGL := {cout0}
@[simp] def cout_1 : FGL := {cout1}

/-- The packed `c`-value (32-bit lane recombination) matches `{a} + {b} = {c}`. -/
example : add_c_lo + add_c_hi * 4294967296 = ({c} : FGL) := by decide

/-- BinaryAdd's chunk reassembly produces the same packed value. -/
example :
    (chunk_c1 * 65536 + chunk_c0) + (chunk_c3 * 65536 + chunk_c2) * 4294967296
      = ({c} : FGL) := by decide

/-- Low-lane carry chain (BinaryAdd `carry_chain_0`):
    a_lo + b_lo = cout_0 * 2^32 + chunk_c1 * 2^16 + chunk_c0. -/
example :
    add_a_lo + add_b_lo
      = cout_0 * 4294967296 + chunk_c1 * 65536 + chunk_c0 := by decide

/-- High-lane carry chain (BinaryAdd `carry_chain_1`):
    a_hi + b_hi + cout_0 = cout_1 * 2^32 + chunk_c3 * 2^16 + chunk_c2. -/
example :
    add_a_hi + add_b_hi + cout_0
      = cout_1 * 4294967296 + chunk_c3 * 65536 + chunk_c2 := by decide

end ZiskFv.GoldenTraces.Add
",
        a = a, b = b, c = c,
        a_lo = a_lo, a_hi = a_hi, b_lo = b_lo, b_hi = b_hi, c_lo = c_lo, c_hi = c_hi,
        a0_chunk = a0_chunk, a1_chunk = a1_chunk,
        c0_chunk = c0_chunk, c1_chunk = c1_chunk, c2_chunk = c2_chunk, c3_chunk = c3_chunk,
        cout0 = cout0, cout1 = cout1,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_lean_canonical_add() {
        let s = render_lean(3, 5, 8,
            3, 0, 5, 0, 8, 0,
            3, 0, 8, 0, 0, 0, 0, 0);
        assert!(s.contains("add_a_lo : FGL := 3"));
        assert!(s.contains("add_b_lo : FGL := 5"));
        assert!(s.contains("add_c_lo : FGL := 8"));
        assert!(s.contains("cout_0 : FGL := 0"));
        assert!(s.contains("cout_1 : FGL := 0"));
    }

    #[test]
    fn cout_propagation_overflow_lo() {
        // 0xFFFFFFFF + 1 = 0x100000000 → cout_0 = 1, c_lo = 0
        let a: u64 = 0xFFFF_FFFF;
        let b: u64 = 1;
        let c = a.wrapping_add(b);
        let a_lo = a & 0xFFFF_FFFF;
        let b_lo = b & 0xFFFF_FFFF;
        let cout0 = if (a_lo + b_lo) >= (1u64 << 32) { 1 } else { 0 };
        assert_eq!(cout0, 1);
        assert_eq!(c, 0x1_0000_0000);
    }
}
