import ZiskFv.AirsClean.BinaryAdd.Spec
import Clean.Circuit.Basic
import ZiskFv.Channels.OperationBus

/-!
# BinaryAdd circuit operations (the `main` field of the Component)

The constraint emissions of ZisK's BinaryAdd AIR, expressed as a Clean
circuit do-block: one `assertZero` per F-only pilout constraint,
then the operation-bus `OpBusChannel.push`.

AUTO-GENERATED by `tools/pil-extract` (`clean-component` subcommand) —
do not hand-edit. The op-bus push is reconstructed from the
proves-side `gsum_debug_data` hint and is slot-for-slot faithful to
`opBus_row_BinaryAdd` (`ZiskFv/Airs/OperationBus/OperationBus.lean`).

## Trust note

No axioms. Pure operational declaration.
-/

namespace ZiskFv.AirsClean.BinaryAdd

open Goldilocks
open Circuit (assertZero)
open ZiskFv.Channels.OperationBus (OpBusChannel)

/-- The 4 F-constraints and op-bus push, taking the row's slot
    values as `Expression FGL`s. Returns `Unit` (BinaryAdd is a pure
    assertion — no fresh witnesses introduced inside the circuit). -/
@[circuit_norm]
def main (row : Var BinaryAddRow FGL) : Circuit FGL Unit := do
  -- constraint 0 (binary/pil/binary_add.pil:14)
  assertZero (row.cout_0 * (1 - row.cout_0))
  -- constraint 1 (binary/pil/binary_add.pil:19)
  assertZero ((row.a_0 + row.b_0) - (((row.cout_0 * 4294967296) + (row.c_chunks_1 * 65536)) + row.c_chunks_0))
  -- constraint 2 (binary/pil/binary_add.pil:14)
  assertZero (row.cout_1 * (1 - row.cout_1))
  -- constraint 3 (binary/pil/binary_add.pil:19)
  assertZero (((row.a_1 + row.b_1) + row.cout_0) - (((row.cout_1 * 4294967296) + (row.c_chunks_3 * 65536)) + row.c_chunks_2))
  -- Op-bus emission: BinaryAdd pushes its result onto operation bus 5000.
  -- Reconstructed from the proves-side `gsum_debug_data` hint;
  -- slot-for-slot faithful to `opBus_row_BinaryAdd`.
  OpBusChannel.push
    { op := 10
      a_lo := row.a_0
      a_hi := row.a_1
      b_lo := row.b_0
      b_hi := row.b_1
      c_lo := ((row.c_chunks_1 * 65536) + row.c_chunks_0)
      c_hi := ((row.c_chunks_3 * 65536) + row.c_chunks_2)
      flag := 0
      main_step := 0
      extended_arg := 0
      extra_args_0 := 0 }

/-- The elaborated circuit for BinaryAdd's `main` — 4 `assertZero`
    constraints + the op-bus push, no fresh witnesses (`localLength = 0`,
    `unit` output). Lives here (next to `main`) rather than in
    `Circuit.lean` so the completeness axiom (`Completeness.lean`, whose
    type mentions this) can be declared without an import cycle. -/
@[reducible] def binaryAddElaborated : ElaboratedCircuit FGL BinaryAddRow unit where
  name := "BinaryAdd"
  main := main
  localLength _ := 0
  output _ _ := ()
  channelsWithRequirements := [OpBusChannel.toRaw]

end ZiskFv.AirsClean.BinaryAdd
