import ZiskFv.AirsClean.BinaryAdd.Spec
import ZiskFv.AirsClean.RangeTables
import Clean.Circuit.Basic
import ZiskFv.Channels.OperationBus

/-!
# BinaryAdd circuit operations (the `main` field of the Component)

The constraint emissions of ZisK's BinaryAdd AIR, expressed as a Clean
circuit do-block: one `assertZero` per F-only pilout constraint,
then the operation bus `OpBusChannel.push`.

AUTO-GENERATED by `tools/pil-extract` (`clean-component` subcommand) —
do not hand-edit. The bus push is reconstructed from the
proves-side `gsum_debug_data` hint and is slot-for-slot faithful to
the hand-written reference.

## Trust note

No axioms. Pure operational declaration.
-/

namespace ZiskFv.AirsClean.BinaryAdd

open Goldilocks
open Circuit (assertZero lookup)
open ZiskFv.AirsClean.RangeTables
open ZiskFv.Channels.OperationBus (OpBusChannel OpBusMessage)

@[reducible]
def opBusMessageExpr (row : Var BinaryAddRow FGL) : OpBusMessage (Expression FGL) :=
  { op := 10
    a_lo := row.a_0
    a_hi := row.a_1
    b_lo := row.b_0
    b_hi := row.b_1
    c_lo := ((row.c_chunks_1 * 65536) + row.c_chunks_0)
    c_hi := ((row.c_chunks_3 * 65536) + row.c_chunks_2)
    flag := 0
    main_step := 0
    extended_arg := 0
    extra_args_0 := 0 }

/-- The 4 F-constraints and operation bus push, taking the row's slot
    values as `Expression FGL`s. Returns `Unit` (BinaryAdd is a pure
    assertion — no fresh witnesses introduced inside the circuit). -/
@[circuit_norm]
def main (row : Var BinaryAddRow FGL) : Circuit FGL Unit := do
  -- range lookups (binary/pil/binary_add.pil: a/b are 32-bit limbs,
  -- c_chunks are 16-bit limbs)
  lookup (Table.fromStatic rangeTable32) row.a_0
  lookup (Table.fromStatic rangeTable32) row.a_1
  lookup (Table.fromStatic rangeTable32) row.b_0
  lookup (Table.fromStatic rangeTable32) row.b_1
  lookup (Table.fromStatic rangeTable16) row.c_chunks_0
  lookup (Table.fromStatic rangeTable16) row.c_chunks_1
  lookup (Table.fromStatic rangeTable16) row.c_chunks_2
  lookup (Table.fromStatic rangeTable16) row.c_chunks_3
  -- constraint 0 (binary/pil/binary_add.pil:14)
  assertZero (row.cout_0 * (1 - row.cout_0))
  -- constraint 1 (binary/pil/binary_add.pil:19)
  assertZero ((row.a_0 + row.b_0) - (((row.cout_0 * 4294967296) + (row.c_chunks_1 * 65536)) + row.c_chunks_0))
  -- constraint 2 (binary/pil/binary_add.pil:14)
  assertZero (row.cout_1 * (1 - row.cout_1))
  -- constraint 3 (binary/pil/binary_add.pil:19)
  assertZero (((row.a_1 + row.b_1) + row.cout_0) - (((row.cout_1 * 4294967296) + (row.c_chunks_3 * 65536)) + row.c_chunks_2))
  -- Bus emission: BinaryAdd pushes its proves-side tuple onto operation bus 5000.
  -- Reconstructed from the proves-side `gsum_debug_data` hint;
  -- slot-for-slot faithful to the hand-written reference.
  OpBusChannel.push (opBusMessageExpr row)

/-- The elaborated circuit for BinaryAdd's `main` — 4 `assertZero`
    constraints + the bus push, no fresh witnesses (`localLength = 0`,
    `unit` output). Lives here (next to `main`) so the `Circuit.lean`
    wrapper can reuse it without an import cycle. -/
@[reducible] def binaryAddElaborated : ElaboratedCircuit FGL BinaryAddRow unit where
  name := "BinaryAdd"
  main := main
  localLength _ := 0
  output _ _ := ()
  channelsWithRequirements := [OpBusChannel.toRaw]
  exposedChannels row _ :=
    expose OpBusChannel [OpBusChannel.pushed (opBusMessageExpr row)]
  channelsLawful := by
    simp only [circuit_norm, main, opBusMessageExpr, OpBusChannel]

end ZiskFv.AirsClean.BinaryAdd
