import Clean.Circuit.Channel
import Clean.Circuit.Provable
import Clean.Utils.Tactics.ProvableStructDeriving
import ZiskFv.Field.Goldilocks

/-!
# BinaryAdd row type (Clean ProvableStruct)

The stage-1 witness row layout for ZisK's BinaryAdd AIR, expressed as a
`ProvableStruct` for consumption by a Clean `GeneralFormalCircuit`.

AUTO-GENERATED by `tools/pil-extract` (`clean-component` subcommand)
from `build/zisk.pilout` — do not hand-edit.

Stage-1 columns (one struct field each):

* `a_0` — pilout column 0 (`a[0]`)
* `a_1` — pilout column 1 (`a[1]`)
* `b_0` — pilout column 2 (`b[0]`)
* `b_1` — pilout column 3 (`b[1]`)
* `c_chunks_0` — pilout column 4 (`c_chunks[0]`)
* `c_chunks_1` — pilout column 5 (`c_chunks[1]`)
* `c_chunks_2` — pilout column 6 (`c_chunks[2]`)
* `c_chunks_3` — pilout column 7 (`c_chunks[3]`)
* `cout_0` — pilout column 8 (`cout[0]`)
* `cout_1` — pilout column 9 (`cout[1]`)

Stage-2 columns (`gsum`, `im_cluster`) are omitted: they are the permutation
accumulators / intermediates, which Clean's channel-balance
machinery subsumes. The row here is the witness-only slice the
Clean Component constrains directly.

## Trust note

No axiom added — this is a pure data definition.
-/

namespace ZiskFv.AirsClean.BinaryAdd

open Goldilocks

/-- The 10-column stage-1 witness row for BinaryAdd. -/
structure BinaryAddRow (F : Type) where
  a_0 : F
  a_1 : F
  b_0 : F
  b_1 : F
  c_chunks_0 : F
  c_chunks_1 : F
  c_chunks_2 : F
  c_chunks_3 : F
  cout_0 : F
  cout_1 : F
deriving ProvableStruct

/-- The 32-bit packed value of a two-half lane. -/
@[reducible]
def packed32 (lo hi : FGL) : ℕ := lo.val + hi.val * 2 ^ 32

/-- The 64-bit packed value reconstructed from four 16-bit chunks. -/
@[reducible]
def cPacked (row : BinaryAddRow FGL) : ℕ :=
  (row.c_chunks_0.val + row.c_chunks_1.val * 2 ^ 16) +
  (row.c_chunks_2.val + row.c_chunks_3.val * 2 ^ 16) * 2 ^ 32

end ZiskFv.AirsClean.BinaryAdd
