import ZiskFv.AirsClean.MemAlignByte.Spec
import ZiskFv.AirsClean.RangeTables
import Clean.Circuit.Basic
import ZiskFv.Channels.MemoryBus

/-!
# MemAlignByte circuit operations (the `main` field of the Component)

The constraint emissions of ZisK's MemAlignByte AIR, expressed as a Clean
circuit do-block: one `assertZero` per F-only pilout constraint,
then the unified memory bus `MemBusChannel.push`.

AUTO-GENERATED by `tools/pil-extract` (`clean-component` subcommand) —
do not hand-edit. The bus push is reconstructed from the
proves-side `gsum_debug_data` hint and is slot-for-slot faithful to
the hand-written reference.

## Trust note

No axioms. Pure operational declaration.
-/

namespace ZiskFv.AirsClean.MemAlignByte

open Goldilocks
open Circuit (assertZero lookup)
open ZiskFv.AirsClean.RangeTables
open ZiskFv.Channels.MemoryBus (MemBusChannel MemBusMessage)

@[reducible]
def memBusMessageExpr (row : Var MemAlignByteRow FGL) :
    MemBusMessage (Expression FGL) :=
  { mem_op := (1 + row.is_write)
    ptr := ((row.addr_w * 8) + (((row.sel_high_4b * 4) + (row.sel_high_2b * 2)) + row.sel_high_b))
    timestamp := row.step
    width := 1
    value_0 := row.bus_byte
    value_1 := 0 }

/-- The 9 F-constraints and memory bus push, taking the row's slot
    values as `Expression FGL`s. Returns `Unit` (MemAlignByte is a pure
    assertion — no fresh witnesses introduced inside the circuit). -/
@[circuit_norm]
def main (row : Var MemAlignByteRow FGL) : Circuit FGL Unit := do
  -- range lookups for bits declarations used by the algebraic Spec
  lookup (Table.fromStatic rangeTable8) row.bus_byte
  lookup (Table.fromStatic rangeTable8) row.byte_value
  lookup (Table.fromStatic rangeTable1) row.is_write
  -- constraint 0 (mem/pil/mem_align_byte.pil:35)
  assertZero (row.sel_high_4b * (1 - row.sel_high_4b))
  -- constraint 1 (mem/pil/mem_align_byte.pil:36)
  assertZero (row.sel_high_2b * (1 - row.sel_high_2b))
  -- constraint 2 (mem/pil/mem_align_byte.pil:37)
  assertZero (row.sel_high_b * (1 - row.sel_high_b))
  -- constraint 3 (mem/pil/mem_align_byte.pil:59)
  assertZero (row.composed_value - (((row.byte_value * (((((16777216 * row.sel_high_2b) * row.sel_high_b) + ((65536 * row.sel_high_2b) * (1 - row.sel_high_b))) + ((256 * (1 - row.sel_high_2b)) * row.sel_high_b)) + ((1 - row.sel_high_2b) * (1 - row.sel_high_b)))) + (row.value_8b * (((((16777216 * row.sel_high_2b) * (1 - row.sel_high_b)) + ((65536 * row.sel_high_2b) * row.sel_high_b)) + ((256 * (1 - row.sel_high_2b)) * (1 - row.sel_high_b))) + ((1 - row.sel_high_2b) * row.sel_high_b)))) + (row.value_16b * ((65536 * (1 - row.sel_high_2b)) + row.sel_high_2b))))
  -- constraint 4 (mem/pil/mem_align_byte.pil:71)
  assertZero (row.is_write * (1 - row.is_write))
  -- constraint 5 (mem/pil/mem_align_byte.pil:83)
  assertZero (row.written_composed_value - (((row.written_byte_value * (((((16777216 * row.sel_high_2b) * row.sel_high_b) + ((65536 * row.sel_high_2b) * (1 - row.sel_high_b))) + ((256 * (1 - row.sel_high_2b)) * row.sel_high_b)) + ((1 - row.sel_high_2b) * (1 - row.sel_high_b)))) + (row.value_8b * (((((16777216 * row.sel_high_2b) * (1 - row.sel_high_b)) + ((65536 * row.sel_high_2b) * row.sel_high_b)) + ((256 * (1 - row.sel_high_2b)) * (1 - row.sel_high_b))) + ((1 - row.sel_high_2b) * row.sel_high_b)))) + (row.value_16b * ((65536 * (1 - row.sel_high_2b)) + row.sel_high_2b))))
  -- constraint 6 (mem/pil/mem_align_byte.pil:87)
  assertZero (row.mem_write_values_0 - ((row.sel_high_4b * (row.direct_value - row.written_composed_value)) + row.written_composed_value))
  -- constraint 7 (mem/pil/mem_align_byte.pil:88)
  assertZero (row.mem_write_values_1 - ((row.sel_high_4b * (row.written_composed_value - row.direct_value)) + row.direct_value))
  -- constraint 8 (mem/pil/mem_align_byte.pil:95)
  assertZero (row.bus_byte - ((row.is_write * (row.written_byte_value - row.byte_value)) + row.byte_value))
  -- Bus emission: MemAlignByte pushes its proves-side tuple onto memory bus 10.
  -- Reconstructed from the proves-side `gsum_debug_data` hint;
  -- slot-for-slot faithful to the hand-written reference.
  MemBusChannel.push (memBusMessageExpr row)

/-- The elaborated circuit for MemAlignByte's `main` — 9 `assertZero`
    constraints + the bus push, no fresh witnesses (`localLength = 0`,
    `unit` output). Lives here (next to `main`) so the `Circuit.lean`
    wrapper can reuse it without an import cycle. -/
@[reducible] def memAlignByteElaborated : ElaboratedCircuit FGL MemAlignByteRow unit where
  name := "MemAlignByte"
  main := main
  localLength _ := 0
  output _ _ := ()
  channelsWithRequirements := [MemBusChannel.toRaw]
  exposedChannels row _ :=
    expose MemBusChannel [MemBusChannel.pushed (memBusMessageExpr row)]
  channelsLawful := by
    simp only [circuit_norm, main, memBusMessageExpr, MemBusChannel]

end ZiskFv.AirsClean.MemAlignByte
