import Clean.Circuit.Channel
import Clean.Circuit.Provable
import Clean.Utils.Tactics.ProvableStructDeriving
import ZiskFv.Field.Goldilocks

/-!
# MemAlignByte row type (Clean ProvableStruct)

The stage-1 witness row layout for ZisK's MemAlignByte AIR, expressed as a
`ProvableStruct` for consumption by a Clean `GeneralFormalCircuit`.

AUTO-GENERATED by `tools/pil-extract` (`clean-component` subcommand)
from `build/zisk.pilout` — do not hand-edit.

Stage-1 columns (one struct field each):

* `sel_high_4b` — pilout column 0 (`sel_high_4b`)
* `sel_high_2b` — pilout column 1 (`sel_high_2b`)
* `sel_high_b` — pilout column 2 (`sel_high_b`)
* `direct_value` — pilout column 3 (`direct_value`)
* `composed_value` — pilout column 4 (`composed_value`)
* `written_composed_value` — pilout column 5 (`written_composed_value`)
* `written_byte_value` — pilout column 6 (`written_byte_value`)
* `value_16b` — pilout column 7 (`value_16b`)
* `value_8b` — pilout column 8 (`value_8b`)
* `byte_value` — pilout column 9 (`byte_value`)
* `addr_w` — pilout column 10 (`addr_w`)
* `step` — pilout column 11 (`step`)
* `is_write` — pilout column 12 (`is_write`)
* `mem_write_values_0` — pilout column 13 (`mem_write_values[0]`)
* `mem_write_values_1` — pilout column 14 (`mem_write_values[1]`)
* `bus_byte` — pilout column 15 (`bus_byte`)

Stage-2 columns (`gsum`, `im_cluster`, `im_single`) are omitted: they are the permutation
accumulators / intermediates, which Clean's channel-balance
machinery subsumes. The row here is the witness-only slice the
Clean Component constrains directly.

## Trust note

No axiom added — this is a pure data definition.
-/

namespace ZiskFv.AirsClean.MemAlignByte

open Goldilocks

/-- The 16-column stage-1 witness row for MemAlignByte. -/
structure MemAlignByteRow (F : Type) where
  sel_high_4b : F
  sel_high_2b : F
  sel_high_b : F
  direct_value : F
  composed_value : F
  written_composed_value : F
  written_byte_value : F
  value_16b : F
  value_8b : F
  byte_value : F
  addr_w : F
  step : F
  is_write : F
  mem_write_values_0 : F
  mem_write_values_1 : F
  bus_byte : F
deriving ProvableStruct

end ZiskFv.AirsClean.MemAlignByte
