import ZiskFv.Completeness.Rv64imShapes
import ZiskFv.SailSpec.Auxiliaries

/-!
# Sail-derived RV decode domain

This module is the checked-in Sail-domain bridge for RV completeness.  It names
the Sail raw-decode domain from the generated Sail decoder and proves the first
non-FENCE containment bridges into the existing RV64IM raw-shape surface.

The ZisK-side predicates still live behind `Rv.Interface`: the concrete
production decoder/lowering predicates are generated by the Aeneas harness.
-/

namespace ZiskFv.Completeness.SailDecode

open ZiskFv.Completeness

abbrev RawInstruction := Rv.RawInstruction

/-- Sail raw decode, from the generated Sail `ext_decode` entrypoint. -/
def SailDecodesTo (raw : RawInstruction) (inst : instruction) : Prop :=
  LeanRV64D.Functions.ext_decode raw = pure inst

/-- Sail raw encoding, from the generated Sail `encdec_forwards` entrypoint. -/
def SailEncodesTo (inst : instruction) (raw : RawInstruction) : Prop :=
  LeanRV64D.Functions.encdec_forwards inst = pure raw

theorem sailM_pure_injective {α : Type} {a b : α}
    (h : (pure a : SailM α) = pure b) : a = b := by
  have h_app :=
    congrFun h
      (default : PreSail.SequentialState RegisterType Sail.trivialChoiceSource)
  simpa [EStateM.pure] using h_app

/-- The Step 3 pilot domain: Sail decodes the raw word to RV64 ADD and the
generated Sail encoder maps that constructor back to the same raw word. -/
def SailAddExecutableRaw (raw : RawInstruction) : Prop :=
  ∃ rs2 rs1 rd,
    let inst := instruction.RTYPE (rs2, rs1, rd, rop.ADD)
    SailDecodesTo raw inst ∧ SailEncodesTo inst raw

/-- The current non-FENCE constructor surface covered by Sail-domain bridges. -/
def SailRegisterPilotInstruction (inst : instruction) : Prop :=
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.ADD)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.SUB))

/-- RV64IM constructor whitelist.  Later steps should add the remaining
register/immediate/load/store/branch/upper/jump/FENCE constructor families. -/
def SailRv64imInstruction (inst : instruction) : Prop :=
  SailRegisterPilotInstruction inst

/-- Sail-executable raw word for the currently covered RV64IM pilot surface. -/
def SailRv64imExecutableRaw (raw : RawInstruction) : Prop :=
  ∃ inst, SailDecodesTo raw inst ∧ SailEncodesTo inst raw ∧
    SailRv64imInstruction inst

theorem sail_add_executable_implies_rv64im_executable
    {raw : RawInstruction} :
    SailAddExecutableRaw raw → SailRv64imExecutableRaw raw := by
  intro h
  rcases h with ⟨rs2, rs1, rd, h_decode, h_encode⟩
  exact
    ⟨instruction.RTYPE (rs2, rs1, rd, rop.ADD),
      h_decode, h_encode, .inl ⟨rs2, rs1, rd, rfl⟩⟩

theorem sail_add_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b000#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 0
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        0
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_sub_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0100000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b000#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 32
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        0
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

/-- Generated Sail encoder fact for the ADD pilot. -/
theorem sail_encode_add_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPE (rs2, rs1, rd, rop.ADD)) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0000000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b000#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0110011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33)
  rw [sail_add_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_sub_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPE (rs2, rs1, rd, rop.SUB)) =
      pure
        (Rv64imShapes.rawRType 32
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0100000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b000#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0110011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 32
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33)
  rw [sail_sub_concat_eq_rawRType rs2 rs1 rd]

/-- Constructor-level bridge for the ADD pilot.  The premises are generated Sail
decode and generated Sail encode facts, not a hand-written raw decoder. -/
theorem sail_decode_add_contained_in_rtype_shape
    {raw : RawInstruction} {rs2 rs1 rd : regidx}
    (_h_decode :
      SailDecodesTo raw (instruction.RTYPE (rs2, rs1, rd, rop.ADD)))
    (h_encode :
      SailEncodesTo (instruction.RTYPE (rs2, rs1, rd, rop.ADD)) raw) :
    Rv64imShapes.RTypeRegisterShape raw := by
  have h_raw :
      raw =
        Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33 := by
    dsimp [SailEncodesTo] at h_encode
    rw [sail_encode_add_eq_rawRType rs2 rs1 rd] at h_encode
    exact sailM_pure_injective h_encode.symm
  subst raw
  refine
    ⟨0, 0, 0x33,
      (regidx_to_fin rd).val,
      (regidx_to_fin rs1).val,
      (regidx_to_fin rs2).val,
      ?_, ?_, ?_, ?_, rfl⟩
  · simp [Rv64imShapes.allRTypeOpcodeShapes]
  · exact List.mem_range.mpr (regidx_to_fin rd).isLt
  · exact List.mem_range.mpr (regidx_to_fin rs1).isLt
  · exact List.mem_range.mpr (regidx_to_fin rs2).isLt

theorem sail_decode_sub_contained_in_rtype_shape
    {raw : RawInstruction} {rs2 rs1 rd : regidx}
    (_h_decode :
      SailDecodesTo raw (instruction.RTYPE (rs2, rs1, rd, rop.SUB)))
    (h_encode :
      SailEncodesTo (instruction.RTYPE (rs2, rs1, rd, rop.SUB)) raw) :
    Rv64imShapes.RTypeRegisterShape raw := by
  have h_raw :
      raw =
        Rv64imShapes.rawRType 32
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33 := by
    dsimp [SailEncodesTo] at h_encode
    rw [sail_encode_sub_eq_rawRType rs2 rs1 rd] at h_encode
    exact sailM_pure_injective h_encode.symm
  subst raw
  refine
    ⟨32, 0, 0x33,
      (regidx_to_fin rd).val,
      (regidx_to_fin rs1).val,
      (regidx_to_fin rs2).val,
      ?_, ?_, ?_, ?_, rfl⟩
  · simp [Rv64imShapes.allRTypeOpcodeShapes]
  · exact List.mem_range.mpr (regidx_to_fin rd).isLt
  · exact List.mem_range.mpr (regidx_to_fin rs1).isLt
  · exact List.mem_range.mpr (regidx_to_fin rs2).isLt

/-- Pilot Step 3 containment for ADD. -/
theorem sail_add_executable_contained :
    ∀ raw,
      SailAddExecutableRaw raw →
      Rv64imShapes.RTypeRegisterShape raw := by
  intro raw h_sail
  rcases h_sail with ⟨rs2, rs1, rd, h_decode, h_encode⟩
  exact
    sail_decode_add_contained_in_rtype_shape
      h_decode
      h_encode

theorem sail_register_pilot_executable_contained :
    ∀ raw inst,
      SailDecodesTo raw inst →
      SailEncodesTo inst raw →
      SailRegisterPilotInstruction inst →
      Rv64imShapes.RTypeRegisterShape raw := by
  intro raw inst h_decode h_encode h_inst
  rcases h_inst with
    ⟨rs2, rs1, rd, h_eq⟩ | ⟨rs2, rs1, rd, h_eq⟩
  · rw [h_eq] at h_decode h_encode
    exact sail_decode_add_contained_in_rtype_shape h_decode h_encode
  · rw [h_eq] at h_decode h_encode
    exact sail_decode_sub_contained_in_rtype_shape h_decode h_encode

theorem sail_rv64im_executable_contained_in_supported_decode_pilot :
    ∀ raw,
      SailRv64imExecutableRaw raw →
      Rv64imShapes.SupportedDecodeShape raw := by
  intro raw h_sail
  rcases h_sail with ⟨inst, h_decode, h_encode, h_inst⟩
  exact .inl
    (sail_register_pilot_executable_contained
      raw inst h_decode h_encode h_inst)

end ZiskFv.Completeness.SailDecode
