import ZiskFv.Completeness.Rv64imShapes
import ZiskFv.SailSpec.Auxiliaries

/-!
# Sail-derived RV decode domain

This module is the checked-in Sail-domain bridge for RV completeness.  It names
the Sail raw-decode domain from the generated Sail decoder and proves the first
non-FENCE containment bridges into the existing RV64IM raw-shape surface.

The ZisK-side predicates still live behind `Rv.Interface`: the concrete
production decoder/lowering predicates are generated by the Aeneas harness.
-/

namespace ZiskFv.Completeness.SailDecode

open ZiskFv.Completeness

abbrev RawInstruction := Rv.RawInstruction
abbrev SailState := PreSail.SequentialState RegisterType Sail.trivialChoiceSource

def SailReturns {α : Type} (action : SailM α) (state : SailState) (value : α) : Prop :=
  action state = EStateM.Result.ok value state

def Rv64imEnabledSailState (state : SailState) : Prop :=
  LeanRV64D.Functions.currentlyEnabled extension.Ext_M state =
    EStateM.Result.ok true state ∧
  LeanRV64D.Functions.currentlyEnabled extension.Ext_Zmmul state =
    EStateM.Result.ok false state

/-- Sail raw decode, from the generated Sail `ext_decode` entrypoint. -/
def SailDecodesTo (raw : RawInstruction) (inst : instruction) : Prop :=
  LeanRV64D.Functions.ext_decode raw = pure inst

/-- Sail raw encoding, from the generated Sail `encdec_forwards` entrypoint. -/
def SailEncodesTo (inst : instruction) (raw : RawInstruction) : Prop :=
  LeanRV64D.Functions.encdec_forwards inst = pure raw

/-- State-aware Sail raw decode, for generated Sail branches that consult
extension state before returning a decoded constructor. -/
def SailDecodesToIn (state : SailState) (raw : RawInstruction) (inst : instruction) : Prop :=
  SailReturns (LeanRV64D.Functions.ext_decode raw) state inst

/-- State-aware Sail raw encoding, for generated Sail branches that consult
extension state before returning a raw word. -/
def SailEncodesToIn (state : SailState) (inst : instruction) (raw : RawInstruction) : Prop :=
  SailReturns (LeanRV64D.Functions.encdec_forwards inst) state raw

theorem sail_returns_of_pure {α : Type} {action : SailM α} {value : α}
    (h : action = pure value) :
    ∀ state, SailReturns action state value := by
  intro state
  rw [h]
  rfl

theorem sailM_bind_ok {α β : Type} {state : SailState}
    {action : SailM α} {next : α → SailM β} {a : α} {b : β}
    (h_action : action state = EStateM.Result.ok a state)
    (h_next : next a state = EStateM.Result.ok b state) :
    (action >>= next) state = EStateM.Result.ok b state := by
  simp [bind, h_action, h_next]

theorem sail_decodes_to_in_of_pure
    {raw : RawInstruction} {inst : instruction}
    (h : SailDecodesTo raw inst) :
    ∀ state, SailDecodesToIn state raw inst :=
  sail_returns_of_pure h

theorem sail_encodes_to_in_of_pure
    {raw : RawInstruction} {inst : instruction}
    (h : SailEncodesTo inst raw) :
    ∀ state, SailEncodesToIn state inst raw :=
  sail_returns_of_pure h

theorem sailM_pure_injective {α : Type} {a b : α}
    (h : (pure a : SailM α) = pure b) : a = b := by
  have h_app :=
    congrFun h
      (default : PreSail.SequentialState RegisterType Sail.trivialChoiceSource)
  simpa [EStateM.pure] using h_app

/-- The Step 3 pilot domain: Sail decodes the raw word to RV64 ADD and the
generated Sail encoder maps that constructor back to the same raw word. -/
def SailAddExecutableRaw (raw : RawInstruction) : Prop :=
  ∃ rs2 rs1 rd,
    let inst := instruction.RTYPE (rs2, rs1, rd, rop.ADD)
    SailDecodesTo raw inst ∧ SailEncodesTo inst raw

/-- Sail RTYPE register-ALU constructor surface. -/
def SailRegisterAluInstruction (inst : instruction) : Prop :=
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.ADD)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.SUB)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.SLL)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.SLT)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.SLTU)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.XOR)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.SRL)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.SRA)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.OR)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.AND))

/-- Sail RTYPEW register-word-ALU constructor surface. -/
def SailRegisterWordAluInstruction (inst : instruction) : Prop :=
  (∃ rs2 rs1 rd, inst = instruction.RTYPEW (rs2, rs1, rd, ropw.ADDW)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPEW (rs2, rs1, rd, ropw.SUBW)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPEW (rs2, rs1, rd, ropw.SLLW)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPEW (rs2, rs1, rd, ropw.SRLW)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPEW (rs2, rs1, rd, ropw.SRAW))

/-- Sail M-extension constructor surface implemented by ZisK RV64IM. -/
def SailMExtensionInstruction (inst : instruction) : Prop :=
  (∃ rs2 rs1 rd,
    inst = instruction.MUL (rs2, rs1, rd,
      { result_part := VectorHalf.Low,
        signed_rs1 := Signedness.Signed,
        signed_rs2 := Signedness.Signed })) ∨
  (∃ rs2 rs1 rd,
    inst = instruction.MUL (rs2, rs1, rd,
      { result_part := VectorHalf.High,
        signed_rs1 := Signedness.Signed,
        signed_rs2 := Signedness.Signed })) ∨
  (∃ rs2 rs1 rd,
    inst = instruction.MUL (rs2, rs1, rd,
      { result_part := VectorHalf.High,
        signed_rs1 := Signedness.Signed,
        signed_rs2 := Signedness.Unsigned })) ∨
  (∃ rs2 rs1 rd,
    inst = instruction.MUL (rs2, rs1, rd,
      { result_part := VectorHalf.High,
        signed_rs1 := Signedness.Unsigned,
        signed_rs2 := Signedness.Unsigned })) ∨
  (∃ rs2 rs1 rd, inst = instruction.MULW (rs2, rs1, rd)) ∨
  (∃ rs2 rs1 rd, inst = instruction.DIV (rs2, rs1, rd, false)) ∨
  (∃ rs2 rs1 rd, inst = instruction.DIV (rs2, rs1, rd, true)) ∨
  (∃ rs2 rs1 rd, inst = instruction.DIVW (rs2, rs1, rd, false)) ∨
  (∃ rs2 rs1 rd, inst = instruction.DIVW (rs2, rs1, rd, true)) ∨
  (∃ rs2 rs1 rd, inst = instruction.REM (rs2, rs1, rd, false)) ∨
  (∃ rs2 rs1 rd, inst = instruction.REM (rs2, rs1, rd, true)) ∨
  (∃ rs2 rs1 rd, inst = instruction.REMW (rs2, rs1, rd, false)) ∨
  (∃ rs2 rs1 rd, inst = instruction.REMW (rs2, rs1, rd, true))

/-- Compatibility name for the already-closed ADD/SUB pilot surface. -/
def SailRegisterPilotInstruction (inst : instruction) : Prop :=
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.ADD)) ∨
  (∃ rs2 rs1 rd, inst = instruction.RTYPE (rs2, rs1, rd, rop.SUB))

/-- RV64IM constructor whitelist.  Later steps should add the remaining
register/immediate/load/store/branch/upper/jump/FENCE constructor families. -/
def SailRv64imInstruction (inst : instruction) : Prop :=
  SailRegisterAluInstruction inst ∨
  SailRegisterWordAluInstruction inst ∨
  SailMExtensionInstruction inst

def SailPureRv64imInstruction (inst : instruction) : Prop :=
  SailRegisterAluInstruction inst ∨
  SailRegisterWordAluInstruction inst

/-- Sail-executable raw word for the currently covered RV64IM pilot surface. -/
def SailRv64imExecutableRaw (raw : RawInstruction) : Prop :=
  ∃ inst, SailDecodesTo raw inst ∧ SailEncodesTo inst raw ∧
    SailPureRv64imInstruction inst

def SailRv64imExecutableRawIn (state : SailState) (raw : RawInstruction) : Prop :=
  ∃ inst, SailDecodesToIn state raw inst ∧ SailEncodesToIn state inst raw ∧
    SailRv64imInstruction inst

theorem sail_rv64im_executable_raw_in_of_pure
    {raw : RawInstruction}
    (h : SailRv64imExecutableRaw raw) :
    ∀ state, SailRv64imExecutableRawIn state raw := by
  intro state
  rcases h with ⟨inst, h_decode, h_encode, h_inst⟩
  exact
    ⟨inst,
      sail_decodes_to_in_of_pure h_decode state,
      sail_encodes_to_in_of_pure h_encode state,
      h_inst.elim (fun h => .inl h) (fun h => .inr (.inl h))⟩

theorem sail_add_executable_implies_rv64im_executable
    {raw : RawInstruction} :
    SailAddExecutableRaw raw → SailRv64imExecutableRaw raw := by
  intro h
  rcases h with ⟨rs2, rs1, rd, h_decode, h_encode⟩
  exact
    ⟨instruction.RTYPE (rs2, rs1, rd, rop.ADD),
      h_decode, h_encode, .inl (.inl ⟨rs2, rs1, rd, rfl⟩)⟩

theorem sail_add_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b000#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 0
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        0
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_sub_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0100000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b000#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 32
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        0
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_sll_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b001#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 0
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        1
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_slt_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b010#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 0
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        2
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_sltu_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b011#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 0
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        3
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_xor_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b100#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 0
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        4
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_srl_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b101#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 0
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        5
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_sra_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0100000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b101#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 32
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        5
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_or_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b110#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 0
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        6
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_and_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b111#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 0
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        7
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_addw_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b000#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0111011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 0
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        0
        (regidx_to_fin rd).val
        0x3b := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_subw_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0100000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b000#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0111011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 32
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        0
        (regidx_to_fin rd).val
        0x3b := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_sllw_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b001#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0111011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 0
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        1
        (regidx_to_fin rd).val
        0x3b := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_srlw_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b101#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0111011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 0
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        5
        (regidx_to_fin rd).val
        0x3b := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_sraw_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0100000#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b101#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0111011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 32
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        5
        (regidx_to_fin rd).val
        0x3b := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_mul_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b000#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        0
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_mulh_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b001#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        1
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_mulhsu_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b010#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        2
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_mulhu_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b011#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0110011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        3
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_mulw_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (0b000#3 ++
            (LeanRV64D.Functions.encdec_reg_forwards rd ++
              0b0111011#7)))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        0
        (regidx_to_fin rd).val
        0x3b := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_div_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (2#2 ++
            (LeanRV64D.Functions.bool_bits_forwards false ++
              (LeanRV64D.Functions.encdec_reg_forwards rd ++
                51#7))))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        4
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_divu_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (2#2 ++
            (LeanRV64D.Functions.bool_bits_forwards true ++
              (LeanRV64D.Functions.encdec_reg_forwards rd ++
                51#7))))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        5
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_divw_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (2#2 ++
            (LeanRV64D.Functions.bool_bits_forwards false ++
              (LeanRV64D.Functions.encdec_reg_forwards rd ++
                59#7))))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        4
        (regidx_to_fin rd).val
        0x3b := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_divuw_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (2#2 ++
            (LeanRV64D.Functions.bool_bits_forwards true ++
              (LeanRV64D.Functions.encdec_reg_forwards rd ++
                59#7))))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        5
        (regidx_to_fin rd).val
        0x3b := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_rem_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (3#2 ++
            (LeanRV64D.Functions.bool_bits_forwards false ++
              (LeanRV64D.Functions.encdec_reg_forwards rd ++
                51#7))))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        6
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_remu_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (3#2 ++
            (LeanRV64D.Functions.bool_bits_forwards true ++
              (LeanRV64D.Functions.encdec_reg_forwards rd ++
                51#7))))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        7
        (regidx_to_fin rd).val
        0x33 := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_remw_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (3#2 ++
            (LeanRV64D.Functions.bool_bits_forwards false ++
              (LeanRV64D.Functions.encdec_reg_forwards rd ++
                59#7))))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        6
        (regidx_to_fin rd).val
        0x3b := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

theorem sail_remuw_concat_eq_rawRType (rs2 rs1 rd : regidx) :
    ((0b0000001#7 ++
      (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
        (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
          (3#2 ++
            (LeanRV64D.Functions.bool_bits_forwards true ++
              (LeanRV64D.Functions.encdec_reg_forwards rd ++
                59#7))))) : RawInstruction)) =
      Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        7
        (regidx_to_fin rd).val
        0x3b := by
  cases rs2 with | Regidx rs2 =>
  cases rs1 with | Regidx rs1 =>
  cases rd with | Regidx rd =>
  native_decide +revert

/-- Generated Sail encoder fact for the ADD pilot. -/
theorem sail_encode_add_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPE (rs2, rs1, rd, rop.ADD)) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0000000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b000#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0110011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33)
  rw [sail_add_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_sub_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPE (rs2, rs1, rd, rop.SUB)) =
      pure
        (Rv64imShapes.rawRType 32
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0100000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b000#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0110011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 32
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33)
  rw [sail_sub_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_sll_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPE (rs2, rs1, rd, rop.SLL)) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          1
          (regidx_to_fin rd).val
          0x33) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0000000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b001#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0110011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          1
          (regidx_to_fin rd).val
          0x33)
  rw [sail_sll_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_slt_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPE (rs2, rs1, rd, rop.SLT)) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          2
          (regidx_to_fin rd).val
          0x33) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0000000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b010#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0110011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          2
          (regidx_to_fin rd).val
          0x33)
  rw [sail_slt_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_sltu_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPE (rs2, rs1, rd, rop.SLTU)) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          3
          (regidx_to_fin rd).val
          0x33) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0000000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b011#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0110011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          3
          (regidx_to_fin rd).val
          0x33)
  rw [sail_sltu_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_xor_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPE (rs2, rs1, rd, rop.XOR)) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          4
          (regidx_to_fin rd).val
          0x33) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0000000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b100#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0110011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          4
          (regidx_to_fin rd).val
          0x33)
  rw [sail_xor_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_srl_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPE (rs2, rs1, rd, rop.SRL)) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          5
          (regidx_to_fin rd).val
          0x33) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0000000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b101#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0110011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          5
          (regidx_to_fin rd).val
          0x33)
  rw [sail_srl_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_sra_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPE (rs2, rs1, rd, rop.SRA)) =
      pure
        (Rv64imShapes.rawRType 32
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          5
          (regidx_to_fin rd).val
          0x33) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0100000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b101#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0110011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 32
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          5
          (regidx_to_fin rd).val
          0x33)
  rw [sail_sra_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_or_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPE (rs2, rs1, rd, rop.OR)) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          6
          (regidx_to_fin rd).val
          0x33) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0000000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b110#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0110011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          6
          (regidx_to_fin rd).val
          0x33)
  rw [sail_or_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_and_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPE (rs2, rs1, rd, rop.AND)) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          7
          (regidx_to_fin rd).val
          0x33) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0000000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b111#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0110011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          7
          (regidx_to_fin rd).val
          0x33)
  rw [sail_and_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_addw_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPEW (rs2, rs1, rd, ropw.ADDW)) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x3b) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0000000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b000#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0111011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x3b)
  rw [sail_addw_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_subw_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPEW (rs2, rs1, rd, ropw.SUBW)) =
      pure
        (Rv64imShapes.rawRType 32
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x3b) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0100000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b000#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0111011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 32
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x3b)
  rw [sail_subw_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_sllw_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPEW (rs2, rs1, rd, ropw.SLLW)) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          1
          (regidx_to_fin rd).val
          0x3b) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0000000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b001#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0111011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          1
          (regidx_to_fin rd).val
          0x3b)
  rw [sail_sllw_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_srlw_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPEW (rs2, rs1, rd, ropw.SRLW)) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          5
          (regidx_to_fin rd).val
          0x3b) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0000000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b101#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0111011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          5
          (regidx_to_fin rd).val
          0x3b)
  rw [sail_srlw_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_sraw_eq_rawRType (rs2 rs1 rd : regidx) :
    LeanRV64D.Functions.encdec_forwards
        (instruction.RTYPEW (rs2, rs1, rd, ropw.SRAW)) =
      pure
        (Rv64imShapes.rawRType 32
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          5
          (regidx_to_fin rd).val
          0x3b) := by
  unfold LeanRV64D.Functions.encdec_forwards
  change
    pure
        (((0b0100000#7 ++
          (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
              (0b101#3 ++
                (LeanRV64D.Functions.encdec_reg_forwards rd ++
                  0b0111011#7)))) : RawInstruction))) =
      pure
        (Rv64imShapes.rawRType 32
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          5
          (regidx_to_fin rd).val
          0x3b)
  rw [sail_sraw_concat_eq_rawRType rs2 rs1 rd]

theorem sail_encode_mul_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.MUL (rs2, rs1, rd,
          { result_part := VectorHalf.Low,
            signed_rs1 := Signedness.Signed,
            signed_rs2 := Signedness.Signed }))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      (LeanRV64D.Functions.currentlyEnabled extension.Ext_Zmmul >>= fun __do_lift_1 =>
      if (__do_lift || __do_lift_1) = true then
        (LeanRV64D.Functions.encdec_mul_op_forwards
          { result_part := VectorHalf.Low,
            signed_rs1 := Signedness.Signed,
            signed_rs2 := Signedness.Signed } >>= fun __do_lift =>
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (__do_lift ++
                  (LeanRV64D.Functions.encdec_reg_forwards rd ++
                    0b0110011#7))))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit)) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        0
        (regidx_to_fin rd).val
        0x33) state
  apply sailM_bind_ok h_m
  apply sailM_bind_ok h_zmmul
  simp [LeanRV64D.Functions.encdec_mul_op_forwards]
  simpa using sail_mul_concat_eq_rawRType rs2 rs1 rd

theorem sail_encode_mulh_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.MUL (rs2, rs1, rd,
          { result_part := VectorHalf.High,
            signed_rs1 := Signedness.Signed,
            signed_rs2 := Signedness.Signed }))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          1
          (regidx_to_fin rd).val
          0x33) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      (LeanRV64D.Functions.currentlyEnabled extension.Ext_Zmmul >>= fun __do_lift_1 =>
      if (__do_lift || __do_lift_1) = true then
        (LeanRV64D.Functions.encdec_mul_op_forwards
          { result_part := VectorHalf.High,
            signed_rs1 := Signedness.Signed,
            signed_rs2 := Signedness.Signed } >>= fun __do_lift =>
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (__do_lift ++
                  (LeanRV64D.Functions.encdec_reg_forwards rd ++
                    0b0110011#7))))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit)) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        1
        (regidx_to_fin rd).val
        0x33) state
  apply sailM_bind_ok h_m
  apply sailM_bind_ok h_zmmul
  simp [LeanRV64D.Functions.encdec_mul_op_forwards]
  simpa using sail_mulh_concat_eq_rawRType rs2 rs1 rd

theorem sail_encode_mulhsu_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.MUL (rs2, rs1, rd,
          { result_part := VectorHalf.High,
            signed_rs1 := Signedness.Signed,
            signed_rs2 := Signedness.Unsigned }))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          2
          (regidx_to_fin rd).val
          0x33) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      (LeanRV64D.Functions.currentlyEnabled extension.Ext_Zmmul >>= fun __do_lift_1 =>
      if (__do_lift || __do_lift_1) = true then
        (LeanRV64D.Functions.encdec_mul_op_forwards
          { result_part := VectorHalf.High,
            signed_rs1 := Signedness.Signed,
            signed_rs2 := Signedness.Unsigned } >>= fun __do_lift =>
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (__do_lift ++
                  (LeanRV64D.Functions.encdec_reg_forwards rd ++
                    0b0110011#7))))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit)) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        2
        (regidx_to_fin rd).val
        0x33) state
  apply sailM_bind_ok h_m
  apply sailM_bind_ok h_zmmul
  simp [LeanRV64D.Functions.encdec_mul_op_forwards]
  simpa using sail_mulhsu_concat_eq_rawRType rs2 rs1 rd

theorem sail_encode_mulhu_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.MUL (rs2, rs1, rd,
          { result_part := VectorHalf.High,
            signed_rs1 := Signedness.Unsigned,
            signed_rs2 := Signedness.Unsigned }))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          3
          (regidx_to_fin rd).val
          0x33) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      (LeanRV64D.Functions.currentlyEnabled extension.Ext_Zmmul >>= fun __do_lift_1 =>
      if (__do_lift || __do_lift_1) = true then
        (LeanRV64D.Functions.encdec_mul_op_forwards
          { result_part := VectorHalf.High,
            signed_rs1 := Signedness.Unsigned,
            signed_rs2 := Signedness.Unsigned } >>= fun __do_lift =>
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (__do_lift ++
                  (LeanRV64D.Functions.encdec_reg_forwards rd ++
                    0b0110011#7))))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit)) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        3
        (regidx_to_fin rd).val
        0x33) state
  apply sailM_bind_ok h_m
  apply sailM_bind_ok h_zmmul
  simp [LeanRV64D.Functions.encdec_mul_op_forwards]
  simpa using sail_mulhu_concat_eq_rawRType rs2 rs1 rd

theorem sail_encode_mulw_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.MULW (rs2, rs1, rd))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x3b) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      (LeanRV64D.Functions.currentlyEnabled extension.Ext_Zmmul >>= fun __do_lift_1 =>
      if (LeanRV64D.Functions.xlen == 64 && (__do_lift || __do_lift_1)) = true then
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (0b000#3 ++
                  (LeanRV64D.Functions.encdec_reg_forwards rd ++
                    0b0111011#7)))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit)) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        0
        (regidx_to_fin rd).val
        0x3b) state
  apply sailM_bind_ok h_m
  apply sailM_bind_ok h_zmmul
  simp
  simpa using sail_mulw_concat_eq_rawRType rs2 rs1 rd

theorem sail_encode_div_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.DIV (rs2, rs1, rd, false))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          4
          (regidx_to_fin rd).val
          0x33) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, _h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      if __do_lift = true then
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (2#2 ++
                  (LeanRV64D.Functions.bool_bits_forwards false ++
                    (LeanRV64D.Functions.encdec_reg_forwards rd ++
                      51#7))))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        4
        (regidx_to_fin rd).val
        0x33) state
  apply sailM_bind_ok h_m
  simp
  simpa using sail_div_concat_eq_rawRType rs2 rs1 rd

theorem sail_encode_divu_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.DIV (rs2, rs1, rd, true))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          5
          (regidx_to_fin rd).val
          0x33) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, _h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      if __do_lift = true then
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (2#2 ++
                  (LeanRV64D.Functions.bool_bits_forwards true ++
                    (LeanRV64D.Functions.encdec_reg_forwards rd ++
                      51#7))))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        5
        (regidx_to_fin rd).val
        0x33) state
  apply sailM_bind_ok h_m
  simp
  simpa using sail_divu_concat_eq_rawRType rs2 rs1 rd

theorem sail_encode_divw_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.DIVW (rs2, rs1, rd, false))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          4
          (regidx_to_fin rd).val
          0x3b) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, _h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      if (LeanRV64D.Functions.xlen == 64 && __do_lift) = true then
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (2#2 ++
                  (LeanRV64D.Functions.bool_bits_forwards false ++
                    (LeanRV64D.Functions.encdec_reg_forwards rd ++
                      59#7))))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        4
        (regidx_to_fin rd).val
        0x3b) state
  apply sailM_bind_ok h_m
  simp
  simpa using sail_divw_concat_eq_rawRType rs2 rs1 rd

theorem sail_encode_divuw_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.DIVW (rs2, rs1, rd, true))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          5
          (regidx_to_fin rd).val
          0x3b) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, _h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      if (LeanRV64D.Functions.xlen == 64 && __do_lift) = true then
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (2#2 ++
                  (LeanRV64D.Functions.bool_bits_forwards true ++
                    (LeanRV64D.Functions.encdec_reg_forwards rd ++
                      59#7))))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        5
        (regidx_to_fin rd).val
        0x3b) state
  apply sailM_bind_ok h_m
  simp
  simpa using sail_divuw_concat_eq_rawRType rs2 rs1 rd

theorem sail_encode_rem_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.REM (rs2, rs1, rd, false))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          6
          (regidx_to_fin rd).val
          0x33) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, _h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      if __do_lift = true then
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (3#2 ++
                  (LeanRV64D.Functions.bool_bits_forwards false ++
                    (LeanRV64D.Functions.encdec_reg_forwards rd ++
                      51#7))))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        6
        (regidx_to_fin rd).val
        0x33) state
  apply sailM_bind_ok h_m
  simp
  simpa using sail_rem_concat_eq_rawRType rs2 rs1 rd

theorem sail_encode_remu_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.REM (rs2, rs1, rd, true))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          7
          (regidx_to_fin rd).val
          0x33) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, _h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      if __do_lift = true then
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (3#2 ++
                  (LeanRV64D.Functions.bool_bits_forwards true ++
                    (LeanRV64D.Functions.encdec_reg_forwards rd ++
                      51#7))))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        7
        (regidx_to_fin rd).val
        0x33) state
  apply sailM_bind_ok h_m
  simp
  simpa using sail_remu_concat_eq_rawRType rs2 rs1 rd

theorem sail_encode_remw_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.REMW (rs2, rs1, rd, false))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          6
          (regidx_to_fin rd).val
          0x3b) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, _h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      if (LeanRV64D.Functions.xlen == 64 && __do_lift) = true then
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (3#2 ++
                  (LeanRV64D.Functions.bool_bits_forwards false ++
                    (LeanRV64D.Functions.encdec_reg_forwards rd ++
                      59#7))))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        6
        (regidx_to_fin rd).val
        0x3b) state
  apply sailM_bind_ok h_m
  simp
  simpa using sail_remw_concat_eq_rawRType rs2 rs1 rd

theorem sail_encode_remuw_eq_rawRType_in
    (state : SailState) (h_state : Rv64imEnabledSailState state)
    (rs2 rs1 rd : regidx) :
    SailEncodesToIn state
        (instruction.REMW (rs2, rs1, rd, true))
        (Rv64imShapes.rawRType 1
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          7
          (regidx_to_fin rd).val
          0x3b) := by
  dsimp [SailEncodesToIn, SailReturns, Rv64imEnabledSailState] at *
  rcases h_state with ⟨h_m, _h_zmmul⟩
  unfold LeanRV64D.Functions.encdec_forwards
  change
    ((LeanRV64D.Functions.currentlyEnabled extension.Ext_M) >>= fun __do_lift =>
      if (LeanRV64D.Functions.xlen == 64 && __do_lift) = true then
        pure
          (0b0000001#7 ++
            (LeanRV64D.Functions.encdec_reg_forwards rs2 ++
              (LeanRV64D.Functions.encdec_reg_forwards rs1 ++
                (3#2 ++
                  (LeanRV64D.Functions.bool_bits_forwards true ++
                    (LeanRV64D.Functions.encdec_reg_forwards rd ++
                      59#7))))))
      else do
        Sail.assert false "Pattern match failure at unknown location"
        throw Sail.Error.Exit) state =
    EStateM.Result.ok
      (Rv64imShapes.rawRType 1
        (regidx_to_fin rs2).val
        (regidx_to_fin rs1).val
        7
        (regidx_to_fin rd).val
        0x3b) state
  apply sailM_bind_ok h_m
  simp
  simpa using sail_remuw_concat_eq_rawRType rs2 rs1 rd

/-- Constructor-level bridge for the ADD pilot.  The premises are generated Sail
decode and generated Sail encode facts, not a hand-written raw decoder. -/
theorem sail_decode_add_contained_in_add_shape
    {raw : RawInstruction} {rs2 rs1 rd : regidx}
    (_h_decode :
      SailDecodesTo raw (instruction.RTYPE (rs2, rs1, rd, rop.ADD)))
    (h_encode :
      SailEncodesTo (instruction.RTYPE (rs2, rs1, rd, rop.ADD)) raw) :
    Rv64imShapes.AddRawShape raw := by
  have h_raw :
      raw =
        Rv64imShapes.rawRType 0
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33 := by
    dsimp [SailEncodesTo] at h_encode
    rw [sail_encode_add_eq_rawRType rs2 rs1 rd] at h_encode
    exact sailM_pure_injective h_encode.symm
  subst raw
  refine
    ⟨(regidx_to_fin rd).val,
      (regidx_to_fin rs1).val,
      (regidx_to_fin rs2).val,
      ?_, ?_, ?_, rfl⟩
  · exact List.mem_range.mpr (regidx_to_fin rd).isLt
  · exact List.mem_range.mpr (regidx_to_fin rs1).isLt
  · exact List.mem_range.mpr (regidx_to_fin rs2).isLt

/-- Broad R-type containment for the ADD pilot, derived from the exact ADD
shape. -/
theorem sail_decode_add_contained_in_rtype_shape
    {raw : RawInstruction} {rs2 rs1 rd : regidx}
    (h_decode :
      SailDecodesTo raw (instruction.RTYPE (rs2, rs1, rd, rop.ADD)))
    (h_encode :
      SailEncodesTo (instruction.RTYPE (rs2, rs1, rd, rop.ADD)) raw) :
    Rv64imShapes.RTypeRegisterShape raw :=
  Rv64imShapes.add_raw_shape_subset_r_type_register_shape
    (sail_decode_add_contained_in_add_shape h_decode h_encode)

theorem sail_decode_sub_contained_in_rtype_shape
    {raw : RawInstruction} {rs2 rs1 rd : regidx}
    (_h_decode :
      SailDecodesTo raw (instruction.RTYPE (rs2, rs1, rd, rop.SUB)))
    (h_encode :
      SailEncodesTo (instruction.RTYPE (rs2, rs1, rd, rop.SUB)) raw) :
    Rv64imShapes.RTypeRegisterShape raw := by
  have h_raw :
      raw =
        Rv64imShapes.rawRType 32
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          0
          (regidx_to_fin rd).val
          0x33 := by
    dsimp [SailEncodesTo] at h_encode
    rw [sail_encode_sub_eq_rawRType rs2 rs1 rd] at h_encode
    exact sailM_pure_injective h_encode.symm
  subst raw
  refine
    ⟨32, 0, 0x33,
      (regidx_to_fin rd).val,
      (regidx_to_fin rs1).val,
      (regidx_to_fin rs2).val,
      ?_, ?_, ?_, ?_, rfl⟩
  · simp [Rv64imShapes.allRTypeOpcodeShapes]
  · exact List.mem_range.mpr (regidx_to_fin rd).isLt
  · exact List.mem_range.mpr (regidx_to_fin rs1).isLt
  · exact List.mem_range.mpr (regidx_to_fin rs2).isLt

theorem rawRType_mem_contained_in_rtype_shape
    {funct7 funct3 opcode rd rs1 rs2 : Nat}
    (h_mem : (funct7, funct3, opcode) ∈ Rv64imShapes.allRTypeOpcodeShapes)
    (h_rd : rd ∈ Rv64imShapes.allRvRegs)
    (h_rs1 : rs1 ∈ Rv64imShapes.allRvRegs)
    (h_rs2 : rs2 ∈ Rv64imShapes.allRvRegs) :
    Rv64imShapes.RTypeRegisterShape
      (Rv64imShapes.rawRType funct7 rs2 rs1 funct3 rd opcode) :=
  ⟨funct7, funct3, opcode, rd, rs1, rs2,
    h_mem, h_rd, h_rs1, h_rs2, rfl⟩

theorem sail_decode_rtype_contained_in_rtype_shape
    {raw : RawInstruction} {rs2 rs1 rd : regidx}
    (h_encode :
      SailEncodesTo (instruction.RTYPE (rs2, rs1, rd, op)) raw)
    (h_encode_op :
      LeanRV64D.Functions.encdec_forwards
          (instruction.RTYPE (rs2, rs1, rd, op)) =
        pure
          (Rv64imShapes.rawRType funct7
            (regidx_to_fin rs2).val
            (regidx_to_fin rs1).val
            funct3
            (regidx_to_fin rd).val
            opcode))
    (h_mem : (funct7, funct3, opcode) ∈ Rv64imShapes.allRTypeOpcodeShapes) :
    Rv64imShapes.RTypeRegisterShape raw := by
  have h_raw :
      raw =
        Rv64imShapes.rawRType funct7
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          funct3
          (regidx_to_fin rd).val
          opcode := by
    dsimp [SailEncodesTo] at h_encode
    rw [h_encode_op] at h_encode
    exact sailM_pure_injective h_encode.symm
  subst raw
  exact
    rawRType_mem_contained_in_rtype_shape
      h_mem
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)

theorem sail_decode_rtypew_contained_in_rtype_shape
    {raw : RawInstruction} {rs2 rs1 rd : regidx}
    (h_encode :
      SailEncodesTo (instruction.RTYPEW (rs2, rs1, rd, op)) raw)
    (h_encode_op :
      LeanRV64D.Functions.encdec_forwards
          (instruction.RTYPEW (rs2, rs1, rd, op)) =
        pure
          (Rv64imShapes.rawRType funct7
            (regidx_to_fin rs2).val
            (regidx_to_fin rs1).val
            funct3
            (regidx_to_fin rd).val
            opcode))
    (h_mem : (funct7, funct3, opcode) ∈ Rv64imShapes.allRTypeOpcodeShapes) :
    Rv64imShapes.RTypeRegisterShape raw := by
  have h_raw :
      raw =
        Rv64imShapes.rawRType funct7
          (regidx_to_fin rs2).val
          (regidx_to_fin rs1).val
          funct3
          (regidx_to_fin rd).val
          opcode := by
    dsimp [SailEncodesTo] at h_encode
    rw [h_encode_op] at h_encode
    exact sailM_pure_injective h_encode.symm
  subst raw
  exact
    rawRType_mem_contained_in_rtype_shape
      h_mem
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)

theorem sail_encode_rawRType_contained_in_rtype_shape_in
    {raw : RawInstruction} {inst : instruction} {state : SailState}
    {funct7 funct3 opcode rd rs1 rs2 : Nat}
    (h_encode : SailEncodesToIn state inst raw)
    (h_encode_op :
      SailEncodesToIn state inst
        (Rv64imShapes.rawRType funct7 rs2 rs1 funct3 rd opcode))
    (h_mem : (funct7, funct3, opcode) ∈ Rv64imShapes.allRTypeOpcodeShapes)
    (h_rd : rd ∈ Rv64imShapes.allRvRegs)
    (h_rs1 : rs1 ∈ Rv64imShapes.allRvRegs)
    (h_rs2 : rs2 ∈ Rv64imShapes.allRvRegs) :
    Rv64imShapes.RTypeRegisterShape raw := by
  have h_raw : raw = Rv64imShapes.rawRType funct7 rs2 rs1 funct3 rd opcode := by
    dsimp [SailEncodesToIn, SailReturns] at h_encode h_encode_op
    rw [h_encode_op] at h_encode
    simpa using h_encode.symm
  subst raw
  exact rawRType_mem_contained_in_rtype_shape h_mem h_rd h_rs1 h_rs2

theorem sail_decode_rtype_contained_in_rtype_shape_in
    {raw : RawInstruction} {state : SailState} {rs2 rs1 rd : regidx}
    (h_encode :
      SailEncodesToIn state (instruction.RTYPE (rs2, rs1, rd, op)) raw)
    (h_encode_op :
      LeanRV64D.Functions.encdec_forwards
          (instruction.RTYPE (rs2, rs1, rd, op)) =
        pure
          (Rv64imShapes.rawRType funct7
            (regidx_to_fin rs2).val
            (regidx_to_fin rs1).val
            funct3
            (regidx_to_fin rd).val
            opcode))
    (h_mem : (funct7, funct3, opcode) ∈ Rv64imShapes.allRTypeOpcodeShapes) :
    Rv64imShapes.RTypeRegisterShape raw :=
  sail_encode_rawRType_contained_in_rtype_shape_in
    h_encode
    (sail_encodes_to_in_of_pure h_encode_op state)
    h_mem
    (List.mem_range.mpr (regidx_to_fin rd).isLt)
    (List.mem_range.mpr (regidx_to_fin rs1).isLt)
    (List.mem_range.mpr (regidx_to_fin rs2).isLt)

theorem sail_decode_rtypew_contained_in_rtype_shape_in
    {raw : RawInstruction} {state : SailState} {rs2 rs1 rd : regidx}
    (h_encode :
      SailEncodesToIn state (instruction.RTYPEW (rs2, rs1, rd, op)) raw)
    (h_encode_op :
      LeanRV64D.Functions.encdec_forwards
          (instruction.RTYPEW (rs2, rs1, rd, op)) =
        pure
          (Rv64imShapes.rawRType funct7
            (regidx_to_fin rs2).val
            (regidx_to_fin rs1).val
            funct3
            (regidx_to_fin rd).val
            opcode))
    (h_mem : (funct7, funct3, opcode) ∈ Rv64imShapes.allRTypeOpcodeShapes) :
    Rv64imShapes.RTypeRegisterShape raw :=
  sail_encode_rawRType_contained_in_rtype_shape_in
    h_encode
    (sail_encodes_to_in_of_pure h_encode_op state)
    h_mem
    (List.mem_range.mpr (regidx_to_fin rd).isLt)
    (List.mem_range.mpr (regidx_to_fin rs1).isLt)
    (List.mem_range.mpr (regidx_to_fin rs2).isLt)

/-- Pilot Step 3 exact-shape containment for ADD. -/
theorem sail_add_executable_contained_in_add_shape :
    ∀ raw,
      SailAddExecutableRaw raw →
      Rv64imShapes.AddRawShape raw := by
  intro raw h_sail
  rcases h_sail with ⟨rs2, rs1, rd, h_decode, h_encode⟩
  exact
    sail_decode_add_contained_in_add_shape
      h_decode
      h_encode

/-- Pilot Step 3 broad-shape containment for ADD. -/
theorem sail_add_executable_contained :
    ∀ raw,
      SailAddExecutableRaw raw →
      Rv64imShapes.RTypeRegisterShape raw := by
  intro raw h_sail
  exact
    Rv64imShapes.add_raw_shape_subset_r_type_register_shape
      (sail_add_executable_contained_in_add_shape raw h_sail)

def AddCompleteness (iface : Rv.Interface) : Prop :=
  ∀ raw, SailAddExecutableRaw raw → Rv.Interface.ziskCircuitCovered iface raw

theorem add_completeness_of_shape_circuit_covered_known_good
    (iface : Rv.Interface)
    (h_covered :
      Rv.Interface.ShapeCircuitCoveredKnownGood
        iface
        Rv64imShapes.AddRawShape) :
    AddCompleteness iface := by
  intro raw h_sail
  exact
    (h_covered raw
      (sail_add_executable_contained_in_add_shape raw h_sail)).left

theorem sail_register_pilot_executable_contained :
    ∀ raw inst,
      SailDecodesTo raw inst →
      SailEncodesTo inst raw →
      SailRegisterPilotInstruction inst →
      Rv64imShapes.RTypeRegisterShape raw := by
  intro raw inst h_decode h_encode h_inst
  rcases h_inst with
    ⟨rs2, rs1, rd, h_eq⟩ | ⟨rs2, rs1, rd, h_eq⟩
  · rw [h_eq] at h_decode h_encode
    exact sail_decode_add_contained_in_rtype_shape h_decode h_encode
  · rw [h_eq] at h_decode h_encode
    exact sail_decode_sub_contained_in_rtype_shape h_decode h_encode

theorem sail_register_alu_executable_contained :
    ∀ raw inst,
      SailDecodesTo raw inst →
      SailEncodesTo inst raw →
      SailRegisterAluInstruction inst →
      Rv64imShapes.RTypeRegisterShape raw := by
  intro raw inst _h_decode h_encode h_inst
  rcases h_inst with
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape h_encode
      (sail_encode_add_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape h_encode
      (sail_encode_sub_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape h_encode
      (sail_encode_sll_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape h_encode
      (sail_encode_slt_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape h_encode
      (sail_encode_sltu_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape h_encode
      (sail_encode_xor_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape h_encode
      (sail_encode_srl_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape h_encode
      (sail_encode_sra_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape h_encode
      (sail_encode_or_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape h_encode
      (sail_encode_and_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])

theorem sail_register_word_alu_executable_contained :
    ∀ raw inst,
      SailDecodesTo raw inst →
      SailEncodesTo inst raw →
      SailRegisterWordAluInstruction inst →
      Rv64imShapes.RTypeRegisterShape raw := by
  intro raw inst _h_decode h_encode h_inst
  rcases h_inst with
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩
  · rw [h_eq] at h_encode
    exact sail_decode_rtypew_contained_in_rtype_shape h_encode
      (sail_encode_addw_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtypew_contained_in_rtype_shape h_encode
      (sail_encode_subw_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtypew_contained_in_rtype_shape h_encode
      (sail_encode_sllw_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtypew_contained_in_rtype_shape h_encode
      (sail_encode_srlw_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtypew_contained_in_rtype_shape h_encode
      (sail_encode_sraw_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])

theorem sail_register_alu_executable_contained_in :
    ∀ state raw inst,
      SailDecodesToIn state raw inst →
      SailEncodesToIn state inst raw →
      SailRegisterAluInstruction inst →
      Rv64imShapes.RTypeRegisterShape raw := by
  intro state raw inst _h_decode h_encode h_inst
  rcases h_inst with
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape_in h_encode
      (sail_encode_add_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape_in h_encode
      (sail_encode_sub_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape_in h_encode
      (sail_encode_sll_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape_in h_encode
      (sail_encode_slt_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape_in h_encode
      (sail_encode_sltu_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape_in h_encode
      (sail_encode_xor_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape_in h_encode
      (sail_encode_srl_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape_in h_encode
      (sail_encode_sra_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape_in h_encode
      (sail_encode_or_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtype_contained_in_rtype_shape_in h_encode
      (sail_encode_and_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])

theorem sail_register_word_alu_executable_contained_in :
    ∀ state raw inst,
      SailDecodesToIn state raw inst →
      SailEncodesToIn state inst raw →
      SailRegisterWordAluInstruction inst →
      Rv64imShapes.RTypeRegisterShape raw := by
  intro state raw inst _h_decode h_encode h_inst
  rcases h_inst with
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩
  · rw [h_eq] at h_encode
    exact sail_decode_rtypew_contained_in_rtype_shape_in h_encode
      (sail_encode_addw_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtypew_contained_in_rtype_shape_in h_encode
      (sail_encode_subw_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtypew_contained_in_rtype_shape_in h_encode
      (sail_encode_sllw_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtypew_contained_in_rtype_shape_in h_encode
      (sail_encode_srlw_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
  · rw [h_eq] at h_encode
    exact sail_decode_rtypew_contained_in_rtype_shape_in h_encode
      (sail_encode_sraw_eq_rawRType rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])

theorem sail_m_extension_executable_contained_in :
    ∀ state raw inst,
      Rv64imEnabledSailState state →
      SailDecodesToIn state raw inst →
      SailEncodesToIn state inst raw →
      SailMExtensionInstruction inst →
      Rv64imShapes.RTypeRegisterShape raw := by
  intro state raw inst h_state _h_decode h_encode h_inst
  rcases h_inst with
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩ |
    ⟨rs2, rs1, rd, h_eq⟩
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_mul_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_mulh_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_mulhsu_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_mulhu_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_mulw_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_div_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_divu_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_divw_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_divuw_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_rem_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_remu_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_remw_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)
  · rw [h_eq] at h_encode
    exact sail_encode_rawRType_contained_in_rtype_shape_in h_encode
      (sail_encode_remuw_eq_rawRType_in state h_state rs2 rs1 rd)
      (by simp [Rv64imShapes.allRTypeOpcodeShapes])
      (List.mem_range.mpr (regidx_to_fin rd).isLt)
      (List.mem_range.mpr (regidx_to_fin rs1).isLt)
      (List.mem_range.mpr (regidx_to_fin rs2).isLt)

theorem sail_rv64im_executable_contained_in_supported_decode :
    ∀ raw,
      SailRv64imExecutableRaw raw →
      Rv64imShapes.SupportedDecodeShape raw := by
  intro raw h_sail
  rcases h_sail with ⟨inst, h_decode, h_encode, h_inst⟩
  rcases h_inst with h_register_alu | h_register_word_alu
  · exact .inl
      (sail_register_alu_executable_contained
        raw inst h_decode h_encode h_register_alu)
  · exact .inl
      (sail_register_word_alu_executable_contained
        raw inst h_decode h_encode h_register_word_alu)

theorem sail_rv64im_executable_contained_in_supported_decode_pilot :
    ∀ raw,
      SailRv64imExecutableRaw raw →
      Rv64imShapes.SupportedDecodeShape raw :=
  sail_rv64im_executable_contained_in_supported_decode

theorem sail_rv64im_executable_contained_in_supported_decode_in :
    ∀ state raw,
      Rv64imEnabledSailState state →
      SailRv64imExecutableRawIn state raw →
      Rv64imShapes.SupportedDecodeShape raw := by
  intro state raw h_state h_sail
  rcases h_sail with ⟨inst, h_decode, h_encode, h_inst⟩
  rcases h_inst with h_register_alu | h_tail
  · exact .inl
      (sail_register_alu_executable_contained_in
        state raw inst h_decode h_encode h_register_alu)
  rcases h_tail with h_register_word_alu | h_m_extension
  · exact .inl
      (sail_register_word_alu_executable_contained_in
        state raw inst h_decode h_encode h_register_word_alu)
  · exact .inl
      (sail_m_extension_executable_contained_in
        state raw inst h_state h_decode h_encode h_m_extension)

end ZiskFv.Completeness.SailDecode
