name = "zisk-fv"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ZiskFv"]
moreLeanArgs = ["--tstack=400000"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"

[[require]]
name = "LeanZKCircuit"
git = "https://github.com/NethermindEth/leanzkcircuit.git"
rev = "v4.26.0"

[[require]]
name = "LeanRV"
git = "https://github.com/NethermindEth/sail-riscv-lean"
rev = "main"

[[lean_lib]]
name = "ZiskFv"
