#!/usr/bin/env bash
# Serve the zisk-fv proof-tree visualizer on port 4042 (defaults to 0.0.0.0).
# Usage: ./trust/proof-tree/serve.sh
#
# The page reads trust/proof-tree/edges.tsv, generated by:
#   nix develop --command lake exe trust-gate print-tree-edges \
#     ZiskFv.Compliance.zisk_riscv_compliant_program_bus \
#     > trust/proof-tree/edges.tsv
set -euo pipefail
cd "$(dirname "$0")"
PORT="${PORT:-4042}"
echo "zisk-fv proof tree on http://0.0.0.0:${PORT}"
exec python3 -m http.server "${PORT}" --bind 0.0.0.0
