import Clean.Circuit.Lookup
import ZiskFv.Channels.BinaryExtensionTable

/-!
# BinaryExtensionTable — Clean `StaticTable` provider side

ZisK's BinaryExtension virtual table has
`6 * 2^19 + 3 * 2^11` meaningful rows. The PIL table is generated by a
deterministic arithmetic indexer over `(op, byte_index, a_byte,
shift_amount)`; see
`zisk/state-machines/binary/pil/binary_extension_table.pil`.

This module gives the provider side as a non-enumerated Clean
`StaticTable`: `row i` decodes the same arithmetic row, and `Spec` is exact
membership in that decoded row set. This is the faithful large-ROM pattern;
there is no `decide` over millions of literal rows.

It intentionally does not retire `bin_ext_table_consumer_wf` by itself.
Load-bearing retirement still needs the consumer lookup path and this
provider table to be connected in the terminal Binary-family ensemble.

## Trust note

No axioms. The membership predicate is exact decoded-row membership, and
`contains_iff` is definitional.
-/

namespace ZiskFv.AirsClean.BinaryExtensionTable

open Goldilocks
open ZiskFv.Channels.BinaryExtensionTable

def shiftBlockSize : ℕ := 2 ^ 19
def sextBlockSize : ℕ := 2 ^ 11
def tableSize : ℕ := 6 * shiftBlockSize + 3 * sextBlockSize

def opOfBlock (block : ℕ) : ℕ :=
  if block = 0 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SLL
  else if block = 1 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SRL
  else if block = 2 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SRA
  else if block = 3 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SLL_W
  else if block = 4 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SRL_W
  else if block = 5 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SRA_W
  else if block = 6 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SEXT_B
  else if block = 7 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SEXT_H
  else ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SEXT_W

@[reducible]
def lowByte (i : ℕ) : ℕ := i % 256

@[reducible]
def byteIndex (i : ℕ) : ℕ := (i / 256) % 8

@[reducible]
def shiftAmount (i : ℕ) : ℕ :=
  if i < 6 * shiftBlockSize then (i / sextBlockSize) % 256 else 0

@[reducible]
def blockOfIndex (i : ℕ) : ℕ :=
  if i < 6 * shiftBlockSize then i / shiftBlockSize
  else 6 + (i - 6 * shiftBlockSize) / sextBlockSize

theorem blockOfIndex_lt_9 (i : Fin tableSize) : blockOfIndex i.val < 9 := by
  have h_i : i.val < tableSize := i.isLt
  unfold blockOfIndex tableSize shiftBlockSize sextBlockSize at *
  split
  · have h_div : i.val / 2 ^ 19 < 6 := Nat.div_lt_of_lt_mul (by omega)
    omega
  · have h_tail : i.val - 6 * 2 ^ 19 < 3 * 2 ^ 11 := by omega
    have h_div : (i.val - 6 * 2 ^ 19) / 2 ^ 11 < 3 :=
      Nat.div_lt_of_lt_mul (by omega)
    omega

@[reducible]
def opOfIndex (i : ℕ) : ℕ := opOfBlock (blockOfIndex i)

@[reducible]
def sllOut (a offset b : ℕ) : ℕ :=
  (a * 256 ^ offset * 2 ^ (b % 64)) % 2 ^ 64

@[reducible]
def srlOut (a offset b : ℕ) : ℕ :=
  (a * 256 ^ offset) / 2 ^ (b % 64)

@[reducible]
def sraOut (a offset b : ℕ) : ℕ :=
  let s := b % 64
  let base := (a * 256 ^ offset) / 2 ^ s
  let ext := if offset = 7 ∧ a ≥ 128 then 2 ^ 64 - 2 ^ (64 - s) else 0
  base + ext

@[reducible]
def sllwOut (a offset b : ℕ) : ℕ :=
  let s := b % 32
  let positioned := a * 256 ^ offset
  let inner := if offset < 4 then (positioned * 2 ^ s) % 2 ^ 32 else 0
  inner + if inner ≥ 2 ^ 31 then 2 ^ 64 - 2 ^ 32 else 0

@[reducible]
def srlwOut (a offset b : ℕ) : ℕ :=
  let s := b % 32
  let positioned := a * 256 ^ offset
  let inner := if offset < 4 then positioned / 2 ^ s else 0
  inner + if inner ≥ 2 ^ 31 then 2 ^ 64 - 2 ^ 32 else 0

@[reducible]
def srawOut (a offset b : ℕ) : ℕ :=
  let s := b % 32
  let positioned := a * 256 ^ offset
  let base := if offset < 4 then positioned / 2 ^ s else 0
  let ext := if offset = 3 ∧ a ≥ 128 then 2 ^ 64 - 2 ^ (32 - s) else 0
  base + ext

@[reducible]
def sextbOut (a offset : ℕ) : ℕ :=
  if offset = 0 then
    if a ≥ 128 then a + (2 ^ 64 - 256) else a
  else 0

@[reducible]
def sexthOut (a offset : ℕ) : ℕ :=
  if offset = 0 then a
  else if offset = 1 then
    let aPos := a * 256
    if a ≥ 128 then aPos + (2 ^ 64 - 2 ^ 16) else aPos
  else 0

@[reducible]
def sextwOut (a offset : ℕ) : ℕ :=
  if offset < 4 then
    let aPos := a * 256 ^ offset
    if offset = 3 ∧ a ≥ 128 then aPos + (2 ^ 64 - 2 ^ 32) else aPos
  else 0

private theorem wmode_signext_lo_val (inner : ℕ) (h_inner : inner < 4294967296) :
    (((inner + (if inner ≥ 2147483648 then 18446744069414584320 else 0) : ℕ) %
        4294967296 : ℕ) : FGL).val =
      inner := by
  by_cases h_sign : inner ≥ 2147483648
  · rw [if_pos h_sign]
    rw [Fin.val_natCast]
    rw [show 18446744069414584320 = 4294967296 * 4294967295 by norm_num]
    rw [Nat.add_mul_mod_self_left, Nat.mod_eq_of_lt h_inner]
    exact Nat.mod_eq_of_lt (by omega)
  · rw [if_neg h_sign]
    rw [Fin.val_natCast]
    change inner % 4294967296 % 18446744069414584321 = inner
    rw [Nat.mod_eq_of_lt h_inner]
    exact Nat.mod_eq_of_lt (by omega)

private theorem wmode_signext_hi_val (inner : ℕ) (h_inner : inner < 4294967296) :
    (((inner + (if inner ≥ 2147483648 then 18446744069414584320 else 0) : ℕ) /
        4294967296 : ℕ) : FGL).val =
      (if inner ≥ 2147483648 then 4294967295 else 0) := by
  by_cases h_sign : inner ≥ 2147483648
  · rw [if_pos h_sign, if_pos h_sign]
    rw [Fin.val_natCast]
    rw [show 18446744069414584320 = 4294967296 * 4294967295 by norm_num]
    rw [Nat.add_mul_div_left _ _ (by norm_num : 0 < 4294967296)]
    rw [Nat.div_eq_of_lt h_inner]
  · rw [if_neg h_sign, if_neg h_sign]
    rw [Fin.val_natCast]
    change inner / 4294967296 % 18446744069414584321 = 0
    rw [Nat.div_eq_of_lt h_inner]

@[reducible]
def outOfIndex (i : ℕ) : ℕ :=
  let a := lowByte i
  let offset := byteIndex i
  let b := shiftAmount i
  match blockOfIndex i with
  | 0 => sllOut a offset b
  | 1 => srlOut a offset b
  | 2 => sraOut a offset b
  | 3 => sllwOut a offset b
  | 4 => srlwOut a offset b
  | 5 => srawOut a offset b
  | 6 => sextbOut a offset
  | 7 => sexthOut a offset
  | _ => sextwOut a offset

@[reducible]
def opIsShiftOfIndex (i : ℕ) : ℕ :=
  if blockOfIndex i < 6 then 1 else 0

theorem opIsShiftOfIndex_eq_one_of_block_lt_6 {i : Fin tableSize}
    (h_block : blockOfIndex i.val < 6) :
    (opIsShiftOfIndex i.val : FGL).val = 1 := by
  simp [opIsShiftOfIndex, h_block]

theorem opIsShiftOfIndex_eq_zero_of_block_ge_6 {i : Fin tableSize}
    (h_block : 6 ≤ blockOfIndex i.val) :
    (opIsShiftOfIndex i.val : FGL).val = 0 := by
  have h_not : ¬ blockOfIndex i.val < 6 := by omega
  simp [opIsShiftOfIndex, h_not]

/-- Decoded row `i` of the BinaryExtensionTable, as a Clean channel
    payload. -/
@[reducible]
def rowOfIndex (i : ℕ) : BinaryExtensionTableMessage FGL :=
  let out := outOfIndex i
  { op := opOfIndex i
    byte_index := byteIndex i
    a_byte := lowByte i
    shift_amount := shiftAmount i
    c_lo_byte := (out % 2 ^ 32 : ℕ)
    c_hi_byte := (out / 2 ^ 32 : ℕ)
    op_is_shift := opIsShiftOfIndex i }

theorem rowOfIndex_op_is_shift_eq_one_of_block_lt_6 {i : Fin tableSize}
    (h_block : blockOfIndex i.val < 6) :
    (rowOfIndex i.val).op_is_shift.val = 1 := by
  change (opIsShiftOfIndex i.val : FGL).val = 1
  exact opIsShiftOfIndex_eq_one_of_block_lt_6 (i := i) h_block

theorem rowOfIndex_op_is_shift_eq_zero_of_block_ge_6 {i : Fin tableSize}
    (h_block : 6 ≤ blockOfIndex i.val) :
    (rowOfIndex i.val).op_is_shift.val = 0 := by
  change (opIsShiftOfIndex i.val : FGL).val = 0
  exact opIsShiftOfIndex_eq_zero_of_block_ge_6 (i := i) h_block

/-- Exact decoded-row membership for the BinaryExtensionTable provider. -/
def binaryExtensionTable : StaticTable FGL BinaryExtensionTableMessage where
  name := "binary_extension_table"
  length := tableSize
  row i := rowOfIndex i.val
  index t := t.op.val
  Spec t := ∃ i : Fin tableSize, t = rowOfIndex i.val
  contains_iff := by intro t; rfl

theorem spec_iff (t : BinaryExtensionTableMessage FGL) :
    binaryExtensionTable.Spec t ↔ ∃ i : Fin tableSize, t = rowOfIndex i.val :=
  Iff.rfl

open ZiskFv.Airs.Tables.BinaryExtensionTable in
/-- BinaryExtensionTable rows cover shift and sign-extension opcodes only;
    they cannot be the Binary-table bitwise opcodes `14`, `15`, or `16`
    (`AND`, `OR`, `XOR`). -/
theorem spec_op_val_ne_bitwise {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    t.op.val ≠ 14 ∧ t.op.val ≠ 15 ∧ t.op.val ≠ 16 := by
  rcases h with ⟨i, rfl⟩
  change (opOfIndex i.val : FGL).val ≠ 14
    ∧ (opOfIndex i.val : FGL).val ≠ 15
    ∧ (opOfIndex i.val : FGL).val ≠ 16
  have h_block_lt : blockOfIndex i.val < 9 := blockOfIndex_lt_9 i
  unfold opOfIndex
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 9 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block
  all_goals
    constructor
    · unfold opOfBlock
      norm_num [OP_SLL, OP_SRL, OP_SRA, OP_SLL_W, OP_SRL_W, OP_SRA_W,
        OP_SEXT_B, OP_SEXT_H, OP_SEXT_W]
    · constructor
      · unfold opOfBlock
        norm_num [OP_SLL, OP_SRL, OP_SRA, OP_SLL_W, OP_SRL_W, OP_SRA_W,
          OP_SEXT_B, OP_SEXT_H, OP_SEXT_W]
      · unfold opOfBlock
        norm_num [OP_SLL, OP_SRL, OP_SRA, OP_SLL_W, OP_SRL_W, OP_SRA_W,
          OP_SEXT_B, OP_SEXT_H, OP_SEXT_W]

open ZiskFv.Airs.Tables.BinaryExtensionTable in
/-- BinaryExtensionTable rows cover shift and sign-extension opcodes only;
    they cannot be the Binary-table comparison opcodes `6` or `7`
    (`LTU`, `LT`). -/
theorem spec_op_val_ne_compare {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    t.op.val ≠ 6 ∧ t.op.val ≠ 7 := by
  rcases h with ⟨i, rfl⟩
  change (opOfIndex i.val : FGL).val ≠ 6
    ∧ (opOfIndex i.val : FGL).val ≠ 7
  have h_block_lt : blockOfIndex i.val < 9 := blockOfIndex_lt_9 i
  unfold opOfIndex
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 9 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block
  all_goals
    constructor
    · unfold opOfBlock
      norm_num [OP_SLL, OP_SRL, OP_SRA, OP_SLL_W, OP_SRL_W, OP_SRA_W,
        OP_SEXT_B, OP_SEXT_H, OP_SEXT_W]
    · unfold opOfBlock
      norm_num [OP_SLL, OP_SRL, OP_SRA, OP_SLL_W, OP_SRL_W, OP_SRA_W,
        OP_SEXT_B, OP_SEXT_H, OP_SEXT_W]

open ZiskFv.Airs.Tables.BinaryExtensionTable in
/-- BinaryExtensionTable rows cover shift and sign-extension opcodes only;
    they cannot be the Main W-mode ADD/SUB opcodes `0x1A` or `0x1B`. -/
theorem spec_op_val_ne_W_add_sub {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    t.op.val ≠ 0x1A ∧ t.op.val ≠ 0x1B := by
  rcases h with ⟨i, rfl⟩
  change (opOfIndex i.val : FGL).val ≠ 0x1A
    ∧ (opOfIndex i.val : FGL).val ≠ 0x1B
  have h_block_lt : blockOfIndex i.val < 9 := blockOfIndex_lt_9 i
  unfold opOfIndex
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 9 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block
  all_goals
    constructor
    · unfold opOfBlock
      norm_num [OP_SLL, OP_SRL, OP_SRA, OP_SLL_W, OP_SRL_W, OP_SRA_W,
        OP_SEXT_B, OP_SEXT_H, OP_SEXT_W]
    · unfold opOfBlock
      norm_num [OP_SLL, OP_SRL, OP_SRA, OP_SLL_W, OP_SRL_W, OP_SRA_W,
        OP_SEXT_B, OP_SEXT_H, OP_SEXT_W]

open ZiskFv.Airs.Tables.BinaryExtensionTable in
/-- The static decoder always produces the byte/range side of the legacy
    BinaryExtensionTable semantic predicate. This is the first reusable
    membership-to-semantics projection; the per-op output equations are
    proved separately to keep the arithmetic cases tractable. -/
theorem rowOfIndex_range_conditions (i : Fin tableSize) :
    range_conditions (BinaryExtensionTableMessage.toEntry (rowOfIndex i.val) 1) := by
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_byte : byteIndex i.val < 8 := by
    unfold byteIndex
    exact Nat.mod_lt _ (by norm_num)
  have h_shift : shiftAmount i.val < 256 := by
    unfold shiftAmount
    split
    · exact Nat.mod_lt _ (by norm_num)
    · norm_num
  simp only [range_conditions]
  constructor
  · rw [Fin.val_natCast]
    omega
  constructor
  · rw [Fin.val_natCast]
    omega
  · rw [Fin.val_natCast]
    omega

open ZiskFv.Airs.Tables.BinaryExtensionTable in
/-- Static-table membership implies the range-condition part of the legacy
    BinaryExtensionTable semantics. -/
theorem spec_range_conditions {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    range_conditions (BinaryExtensionTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_range_conditions i

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem rowOfIndex_wf_SLL (i : Fin tableSize) :
    wf_SLL (BinaryExtensionTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 9 := blockOfIndex_lt_9 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 9 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_SLL, OP_SRL, OP_SRA, OP_SLL_W,
    OP_SRL_W, OP_SRA_W, OP_SEXT_B, OP_SEXT_H, OP_SEXT_W] at h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_byte : byteIndex i.val < 8 := by
    unfold byteIndex
    exact Nat.mod_lt _ (by norm_num)
  have h_shift : shiftAmount i.val < 256 := by
    unfold shiftAmount
    split
    · exact Nat.mod_lt _ (by norm_num)
    · norm_num
  have h_low_mod : lowByte i.val % 18446744069414584321 = lowByte i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_byte_mod : byteIndex i.val % 18446744069414584321 = byteIndex i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_shift_mod : shiftAmount i.val % 18446744069414584321 = shiftAmount i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_shift_val :
      (if i.val < 6 * shiftBlockSize then ((i.val / sextBlockSize) % 256 : ℕ) else 0 : FGL).val =
        if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0 := by
    split
    · exact Nat.mod_eq_of_lt
        (lt_trans (Nat.mod_lt _ (by norm_num : 0 < 256))
          (by norm_num : 256 < 18446744069414584321))
    · rfl
  simp [outOfIndex, sllOut, shiftAmount, h_block, h_low_mod, h_byte_mod,
    h_shift_val, Nat.shiftLeft_eq]
  constructor
  · exact lt_trans (Nat.mod_lt _ (by norm_num : 0 < 4294967296))
      (by norm_num : 4294967296 < 18446744069414584321)
  · have hmod : lowByte i.val * 256 ^ byteIndex i.val *
          2 ^ ((if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0) % 64) %
          18446744073709551616 < 18446744073709551616 :=
        Nat.mod_lt _ (by norm_num)
    exact Nat.div_lt_of_lt_mul (by omega)

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem spec_wf_SLL {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    wf_SLL (BinaryExtensionTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_SLL i

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem rowOfIndex_wf_SRL (i : Fin tableSize) :
    wf_SRL (BinaryExtensionTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 9 := blockOfIndex_lt_9 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 9 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_SLL, OP_SRL, OP_SRA, OP_SLL_W,
    OP_SRL_W, OP_SRA_W, OP_SEXT_B, OP_SEXT_H, OP_SEXT_W] at h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_byte : byteIndex i.val < 8 := by
    unfold byteIndex
    exact Nat.mod_lt _ (by norm_num)
  have h_shift : shiftAmount i.val < 256 := by
    unfold shiftAmount
    split
    · exact Nat.mod_lt _ (by norm_num)
    · norm_num
  have h_low_mod : lowByte i.val % 18446744069414584321 = lowByte i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_byte_mod : byteIndex i.val % 18446744069414584321 = byteIndex i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_shift_mod : shiftAmount i.val % 18446744069414584321 = shiftAmount i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_shift_val :
      (if i.val < 6 * shiftBlockSize then ((i.val / sextBlockSize) % 256 : ℕ) else 0 : FGL).val =
        if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0 := by
    split
    · exact Nat.mod_eq_of_lt
        (lt_trans (Nat.mod_lt _ (by norm_num : 0 < 256))
          (by norm_num : 256 < 18446744069414584321))
    · rfl
  simp [outOfIndex, srlOut, shiftAmount, h_block, h_low_mod, h_byte_mod,
    h_shift_val, Nat.shiftRight_eq_div_pow]
  have h_pos_lt_p : lowByte i.val * 256 ^ byteIndex i.val < 18446744069414584321 := by
    have h_low_le : lowByte i.val ≤ 255 := by omega
    calc
      lowByte i.val * 256 ^ byteIndex i.val ≤ 255 * 256 ^ byteIndex i.val := by
        exact Nat.mul_le_mul_right _ h_low_le
      _ ≤ 255 * 256 ^ 7 := by
        exact Nat.mul_le_mul_left _ (Nat.pow_le_pow_right (by norm_num) (by omega))
      _ < 18446744069414584321 := by norm_num
  constructor
  · exact lt_trans (Nat.mod_lt _ (by norm_num : 0 < 4294967296))
      (by norm_num : 4294967296 < 18446744069414584321)
  · exact lt_of_le_of_lt
      (le_trans (Nat.div_le_self _ _) (Nat.div_le_self _ _))
      h_pos_lt_p

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem spec_wf_SRL {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    wf_SRL (BinaryExtensionTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_SRL i

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem rowOfIndex_wf_SRA (i : Fin tableSize) :
    wf_SRA (BinaryExtensionTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 9 := blockOfIndex_lt_9 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 9 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_SLL, OP_SRL, OP_SRA, OP_SLL_W,
    OP_SRL_W, OP_SRA_W, OP_SEXT_B, OP_SEXT_H, OP_SEXT_W] at h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_byte : byteIndex i.val < 8 := by
    unfold byteIndex
    exact Nat.mod_lt _ (by norm_num)
  have h_shift : shiftAmount i.val < 256 := by
    unfold shiftAmount
    split
    · exact Nat.mod_lt _ (by norm_num)
    · norm_num
  have h_low_mod : lowByte i.val % 18446744069414584321 = lowByte i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_byte_mod : byteIndex i.val % 18446744069414584321 = byteIndex i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_shift_mod : shiftAmount i.val % 18446744069414584321 = shiftAmount i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_shift_val :
      (if i.val < 6 * shiftBlockSize then ((i.val / sextBlockSize) % 256 : ℕ) else 0 : FGL).val =
        if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0 := by
    split
    · exact Nat.mod_eq_of_lt
        (lt_trans (Nat.mod_lt _ (by norm_num : 0 < 256))
          (by norm_num : 256 < 18446744069414584321))
    · rfl
  simp [outOfIndex, sraOut, shiftAmount, h_block, h_low_mod, h_byte_mod,
    h_shift_val, Nat.shiftRight_eq_div_pow]
  have h_pos_lt_p : lowByte i.val * 256 ^ byteIndex i.val < 18446744069414584321 := by
    have h_low_le : lowByte i.val ≤ 255 := by omega
    calc
      lowByte i.val * 256 ^ byteIndex i.val ≤ 255 * 256 ^ byteIndex i.val := by
        exact Nat.mul_le_mul_right _ h_low_le
      _ ≤ 255 * 256 ^ 7 := by
        exact Nat.mul_le_mul_left _ (Nat.pow_le_pow_right (by norm_num) (by omega))
      _ < 18446744069414584321 := by norm_num
  constructor
  · exact lt_trans (Nat.mod_lt _ (by norm_num : 0 < 4294967296))
      (by norm_num : 4294967296 < 18446744069414584321)
  · apply Nat.div_lt_of_lt_mul
    have h_base_le :
        lowByte i.val * 256 ^ byteIndex i.val /
            2 ^ ((if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0) % 64)
          ≤ lowByte i.val * 256 ^ byteIndex i.val :=
      Nat.div_le_self _ _
    have h_ext_lt :
        (if byteIndex i.val = 7 ∧ 128 ≤ lowByte i.val then
            18446744073709551616 -
              2 ^ (64 - (if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0) % 64)
          else 0) < 18446744073709551616 := by
      split
      · have hpow_pos :
            0 < 2 ^ (64 - (if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0) % 64) :=
          Nat.pow_pos (by norm_num : 0 < 2)
        omega
      · norm_num
    omega

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem spec_wf_SRA {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    wf_SRA (BinaryExtensionTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_SRA i

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem rowOfIndex_wf_SLL_W (i : Fin tableSize) :
    wf_SLL_W (BinaryExtensionTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 9 := blockOfIndex_lt_9 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 9 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_SLL, OP_SRL, OP_SRA, OP_SLL_W,
    OP_SRL_W, OP_SRA_W, OP_SEXT_B, OP_SEXT_H, OP_SEXT_W] at h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_byte : byteIndex i.val < 8 := by
    unfold byteIndex
    exact Nat.mod_lt _ (by norm_num)
  have h_shift : shiftAmount i.val < 256 := by
    unfold shiftAmount
    split
    · exact Nat.mod_lt _ (by norm_num)
    · norm_num
  have h_low_mod : lowByte i.val % 18446744069414584321 = lowByte i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_byte_mod : byteIndex i.val % 18446744069414584321 = byteIndex i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_shift_val :
      (if i.val < 6 * shiftBlockSize then ((i.val / sextBlockSize) % 256 : ℕ) else 0 : FGL).val =
        if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0 := by
    split
    · exact Nat.mod_eq_of_lt
        (lt_trans (Nat.mod_lt _ (by norm_num : 0 < 256))
          (by norm_num : 256 < 18446744069414584321))
    · rfl
  simp [outOfIndex, sllwOut, shiftAmount, h_block, h_low_mod, h_byte_mod,
    h_shift_val, Nat.shiftLeft_eq]
  let inner :=
    if byteIndex i.val < 4 then
      lowByte i.val * 256 ^ byteIndex i.val *
          2 ^ ((if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0) % 32) %
        4294967296
    else 0
  have h_inner_lt : inner < 4294967296 := by
    dsimp [inner]
    split
    · exact Nat.mod_lt _ (by norm_num)
    · norm_num
  constructor
  · simpa [inner] using wmode_signext_lo_val inner h_inner_lt
  · simpa [inner] using wmode_signext_hi_val inner h_inner_lt

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem spec_wf_SLL_W {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    wf_SLL_W (BinaryExtensionTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_SLL_W i

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem rowOfIndex_wf_SRL_W (i : Fin tableSize) :
    wf_SRL_W (BinaryExtensionTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 9 := blockOfIndex_lt_9 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 9 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_SLL, OP_SRL, OP_SRA, OP_SLL_W,
    OP_SRL_W, OP_SRA_W, OP_SEXT_B, OP_SEXT_H, OP_SEXT_W] at h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_byte : byteIndex i.val < 8 := by
    unfold byteIndex
    exact Nat.mod_lt _ (by norm_num)
  have h_shift : shiftAmount i.val < 256 := by
    unfold shiftAmount
    split
    · exact Nat.mod_lt _ (by norm_num)
    · norm_num
  have h_low_mod : lowByte i.val % 18446744069414584321 = lowByte i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_byte_mod : byteIndex i.val % 18446744069414584321 = byteIndex i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_shift_val :
      (if i.val < 6 * shiftBlockSize then ((i.val / sextBlockSize) % 256 : ℕ) else 0 : FGL).val =
        if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0 := by
    split
    · exact Nat.mod_eq_of_lt
        (lt_trans (Nat.mod_lt _ (by norm_num : 0 < 256))
          (by norm_num : 256 < 18446744069414584321))
    · rfl
  simp [outOfIndex, srlwOut, shiftAmount, h_block, h_low_mod, h_byte_mod,
    h_shift_val, Nat.shiftRight_eq_div_pow]
  let inner :=
    if byteIndex i.val < 4 then
      lowByte i.val * 256 ^ byteIndex i.val /
        2 ^ ((if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0) % 32)
    else 0
  have h_inner_lt : inner < 4294967296 := by
    dsimp [inner]
    by_cases h_byte_lt : byteIndex i.val < 4
    · rw [if_pos h_byte_lt]
      have h_low_le : lowByte i.val ≤ 255 := by omega
      have h_pos_lt : lowByte i.val * 256 ^ byteIndex i.val < 4294967296 := by
        calc
          lowByte i.val * 256 ^ byteIndex i.val ≤ 255 * 256 ^ byteIndex i.val := by
            exact Nat.mul_le_mul_right _ h_low_le
          _ ≤ 255 * 256 ^ 3 := by
            exact Nat.mul_le_mul_left _ (Nat.pow_le_pow_right (by norm_num) (by omega))
          _ < 4294967296 := by norm_num
      exact lt_of_le_of_lt (Nat.div_le_self _ _) h_pos_lt
    · rw [if_neg h_byte_lt]
      norm_num
  constructor
  · simpa [inner] using wmode_signext_lo_val inner h_inner_lt
  · simpa [inner] using wmode_signext_hi_val inner h_inner_lt

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem spec_wf_SRL_W {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    wf_SRL_W (BinaryExtensionTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_SRL_W i

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem rowOfIndex_wf_SRA_W (i : Fin tableSize) :
    wf_SRA_W (BinaryExtensionTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 9 := blockOfIndex_lt_9 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 9 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_SLL, OP_SRL, OP_SRA, OP_SLL_W,
    OP_SRL_W, OP_SRA_W, OP_SEXT_B, OP_SEXT_H, OP_SEXT_W] at h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_byte : byteIndex i.val < 8 := by
    unfold byteIndex
    exact Nat.mod_lt _ (by norm_num)
  have h_shift : shiftAmount i.val < 256 := by
    unfold shiftAmount
    split
    · exact Nat.mod_lt _ (by norm_num)
    · norm_num
  have h_low_mod : lowByte i.val % 18446744069414584321 = lowByte i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_byte_mod : byteIndex i.val % 18446744069414584321 = byteIndex i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_shift_val :
      (if i.val < 6 * shiftBlockSize then ((i.val / sextBlockSize) % 256 : ℕ) else 0 : FGL).val =
        if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0 := by
    split
    · exact Nat.mod_eq_of_lt
        (lt_trans (Nat.mod_lt _ (by norm_num : 0 < 256))
          (by norm_num : 256 < 18446744069414584321))
    · rfl
  simp [outOfIndex, srawOut, shiftAmount, h_block, h_low_mod, h_byte_mod,
    h_shift_val, Nat.shiftRight_eq_div_pow]
  have h_pos_lt_p : lowByte i.val * 256 ^ byteIndex i.val < 18446744069414584321 := by
    have h_low_le : lowByte i.val ≤ 255 := by omega
    calc
      lowByte i.val * 256 ^ byteIndex i.val ≤ 255 * 256 ^ byteIndex i.val := by
        exact Nat.mul_le_mul_right _ h_low_le
      _ ≤ 255 * 256 ^ 7 := by
        exact Nat.mul_le_mul_left _ (Nat.pow_le_pow_right (by norm_num) (by omega))
      _ < 18446744069414584321 := by norm_num
  constructor
  · exact lt_trans (Nat.mod_lt _ (by norm_num : 0 < 4294967296))
      (by norm_num : 4294967296 < 18446744069414584321)
  · apply Nat.div_lt_of_lt_mul
    have h_base_le :
        (if byteIndex i.val < 4 then
            lowByte i.val * 256 ^ byteIndex i.val /
              2 ^ ((if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0) % 32)
          else 0) ≤ lowByte i.val * 256 ^ byteIndex i.val := by
      split
      · exact Nat.div_le_self _ _
      · omega
    have h_ext_lt :
        (if byteIndex i.val = 3 ∧ 128 ≤ lowByte i.val then
            18446744073709551616 -
              2 ^ (32 - (if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0) % 32)
          else 0) < 18446744073709551616 := by
      split
      · have hpow_pos :
            0 < 2 ^ (32 - (if i.val < 6 * shiftBlockSize then i.val / sextBlockSize % 256 else 0) % 32) :=
          Nat.pow_pos (by norm_num : 0 < 2)
        omega
      · norm_num
    omega

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem spec_wf_SRA_W {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    wf_SRA_W (BinaryExtensionTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_SRA_W i

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem rowOfIndex_wf_SEXT_B (i : Fin tableSize) :
    wf_SEXT_B (BinaryExtensionTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 9 := blockOfIndex_lt_9 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 9 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_SLL, OP_SRL, OP_SRA, OP_SLL_W,
    OP_SRL_W, OP_SRA_W, OP_SEXT_B, OP_SEXT_H, OP_SEXT_W] at h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_byte : byteIndex i.val < 8 := by
    unfold byteIndex
    exact Nat.mod_lt _ (by norm_num)
  have h_low_mod : lowByte i.val % 18446744069414584321 = lowByte i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_byte_mod : byteIndex i.val % 18446744069414584321 = byteIndex i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  simp [outOfIndex, sextbOut, h_block, h_low_mod, h_byte_mod]
  by_cases h_byte_zero : byteIndex i.val = 0
  · by_cases h_sign : 128 ≤ lowByte i.val
    · simp [h_byte_zero, h_sign]
      omega
    · simp [h_byte_zero, h_sign]
      omega
  · simp [h_byte_zero]

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem spec_wf_SEXT_B {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    wf_SEXT_B (BinaryExtensionTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_SEXT_B i

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem rowOfIndex_wf_SEXT_H (i : Fin tableSize) :
    wf_SEXT_H (BinaryExtensionTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 9 := blockOfIndex_lt_9 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 9 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_SLL, OP_SRL, OP_SRA, OP_SLL_W,
    OP_SRL_W, OP_SRA_W, OP_SEXT_B, OP_SEXT_H, OP_SEXT_W] at h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_byte : byteIndex i.val < 8 := by
    unfold byteIndex
    exact Nat.mod_lt _ (by norm_num)
  have h_low_mod : lowByte i.val % 18446744069414584321 = lowByte i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_byte_mod : byteIndex i.val % 18446744069414584321 = byteIndex i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  simp [outOfIndex, sexthOut, h_block, h_low_mod, h_byte_mod]
  by_cases h_byte_zero : byteIndex i.val = 0
  · simp [h_byte_zero]
    omega
  · by_cases h_byte_one : byteIndex i.val = 1
    · by_cases h_sign : 128 ≤ lowByte i.val
      · simp [h_byte_one, h_sign]
        omega
      · simp [h_byte_one, h_sign]
        omega
    · simp [h_byte_zero, h_byte_one]

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem spec_wf_SEXT_H {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    wf_SEXT_H (BinaryExtensionTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_SEXT_H i

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem rowOfIndex_wf_SEXT_W (i : Fin tableSize) :
    wf_SEXT_W (BinaryExtensionTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 9 := blockOfIndex_lt_9 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 9 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_SLL, OP_SRL, OP_SRA, OP_SLL_W,
    OP_SRL_W, OP_SRA_W, OP_SEXT_B, OP_SEXT_H, OP_SEXT_W] at h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_byte : byteIndex i.val < 8 := by
    unfold byteIndex
    exact Nat.mod_lt _ (by norm_num)
  have h_low_mod : lowByte i.val % 18446744069414584321 = lowByte i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  have h_byte_mod : byteIndex i.val % 18446744069414584321 = byteIndex i.val := by
    exact Nat.mod_eq_of_lt (by omega)
  simp [outOfIndex, sextwOut, h_block, h_low_mod, h_byte_mod]
  by_cases h_byte_lt : byteIndex i.val < 4
  · by_cases h_byte_three : byteIndex i.val = 3
    · by_cases h_sign : 128 ≤ lowByte i.val
      · simp [h_byte_three, h_sign]
        omega
      · simp [h_byte_three, h_sign]
        omega
    · interval_cases byteIndex i.val <;> simp at h_byte_three ⊢ <;> omega
  · simp [h_byte_lt]

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem spec_wf_SEXT_W {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    wf_SEXT_W (BinaryExtensionTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_SEXT_W i

open ZiskFv.Airs.Tables.BinaryExtensionTable in
theorem spec_wf_properties {t : BinaryExtensionTableMessage FGL}
    (h : binaryExtensionTable.Spec t) :
    wf_properties (BinaryExtensionTableMessage.toEntry t 1) := by
  exact ⟨ spec_range_conditions h
        , spec_wf_SLL h
        , spec_wf_SRL h
        , spec_wf_SRA h
        , spec_wf_SLL_W h
        , spec_wf_SRL_W h
        , spec_wf_SRA_W h
        , spec_wf_SEXT_B h
        , spec_wf_SEXT_H h
        , spec_wf_SEXT_W h ⟩

end ZiskFv.AirsClean.BinaryExtensionTable
