import Clean.Circuit.Lookup
import ZiskFv.Channels.BinaryExtensionTable

/-!
# BinaryExtensionTable — Clean `StaticTable` provider side

ZisK's BinaryExtension virtual table has
`6 * 2^19 + 3 * 2^11` meaningful rows. The PIL table is generated by a
deterministic arithmetic indexer over `(op, byte_index, a_byte,
shift_amount)`; see
`zisk/state-machines/binary/pil/binary_extension_table.pil`.

This module gives the provider side as a non-enumerated Clean
`StaticTable`: `row i` decodes the same arithmetic row, and `Spec` is exact
membership in that decoded row set. This is the faithful large-ROM pattern
validated by `AirsClean/ZRomSpike.lean`; there is no `decide` over millions
of literal rows.

It intentionally does not retire `bin_ext_table_consumer_wf` by itself.
Load-bearing retirement still needs the consumer lookup path and this
provider table to be connected in the terminal Binary-family ensemble.

## Trust note

No axioms. The membership predicate is exact decoded-row membership, and
`contains_iff` is definitional.
-/

namespace ZiskFv.AirsClean.BinaryExtensionTable

open Goldilocks
open ZiskFv.Channels.BinaryExtensionTable

def shiftBlockSize : ℕ := 2 ^ 19
def sextBlockSize : ℕ := 2 ^ 11
def tableSize : ℕ := 6 * shiftBlockSize + 3 * sextBlockSize

def opOfBlock (block : ℕ) : ℕ :=
  if block = 0 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SLL
  else if block = 1 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SRL
  else if block = 2 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SRA
  else if block = 3 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SLL_W
  else if block = 4 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SRL_W
  else if block = 5 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SRA_W
  else if block = 6 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SEXT_B
  else if block = 7 then ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SEXT_H
  else ZiskFv.Airs.Tables.BinaryExtensionTable.OP_SEXT_W

@[reducible]
def lowByte (i : ℕ) : ℕ := i % 256

@[reducible]
def byteIndex (i : ℕ) : ℕ := (i / 256) % 8

@[reducible]
def shiftAmount (i : ℕ) : ℕ :=
  if i < 6 * shiftBlockSize then (i / sextBlockSize) % 256 else 0

@[reducible]
def blockOfIndex (i : ℕ) : ℕ :=
  if i < 6 * shiftBlockSize then i / shiftBlockSize
  else 6 + (i - 6 * shiftBlockSize) / sextBlockSize

@[reducible]
def opOfIndex (i : ℕ) : ℕ := opOfBlock (blockOfIndex i)

@[reducible]
def sllOut (a offset b : ℕ) : ℕ :=
  (a * 256 ^ offset * 2 ^ (b % 64)) % 2 ^ 64

@[reducible]
def srlOut (a offset b : ℕ) : ℕ :=
  (a * 256 ^ offset) / 2 ^ (b % 64)

@[reducible]
def sraOut (a offset b : ℕ) : ℕ :=
  let s := b % 64
  let base := (a * 256 ^ offset) / 2 ^ s
  let ext := if offset = 7 ∧ a ≥ 128 then 2 ^ 64 - 2 ^ (64 - s) else 0
  base + ext

@[reducible]
def sllwOut (a offset b : ℕ) : ℕ :=
  let s := b % 32
  let positioned := a * 256 ^ offset
  let inner := if offset < 4 then (positioned * 2 ^ s) % 2 ^ 32 else 0
  inner + if inner ≥ 2 ^ 31 then 2 ^ 64 - 2 ^ 32 else 0

@[reducible]
def srlwOut (a offset b : ℕ) : ℕ :=
  let s := b % 32
  let positioned := a * 256 ^ offset
  let inner := if offset < 4 then positioned / 2 ^ s else 0
  inner + if inner ≥ 2 ^ 31 then 2 ^ 64 - 2 ^ 32 else 0

@[reducible]
def srawOut (a offset b : ℕ) : ℕ :=
  let s := b % 32
  let positioned := a * 256 ^ offset
  let base := if offset < 4 then positioned / 2 ^ s else 0
  let ext := if offset = 3 ∧ a ≥ 128 then 2 ^ 64 - 2 ^ (32 - s) else 0
  base + ext

@[reducible]
def sextbOut (a offset : ℕ) : ℕ :=
  if offset = 0 then
    if a ≥ 128 then a + (2 ^ 64 - 256) else a
  else 0

@[reducible]
def sexthOut (a offset : ℕ) : ℕ :=
  if offset = 0 then a
  else if offset = 1 then
    let aPos := a * 256
    if a ≥ 128 then aPos + (2 ^ 64 - 2 ^ 16) else aPos
  else 0

@[reducible]
def sextwOut (a offset : ℕ) : ℕ :=
  if offset < 4 then
    let aPos := a * 256 ^ offset
    if offset = 3 ∧ a ≥ 128 then aPos + (2 ^ 64 - 2 ^ 32) else aPos
  else 0

@[reducible]
def outOfIndex (i : ℕ) : ℕ :=
  let a := lowByte i
  let offset := byteIndex i
  let b := shiftAmount i
  match blockOfIndex i with
  | 0 => sllOut a offset b
  | 1 => srlOut a offset b
  | 2 => sraOut a offset b
  | 3 => sllwOut a offset b
  | 4 => srlwOut a offset b
  | 5 => srawOut a offset b
  | 6 => sextbOut a offset
  | 7 => sexthOut a offset
  | _ => sextwOut a offset

@[reducible]
def opIsShiftOfIndex (i : ℕ) : ℕ :=
  if blockOfIndex i < 6 then 1 else 0

/-- Decoded row `i` of the BinaryExtensionTable, as a Clean channel
    payload. -/
@[reducible]
def rowOfIndex (i : ℕ) : BinaryExtensionTableMessage FGL :=
  let out := outOfIndex i
  { op := opOfIndex i
    byte_index := byteIndex i
    a_byte := lowByte i
    shift_amount := shiftAmount i
    c_lo_byte := out % 2 ^ 32
    c_hi_byte := out / 2 ^ 32
    op_is_shift := opIsShiftOfIndex i }

/-- Exact decoded-row membership for the BinaryExtensionTable provider. -/
def binaryExtensionTable : StaticTable FGL BinaryExtensionTableMessage where
  name := "binary_extension_table"
  length := tableSize
  row i := rowOfIndex i.val
  index t := t.op.val
  Spec t := ∃ i : Fin tableSize, t = rowOfIndex i.val
  contains_iff := by intro t; rfl

theorem spec_iff (t : BinaryExtensionTableMessage FGL) :
    binaryExtensionTable.Spec t ↔ ∃ i : Fin tableSize, t = rowOfIndex i.val :=
  Iff.rfl

end ZiskFv.AirsClean.BinaryExtensionTable
