import Clean.Circuit.Lookup
import ZiskFv.Channels.BinaryTable

/-!
# BinaryTable — Clean `StaticTable` provider side

ZisK's Binary virtual table has `2^22 + 2^20 + 2^18` meaningful rows.
The PIL table is generated by deterministic fixed columns plus a switch over
the operation code; see
`zisk/state-machines/binary/pil/binary_table.pil`.

This module gives the provider side as a non-enumerated Clean
`StaticTable`: `row i` decodes the same arithmetic row, and `Spec` is exact
membership in that decoded row set. This follows the large-ROM pattern in
the other static-table providers; there is no literal enumeration of the
5.5M-row table.

It intentionally does not retire `bin_table_consumer_wf` by itself.
Load-bearing retirement still needs the Binary consumer lookup path and this
provider table to be connected in the terminal Binary-family ensemble.

## Trust note

No axioms. The membership predicate is exact decoded-row membership, and
`contains_iff` is definitional.
-/

namespace ZiskFv.AirsClean.BinaryTable

open Goldilocks
open ZiskFv.Channels.BinaryTable
open ZiskFv.Airs.Tables.BinaryTable

def tableSize : ℕ := 2 ^ 22 + 2 ^ 20 + 2 ^ 18

def OP_MINU : ℕ := 0x02
def OP_MIN : ℕ := 0x03
def OP_MAXU : ℕ := 0x04
def OP_MAX : ℕ := 0x05
def OP_LT_ABS_NP : ℕ := 0x50
def OP_LT_ABS_PN : ℕ := 0x51

@[reducible] def p2_16 : ℕ := 2 ^ 16
@[reducible] def p2_17 : ℕ := 2 ^ 17
@[reducible] def p2_18 : ℕ := 2 ^ 18
@[reducible] def p2_19 : ℕ := 2 ^ 19

@[reducible] def minMaxBlockSize : ℕ := p2_18 + p2_17
@[reducible] def absBlockSize : ℕ := p2_19
@[reducible] def fullBlockSize : ℕ := p2_18
@[reducible] def bitwiseBlockSize : ℕ := p2_17
@[reducible] def sextBlockSize : ℕ := p2_17 + p2_16

@[reducible] def block0 : ℕ := 0
@[reducible] def block1 : ℕ := block0 + minMaxBlockSize
@[reducible] def block2 : ℕ := block1 + minMaxBlockSize
@[reducible] def block3 : ℕ := block2 + minMaxBlockSize
@[reducible] def block4 : ℕ := block3 + minMaxBlockSize
@[reducible] def block5 : ℕ := block4 + absBlockSize
@[reducible] def block6 : ℕ := block5 + absBlockSize
@[reducible] def block7 : ℕ := block6 + fullBlockSize
@[reducible] def block8 : ℕ := block7 + fullBlockSize
@[reducible] def block9 : ℕ := block8 + fullBlockSize
@[reducible] def block10 : ℕ := block9 + fullBlockSize
@[reducible] def block11 : ℕ := block10 + fullBlockSize
@[reducible] def block12 : ℕ := block11 + fullBlockSize
@[reducible] def block13 : ℕ := block12 + fullBlockSize
@[reducible] def block14 : ℕ := block13 + fullBlockSize
@[reducible] def block15 : ℕ := block14 + bitwiseBlockSize
@[reducible] def block16 : ℕ := block15 + bitwiseBlockSize
@[reducible] def block17 : ℕ := block16 + bitwiseBlockSize
@[reducible] def block18 : ℕ := block17 + sextBlockSize

@[reducible]
def lowByte (i : ℕ) : ℕ := i % 256

@[reducible]
def highByte (i : ℕ) : ℕ := (i / 256) % 256

@[reducible]
def blockOfIndex (i : ℕ) : ℕ :=
  if i < block1 then 0
  else if i < block2 then 1
  else if i < block3 then 2
  else if i < block4 then 3
  else if i < block5 then 4
  else if i < block6 then 5
  else if i < block7 then 6
  else if i < block8 then 7
  else if i < block9 then 8
  else if i < block10 then 9
  else if i < block11 then 10
  else if i < block12 then 11
  else if i < block13 then 12
  else if i < block14 then 13
  else if i < block15 then 14
  else if i < block16 then 15
  else if i < block17 then 16
  else if i < block18 then 17
  else 18

@[reducible]
def startOfBlock (block : ℕ) : ℕ :=
  match block with
  | 0 => block0
  | 1 => block1
  | 2 => block2
  | 3 => block3
  | 4 => block4
  | 5 => block5
  | 6 => block6
  | 7 => block7
  | 8 => block8
  | 9 => block9
  | 10 => block10
  | 11 => block11
  | 12 => block12
  | 13 => block13
  | 14 => block14
  | 15 => block15
  | 16 => block16
  | 17 => block17
  | _ => block18

@[reducible]
def relativeIndex (i : ℕ) : ℕ :=
  i - startOfBlock (blockOfIndex i)

@[reducible]
def opOfBlock (block : ℕ) : ℕ :=
  match block with
  | 0 => OP_MINU
  | 1 => OP_MIN
  | 2 => OP_MAXU
  | 3 => OP_MAX
  | 4 => OP_LT_ABS_NP
  | 5 => OP_LT_ABS_PN
  | 6 => OP_LTU
  | 7 => OP_LT
  | 8 => OP_GT
  | 9 => OP_EQ
  | 10 => OP_ADD
  | 11 => OP_SUB
  | 12 => OP_LEU
  | 13 => OP_LE
  | 14 => OP_AND
  | 15 => OP_OR
  | 16 => OP_XOR
  | 17 => OP_SEXT_00
  | _ => OP_SEXT_FF

@[reducible]
def opOfIndex (i : ℕ) : ℕ := opOfBlock (blockOfIndex i)

@[reducible]
def posIndOfIndex (i : ℕ) : ℕ :=
  let block := blockOfIndex i
  let rel := relativeIndex i
  if block < 4 then
    if rel < p2_18 then 0 else 1
  else if block < 6 then
    let slot := (rel / p2_16) % 4
    if slot = 0 then 0 else if slot = 1 then 1 else 2
  else if block < 14 then
    if (rel / p2_16) % 2 = 0 then 0 else 1
  else if block < 17 then
    if rel < p2_16 then 0 else 1
  else
    0

@[reducible]
def cinOfIndex (i : ℕ) : ℕ :=
  let block := blockOfIndex i
  let rel := relativeIndex i
  if block < 4 then
    (rel / p2_16) % 2
  else if block < 6 then
    if rel < p2_18 then 0 else 1
  else if block < 14 then
    if rel < p2_17 then 0 else 1
  else if block < 17 then
    0
  else
    if (rel / p2_16) % 3 = 1 then 1 else 0

@[reducible]
def coutLt (a b cin : ℕ) : ℕ :=
  if a < b then 1 else if a = b then cin else 0

theorem coutLt_lt_two {a b cin : ℕ} (hcin : cin < 2) : coutLt a b cin < 2 := by
  unfold coutLt
  split <;> try omega
  split <;> omega

@[reducible]
def coutGt (a b cin : ℕ) : ℕ :=
  if a > b then 1 else if a = b then cin else 0

theorem coutGt_lt_two {a b cin : ℕ} (hcin : cin < 2) : coutGt a b cin < 2 := by
  unfold coutGt
  split <;> try omega
  split <;> omega

@[reducible]
def signByte (a : ℕ) : ℕ := if (a &&& 0x80) = 0 then 0 else 1

theorem signByte_lt_two (a : ℕ) : signByte a < 2 := by
  unfold signByte
  split <;> omega

@[reducible]
def chooseByte (pickA a b : ℕ) : ℕ := if pickA = 0 then b else a

theorem chooseByte_lt_256 {pickA a b : ℕ} (ha : a < 256) (hb : b < 256) :
    chooseByte pickA a b < 256 := by
  unfold chooseByte
  split <;> assumption

theorem add_mod_highByte (cin a i : ℕ) :
    (cin + a + i / 256) % 256 = (cin + a + highByte i) % 256 := by
  unfold highByte
  omega

theorem even_add_cIsSigned_mod_two (x y : ℕ) :
    (x + 8 * y) % 2 = x % 2 := by
  omega

@[reducible]
def cOfIndex (i : ℕ) : ℕ :=
  let block := blockOfIndex i
  let rel := relativeIndex i
  let a := lowByte i
  let b := highByte i
  let cin := cinOfIndex i
  let pos := posIndOfIndex i
  let plast := pos = 1
  match block with
  | 0 =>
      let cout := coutLt a b cin
      let pickA := if plast then cout else if rel ≥ p2_17 then 1 else 0
      chooseByte pickA a b
  | 1 =>
      let cout := coutLt a b cin
      let pickA :=
        if plast then
          if (a &&& 0x80) ≠ (b &&& 0x80) then signByte a else cout
        else if rel ≥ p2_17 then 1 else 0
      chooseByte pickA a b
  | 2 =>
      let cout := coutGt a b cin
      let pickA := if plast then cout else if rel ≥ p2_17 then 1 else 0
      chooseByte pickA a b
  | 3 =>
      let cout := coutGt a b cin
      let pickA :=
        if plast then
          if (a &&& 0x80) ≠ (b &&& 0x80) then signByte b else cout
        else if rel ≥ p2_17 then 1 else 0
      chooseByte pickA a b
  | 10 => (cin + a + b) % 256
  | 11 => if a ≥ cin + b then a - cin - b else 256 + a - cin - b
  | 14 => a &&& b
  | 15 => a ||| b
  | 16 => a ^^^ b
  | 17 => 0x00
  | 18 => 0xFF
  | _ => 0

@[reducible]
def coutOfIndex (i : ℕ) : ℕ :=
  let block := blockOfIndex i
  let a := lowByte i
  let b := highByte i
  let cin := cinOfIndex i
  let pos := posIndOfIndex i
  let pfirst := pos = 2
  let plast := pos = 1
  match block with
  | 0 =>
      if plast then 0 else coutLt a b cin
  | 1 =>
      if plast then 0 else coutLt a b cin
  | 2 =>
      if plast then 0 else coutGt a b cin
  | 3 =>
      if plast then 0 else coutGt a b cin
  | 4 =>
      let aAbsByte := a ^^^ 0xFF
      if pfirst then coutLt (aAbsByte + 1) b cin else coutLt aAbsByte b cin
  | 5 =>
      let bAbsByte := b ^^^ 0xFF
      if pfirst then coutLt a (bAbsByte + 1) cin else coutLt a bAbsByte cin
  | 6 => coutLt a b cin
  | 7 =>
      let cout := coutLt a b cin
      if plast ∧ (a &&& 0x80) ≠ (b &&& 0x80) then signByte a else cout
  | 8 =>
      let cout := coutGt a b cin
      if plast ∧ (a &&& 0x80) ≠ (b &&& 0x80) then signByte b else cout
  | 9 =>
      let cout := if cin = 0 ∧ a = b then 0 else 1
      if plast then 1 - cout else cout
  | 10 =>
      if plast then 0 else (cin + a + b) / 256
  | 11 =>
      if plast then 0 else if a < cin + b then 1 else 0
  | 12 =>
      let cout := if a < b then 0 else if a = b then cin else 1
      if plast then 1 - cout else cout
  | 13 =>
      let cout := if a < b then 0 else if a = b then cin else 1
      if plast then
        if (a &&& 0x80) ≠ (b &&& 0x80) then signByte a else 1 - cout
      else
        cout
  | 17 => cin
  | 18 => cin
  | _ => 0

@[reducible]
def resultIsAOfIndex (i : ℕ) : ℕ :=
  let block := blockOfIndex i
  let rel := relativeIndex i
  let a := lowByte i
  let b := highByte i
  let cin := cinOfIndex i
  let pos := posIndOfIndex i
  let plast := pos = 1
  match block with
  | 0 => if plast then coutLt a b cin else if rel ≥ p2_17 then 1 else 0
  | 1 =>
      if plast then
        if (a &&& 0x80) ≠ (b &&& 0x80) then signByte a else coutLt a b cin
      else if rel ≥ p2_17 then 1 else 0
  | 2 => if plast then coutGt a b cin else if rel ≥ p2_17 then 1 else 0
  | 3 =>
      if plast then
        if (a &&& 0x80) ≠ (b &&& 0x80) then signByte b else coutGt a b cin
      else if rel ≥ p2_17 then 1 else 0
  | 17 => if rel ≥ p2_17 then 1 else 0
  | 18 => if rel ≥ p2_17 then 1 else 0
  | _ => 0

@[reducible]
def useFirstByteOfIndex (i : ℕ) : ℕ :=
  let block := blockOfIndex i
  if block = 4 ∨ block = 5 then 1 else 0

@[reducible]
def cIsSignedOfIndex (i : ℕ) : ℕ :=
  let block := blockOfIndex i
  let pos := posIndOfIndex i
  match block with
  | 0 => if pos = 1 then signByte (cOfIndex i) else 0
  | 1 => if pos = 1 then signByte (cOfIndex i) else 0
  | 2 => if pos = 1 then signByte (cOfIndex i) else 0
  | 3 => if pos = 1 then signByte (cOfIndex i) else 0
  | 10 => if pos = 1 then signByte (cOfIndex i) else 0
  | 11 => if pos = 1 then signByte (cOfIndex i) else 0
  | 18 => 1
  | _ => 0

@[reducible]
def flagsOfIndex (i : ℕ) : ℕ :=
  coutOfIndex i
    + 2 * resultIsAOfIndex i
    + 4 * useFirstByteOfIndex i
    + 8 * cIsSignedOfIndex i

/-- Decoded row `i` of the BinaryTable, as a Clean channel payload. -/
@[reducible]
def rowOfIndex (i : ℕ) : BinaryTableMessage FGL :=
  { pos_ind := posIndOfIndex i
    op := opOfIndex i
    a_byte := lowByte i
    b_byte := highByte i
    cin := cinOfIndex i
    c_byte := cOfIndex i
    flags := flagsOfIndex i }

/-- Exact decoded-row membership for the BinaryTable provider. -/
def binaryTable : StaticTable FGL BinaryTableMessage where
  name := "binary_table"
  length := tableSize
  row i := rowOfIndex i.val
  index t := t.op.val
  Spec t := ∃ i : Fin tableSize, t = rowOfIndex i.val
  contains_iff := by intro t; rfl

theorem spec_iff (t : BinaryTableMessage FGL) :
    binaryTable.Spec t ↔ ∃ i : Fin tableSize, t = rowOfIndex i.val :=
  Iff.rfl

theorem blockOfIndex_lt_19 (i : Fin tableSize) : blockOfIndex i.val < 19 := by
  unfold blockOfIndex
  by_cases h1 : i.val < block1
  · rw [if_pos h1]; norm_num
  · rw [if_neg h1]
    by_cases h2 : i.val < block2
    · rw [if_pos h2]; norm_num
    · rw [if_neg h2]
      by_cases h3 : i.val < block3
      · rw [if_pos h3]; norm_num
      · rw [if_neg h3]
        by_cases h4 : i.val < block4
        · rw [if_pos h4]; norm_num
        · rw [if_neg h4]
          by_cases h5 : i.val < block5
          · rw [if_pos h5]; norm_num
          · rw [if_neg h5]
            by_cases h6 : i.val < block6
            · rw [if_pos h6]; norm_num
            · rw [if_neg h6]
              by_cases h7 : i.val < block7
              · rw [if_pos h7]; norm_num
              · rw [if_neg h7]
                by_cases h8 : i.val < block8
                · rw [if_pos h8]; norm_num
                · rw [if_neg h8]
                  by_cases h9 : i.val < block9
                  · rw [if_pos h9]; norm_num
                  · rw [if_neg h9]
                    by_cases h10 : i.val < block10
                    · rw [if_pos h10]; norm_num
                    · rw [if_neg h10]
                      by_cases h11 : i.val < block11
                      · rw [if_pos h11]; norm_num
                      · rw [if_neg h11]
                        by_cases h12 : i.val < block12
                        · rw [if_pos h12]; norm_num
                        · rw [if_neg h12]
                          by_cases h13 : i.val < block13
                          · rw [if_pos h13]; norm_num
                          · rw [if_neg h13]
                            by_cases h14 : i.val < block14
                            · rw [if_pos h14]; norm_num
                            · rw [if_neg h14]
                              by_cases h15 : i.val < block15
                              · rw [if_pos h15]; norm_num
                              · rw [if_neg h15]
                                by_cases h16 : i.val < block16
                                · rw [if_pos h16]; norm_num
                                · rw [if_neg h16]
                                  by_cases h17 : i.val < block17
                                  · rw [if_pos h17]; norm_num
                                  · rw [if_neg h17]
                                    by_cases h18 : i.val < block18
                                    · rw [if_pos h18]; norm_num
                                    · rw [if_neg h18]; norm_num

theorem rowOfIndex_c_byte_lt_256 (i : Fin tableSize) :
    (BinaryTableMessage.toEntry (rowOfIndex i.val) 1).c_byte.val < 256 := by
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_high : highByte i.val < 256 := by
    unfold highByte
    exact Nat.mod_lt _ (by norm_num)
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only
  change (cOfIndex i.val : FGL).val < 256
  rw [Fin.val_natCast]
  suffices h_c : cOfIndex i.val < 256 by
    have hp : cOfIndex i.val < 18446744069414584321 := by omega
    rw [Nat.mod_eq_of_lt hp]
    exact h_c
  unfold cOfIndex
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block
  · simp
    exact chooseByte_lt_256 h_low h_high
  · simp
    exact chooseByte_lt_256 h_low h_high
  · simp
    exact chooseByte_lt_256 h_low h_high
  · simp
    exact chooseByte_lt_256 h_low h_high
  · simp
  · simp
  · simp
  · simp
  · simp
  · simp
  · simp
    exact Nat.mod_lt _ (by norm_num)
  · simp
    split <;> omega
  · simp
  · simp
  · simp
    exact lt_of_le_of_lt Nat.and_le_left h_low
  · simp
    have h_or : lowByte i.val ||| highByte i.val < 2 ^ 8 :=
      Nat.bitwise_lt_two_pow (by simpa using h_low) (by simpa using h_high)
    simpa using h_or
  · simp
    have h_xor : lowByte i.val ^^^ highByte i.val < 2 ^ 8 :=
      Nat.xor_lt_two_pow (by simpa using h_low) (by simpa using h_high)
    simpa using h_xor
  · simp
  · simp

open ZiskFv.Airs.Tables.BinaryTable in
/-- The BinaryTable decoder always emits 8-bit `a` and `b` inputs and a
    one-bit carry input. The `c_byte` range is op-dependent and is proved by
    separate block projections. -/
theorem rowOfIndex_input_range_conditions (i : Fin tableSize) :
    (BinaryTableMessage.toEntry (rowOfIndex i.val) 1).a_byte.val < 256 ∧
    (BinaryTableMessage.toEntry (rowOfIndex i.val) 1).b_byte.val < 256 ∧
    (BinaryTableMessage.toEntry (rowOfIndex i.val) 1).cin.val < 2 := by
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_high : highByte i.val < 256 := by
    unfold highByte
    exact Nat.mod_lt _ (by norm_num)
  have h_cin : cinOfIndex i.val < 2 := by
    simp [cinOfIndex]
    split <;> try exact Nat.mod_lt _ (by norm_num)
    split <;> try omega
    split <;> try omega
    split <;> try omega
    split <;> try omega
    split <;> try omega
    split <;> omega
  simp only
  constructor
  · rw [Fin.val_natCast]
    omega
  constructor
  · rw [Fin.val_natCast]
    omega
  · rw [Fin.val_natCast]
    omega

open ZiskFv.Airs.Tables.BinaryTable in
/-- Static BinaryTable membership gives the input-byte/carry range part of
    the legacy `range_conditions` predicate. -/
theorem spec_input_range_conditions {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    (BinaryTableMessage.toEntry t 1).a_byte.val < 256 ∧
    (BinaryTableMessage.toEntry t 1).b_byte.val < 256 ∧
    (BinaryTableMessage.toEntry t 1).cin.val < 2 := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_input_range_conditions i

open ZiskFv.Airs.Tables.BinaryTable in
/-- Static BinaryTable membership gives the full legacy byte/carry range
    predicate. This is the provider-side replacement for the range component
    of `bin_table_consumer_wf`; the per-op semantic clauses are discharged
    separately. -/
theorem rowOfIndex_range_conditions (i : Fin tableSize) :
    range_conditions (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  rcases rowOfIndex_input_range_conditions i with ⟨ha, hb, hcin⟩
  exact ⟨ha, hb, rowOfIndex_c_byte_lt_256 i, hcin⟩

open ZiskFv.Airs.Tables.BinaryTable in
/-- Exact static-table membership implies the legacy BinaryTable range
    predicate. -/
theorem spec_range_conditions {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    range_conditions (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_range_conditions i

theorem rowOfIndex_op_val_ne_zero (i : Fin tableSize) :
    (rowOfIndex i.val).op.val ≠ 0 := by
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  unfold rowOfIndex opOfIndex
  rw [Fin.val_natCast]
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR,
    OP_LTU, OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE,
    OP_SEXT_00, OP_SEXT_FF, OP_MINU, OP_MIN, OP_MAXU, OP_MAX,
    OP_LT_ABS_NP, OP_LT_ABS_PN]

theorem spec_op_val_ne_zero {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) : t.op.val ≠ 0 := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_op_val_ne_zero i

theorem rowOfIndex_op_val_lt_514 (i : Fin tableSize) :
    (rowOfIndex i.val).op.val < 514 := by
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  unfold rowOfIndex opOfIndex
  rw [Fin.val_natCast]
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR,
    OP_LTU, OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE,
    OP_SEXT_00, OP_SEXT_FF, OP_MINU, OP_MIN, OP_MAXU, OP_MAX,
    OP_LT_ABS_NP, OP_LT_ABS_PN]

theorem spec_op_val_lt_514 {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) : t.op.val < 514 := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_op_val_lt_514 i

/-- No static BinaryTable row carries op_val = 0x1A or 0x1B (those are
    W-mode bus opcodes ADDW/SUBW, not byte-table opcodes). Used by the
    W-mode dispatch to exclude the alternate (mode32 = 0, b_op = op_emit)
    decomposition of the op-bus emission. -/
theorem rowOfIndex_op_val_ne_W_add_sub (i : Fin tableSize) :
    (rowOfIndex i.val).op.val ≠ 0x1A ∧ (rowOfIndex i.val).op.val ≠ 0x1B := by
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  unfold rowOfIndex opOfIndex
  rw [Fin.val_natCast]
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  refine ⟨?_, ?_⟩ <;>
    interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR,
      OP_LTU, OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE,
      OP_SEXT_00, OP_SEXT_FF, OP_MINU, OP_MIN, OP_MAXU, OP_MAX,
      OP_LT_ABS_NP, OP_LT_ABS_PN]

theorem spec_op_val_ne_W_add_sub {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) : t.op.val ≠ 0x1A ∧ t.op.val ≠ 0x1B := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_op_val_ne_W_add_sub i

/-- No static BinaryTable row carries op values 17..22. Combined with
    `mode32 = 1`, those would emit BinaryExtension shift bus opcodes 33..38. -/
theorem rowOfIndex_op_val_ne_shift_offset_ops (i : Fin tableSize) :
    (rowOfIndex i.val).op.val ≠ 17
      ∧ (rowOfIndex i.val).op.val ≠ 18
      ∧ (rowOfIndex i.val).op.val ≠ 19
      ∧ (rowOfIndex i.val).op.val ≠ 20
      ∧ (rowOfIndex i.val).op.val ≠ 21
      ∧ (rowOfIndex i.val).op.val ≠ 22 := by
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  unfold rowOfIndex opOfIndex
  rw [Fin.val_natCast]
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩ <;>
    interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR,
      OP_LTU, OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE,
      OP_SEXT_00, OP_SEXT_FF, OP_MINU, OP_MIN, OP_MAXU, OP_MAX,
      OP_LT_ABS_NP, OP_LT_ABS_PN]

theorem spec_op_val_ne_shift_offset_ops {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    t.op.val ≠ 17
      ∧ t.op.val ≠ 18
      ∧ t.op.val ≠ 19
      ∧ t.op.val ≠ 20
      ∧ t.op.val ≠ 21
      ∧ t.op.val ≠ 22 := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_op_val_ne_shift_offset_ops i

/-- No static BinaryTable row carries BinaryExtension shift bus opcodes 33..38. -/
theorem rowOfIndex_op_val_ne_shift_ops (i : Fin tableSize) :
    (rowOfIndex i.val).op.val ≠ 33
      ∧ (rowOfIndex i.val).op.val ≠ 34
      ∧ (rowOfIndex i.val).op.val ≠ 35
      ∧ (rowOfIndex i.val).op.val ≠ 36
      ∧ (rowOfIndex i.val).op.val ≠ 37
      ∧ (rowOfIndex i.val).op.val ≠ 38 := by
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  unfold rowOfIndex opOfIndex
  rw [Fin.val_natCast]
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩ <;>
    interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR,
      OP_LTU, OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE,
      OP_SEXT_00, OP_SEXT_FF, OP_MINU, OP_MIN, OP_MAXU, OP_MAX,
      OP_LT_ABS_NP, OP_LT_ABS_PN]

theorem spec_op_val_ne_shift_ops {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    t.op.val ≠ 33
      ∧ t.op.val ≠ 34
      ∧ t.op.val ≠ 35
      ∧ t.op.val ≠ 36
      ∧ t.op.val ≠ 37
      ∧ t.op.val ≠ 38 := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_op_val_ne_shift_ops i

/-- No static BinaryTable row carries the Arith MULW bus opcode `182`
    (`OP_MUL_W`) nor the alternate `m32 = 0` decomposition value `166`
    (`= 182 - 16`). Used by the MULW dispatch to exclude the static
    Binary provider branch. -/
theorem rowOfIndex_op_val_ne_arith_mul_w (i : Fin tableSize) :
    (rowOfIndex i.val).op.val ≠ 182
      ∧ (rowOfIndex i.val).op.val ≠ 166 := by
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  unfold rowOfIndex opOfIndex
  rw [Fin.val_natCast]
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  refine ⟨?_, ?_⟩ <;>
    interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR,
      OP_LTU, OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE,
      OP_SEXT_00, OP_SEXT_FF, OP_MINU, OP_MIN, OP_MAXU, OP_MAX,
      OP_LT_ABS_NP, OP_LT_ABS_PN]

theorem spec_op_val_ne_arith_mul_w {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    t.op.val ≠ 182 ∧ t.op.val ≠ 166 := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_op_val_ne_arith_mul_w i

theorem rowOfIndex_op_val_ne_arith_mul_uh (i : Fin tableSize) :
    (rowOfIndex i.val).op.val ≠ 177
      ∧ (rowOfIndex i.val).op.val ≠ 161 := by
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  unfold rowOfIndex opOfIndex
  rw [Fin.val_natCast]
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  refine ⟨?_, ?_⟩ <;>
    interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR,
      OP_LTU, OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE,
      OP_SEXT_00, OP_SEXT_FF, OP_MINU, OP_MIN, OP_MAXU, OP_MAX,
      OP_LT_ABS_NP, OP_LT_ABS_PN]

theorem spec_op_val_ne_arith_mul_uh {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    t.op.val ≠ 177 ∧ t.op.val ≠ 161 := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_op_val_ne_arith_mul_uh i

theorem rowOfIndex_op_val_ne_arith_divu (i : Fin tableSize) :
    (rowOfIndex i.val).op.val ≠ 184
      ∧ (rowOfIndex i.val).op.val ≠ 168 := by
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  unfold rowOfIndex opOfIndex
  rw [Fin.val_natCast]
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  refine ⟨?_, ?_⟩ <;>
    interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR,
      OP_LTU, OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE,
      OP_SEXT_00, OP_SEXT_FF, OP_MINU, OP_MIN, OP_MAXU, OP_MAX,
      OP_LT_ABS_NP, OP_LT_ABS_PN]

theorem spec_op_val_ne_arith_divu {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    t.op.val ≠ 184 ∧ t.op.val ≠ 168 := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_op_val_ne_arith_divu i

theorem rowOfIndex_op_val_ne_arith_remu (i : Fin tableSize) :
    (rowOfIndex i.val).op.val ≠ 185
      ∧ (rowOfIndex i.val).op.val ≠ 169 := by
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  unfold rowOfIndex opOfIndex
  rw [Fin.val_natCast]
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  refine ⟨?_, ?_⟩ <;>
    interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR,
      OP_LTU, OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE,
      OP_SEXT_00, OP_SEXT_FF, OP_MINU, OP_MIN, OP_MAXU, OP_MAX,
      OP_LT_ABS_NP, OP_LT_ABS_PN]

theorem spec_op_val_ne_arith_remu {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    t.op.val ≠ 185 ∧ t.op.val ≠ 169 := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_op_val_ne_arith_remu i

theorem rowOfIndex_op_val_ne_arith_divuw (i : Fin tableSize) :
    (rowOfIndex i.val).op.val ≠ 188
      ∧ (rowOfIndex i.val).op.val ≠ 172 := by
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  unfold rowOfIndex opOfIndex
  rw [Fin.val_natCast]
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  refine ⟨?_, ?_⟩ <;>
    interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR,
      OP_LTU, OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE,
      OP_SEXT_00, OP_SEXT_FF, OP_MINU, OP_MIN, OP_MAXU, OP_MAX,
      OP_LT_ABS_NP, OP_LT_ABS_PN]

theorem spec_op_val_ne_arith_divuw {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    t.op.val ≠ 188 ∧ t.op.val ≠ 172 := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_op_val_ne_arith_divuw i

theorem rowOfIndex_op_val_ne_arith_remuw (i : Fin tableSize) :
    (rowOfIndex i.val).op.val ≠ 189
      ∧ (rowOfIndex i.val).op.val ≠ 173 := by
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  unfold rowOfIndex opOfIndex
  rw [Fin.val_natCast]
  generalize h_block : blockOfIndex i.val = block
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  refine ⟨?_, ?_⟩ <;>
    interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR,
      OP_LTU, OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE,
      OP_SEXT_00, OP_SEXT_FF, OP_MINU, OP_MIN, OP_MAXU, OP_MAX,
      OP_LT_ABS_NP, OP_LT_ABS_PN]

theorem spec_op_val_ne_arith_remuw {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    t.op.val ≠ 189 ∧ t.op.val ≠ 173 := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_op_val_ne_arith_remuw i

theorem signByte_eq_zero_iff_lt_128 {a : ℕ} (ha : a < 256) :
    signByte a = 0 ↔ a < 128 := by
  interval_cases a <;> decide

theorem signByte_eq_one_iff_ge_128 {a : ℕ} (ha : a < 256) :
    signByte a = 1 ↔ 128 ≤ a := by
  have hzero := signByte_eq_zero_iff_lt_128 ha
  have hlt : a < 128 ∨ 128 ≤ a := by omega
  constructor
  · intro h
    rcases hlt with hlt | hge
    · have hz : signByte a = 0 := hzero.mpr hlt
      omega
    · exact hge
  · intro hge
    have hval : signByte a < 2 := signByte_lt_two a
    have hne : signByte a ≠ 0 := by
      intro hz
      have hlt' := hzero.mp hz
      omega
    omega

theorem rowOfIndex_add_sub_final_flags_eq_sign (i : Fin tableSize)
    (h_op : (rowOfIndex i.val).op.val = OP_ADD ∨
      (rowOfIndex i.val).op.val = OP_SUB)
    (h_pos : (rowOfIndex i.val).pos_ind.val = 1) :
    (rowOfIndex i.val).flags.val = 8 * signByte (rowOfIndex i.val).c_byte.val := by
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  unfold rowOfIndex opOfIndex at h_op h_pos ⊢
  simp only at h_op h_pos ⊢
  rw [Fin.val_natCast] at h_op h_pos ⊢
  generalize h_block : blockOfIndex i.val = block at h_op h_pos ⊢
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;>
    norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU, OP_LT, OP_GT, OP_EQ,
      OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF, OP_MINU, OP_MIN,
      OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  · have h_pos_nat : posIndOfIndex i.val = 1 := by
      have h_pos_lt : posIndOfIndex i.val < 2 := by
        simp [posIndOfIndex, h_block]
        split <;> omega
      omega
    have hc_lt : cOfIndex i.val < 18446744069414584321 := by
      have hmod : (cinOfIndex i.val + lowByte i.val + highByte i.val) % 256 < 256 :=
        Nat.mod_lt _ (by norm_num)
      simp [cOfIndex, h_block]
      omega
    simp [flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
      cIsSignedOfIndex, h_block, h_pos_nat, Nat.mod_eq_of_lt hc_lt]
    split <;> norm_num
  · have h_pos_nat : posIndOfIndex i.val = 1 := by
      have h_pos_lt : posIndOfIndex i.val < 2 := by
        simp [posIndOfIndex, h_block]
        split <;> omega
      omega
    have hc_lt : cOfIndex i.val < 18446744069414584321 := by
      have hlow : lowByte i.val < 256 := by
        unfold lowByte
        exact Nat.mod_lt _ (by norm_num)
      have hhigh : highByte i.val < 256 := by
        unfold highByte
        exact Nat.mod_lt _ (by norm_num)
      have hcin : cinOfIndex i.val < 2 := by
        simp [cinOfIndex, h_block]
        split <;> omega
      simp [cOfIndex, h_block]
      split <;> omega
    simp [flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
      cIsSignedOfIndex, h_block, h_pos_nat, Nat.mod_eq_of_lt hc_lt]
    split <;> norm_num

theorem spec_add_sub_final_flags_eq_sign {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t)
    (h_op : t.op.val = OP_ADD ∨ t.op.val = OP_SUB)
    (h_pos : t.pos_ind.val = 1) :
    t.flags.val = 8 * signByte t.c_byte.val := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_add_sub_final_flags_eq_sign i h_op h_pos

open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_AND (i : Fin tableSize) :
    wf_AND (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_high : highByte i.val < 256 := by
    unfold highByte
    exact Nat.mod_lt _ (by norm_num)
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  constructor
  · simp [cOfIndex, h_block]
    have h_and_p : lowByte i.val &&& highByte i.val < 18446744069414584321 :=
      lt_of_le_of_lt Nat.and_le_left (by omega)
    rw [Nat.mod_eq_of_lt h_and_p]
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)]
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)]
  · simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
      cIsSignedOfIndex]

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_AND {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_AND (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_AND i

open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_OR (i : Fin tableSize) :
    wf_OR (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_high : highByte i.val < 256 := by
    unfold highByte
    exact Nat.mod_lt _ (by norm_num)
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  constructor
  · simp [cOfIndex, h_block]
    have h_or : lowByte i.val ||| highByte i.val < 2 ^ 8 :=
      Nat.or_lt_two_pow (by simpa using h_low) (by simpa using h_high)
    have h_or_p : lowByte i.val ||| highByte i.val < 18446744069414584321 := by
      omega
    rw [Nat.mod_eq_of_lt h_or_p]
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)]
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)]
  · simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
      cIsSignedOfIndex]

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_OR {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_OR (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_OR i

open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_XOR (i : Fin tableSize) :
    wf_XOR (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_high : highByte i.val < 256 := by
    unfold highByte
    exact Nat.mod_lt _ (by norm_num)
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  constructor
  · simp [cOfIndex, h_block]
    have h_xor : lowByte i.val ^^^ highByte i.val < 2 ^ 8 :=
      Nat.xor_lt_two_pow (by simpa using h_low) (by simpa using h_high)
    have h_xor_p : lowByte i.val ^^^ highByte i.val < 18446744069414584321 := by
      omega
    rw [Nat.mod_eq_of_lt h_xor_p]
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)]
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)]
  · simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
      cIsSignedOfIndex]

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_XOR {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_XOR (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_XOR i

open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_SEXT_00 (i : Fin tableSize) :
    wf_SEXT_00 (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  constructor
  · simp [cOfIndex, h_block]
  · simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
      cIsSignedOfIndex]
    split <;> split <;> norm_num

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_SEXT_00 {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_SEXT_00 (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_SEXT_00 i

open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_SEXT_FF (i : Fin tableSize) :
    wf_SEXT_FF (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  constructor
  · simp [cOfIndex, h_block]
  · simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
      cIsSignedOfIndex]
    split <;> split <;> norm_num

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_SEXT_FF {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_SEXT_FF (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_SEXT_FF i

open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_ADD (i : Fin tableSize) :
    wf_ADD (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_high : highByte i.val < 256 := by
    unfold highByte
    exact Nat.mod_lt _ (by norm_num)
  have h_cin : cinOfIndex i.val < 2 := by
    simp [cinOfIndex]
    split <;> try exact Nat.mod_lt _ (by norm_num)
    split <;> try omega
    split <;> try omega
    split <;> try omega
    split <;> try omega
    split <;> try omega
    split <;> omega
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  constructor
  · simp [cOfIndex, h_block]
    rw [add_mod_highByte]
    have h_cin_eq :
        cinOfIndex i.val = (if relativeIndex i.val < p2_17 then 0 else 1) := by
      simp [cinOfIndex, h_block]
    have h_sum_lt :
        (cinOfIndex i.val + lowByte i.val + highByte i.val) % 256 <
            18446744069414584321 := by
      have h_mod :
          (cinOfIndex i.val + lowByte i.val + highByte i.val) % 256 < 256 :=
        Nat.mod_lt _ (by norm_num)
      omega
    rw [Nat.mod_eq_of_lt h_sum_lt]
    rw [h_cin_eq]
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)]
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)]
    split <;> norm_num
  constructor
  · intro h_not_last
    have h_cin_eq :
        cinOfIndex i.val = (if relativeIndex i.val < p2_17 then 0 else 1) := by
      simp [cinOfIndex, h_block]
    by_cases h_pos : posIndOfIndex i.val = 1
    · exfalso
      exact h_not_last (by simp [h_pos])
    · simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, h_pos] at *
      have h_carry_lt :
          (cinOfIndex i.val + lowByte i.val + highByte i.val) / 256 <
              18446744069414584321 := by
        omega
      have h_carry_two :
          (cinOfIndex i.val + lowByte i.val + highByte i.val) / 256 < 2 := by
        omega
      rw [Nat.mod_eq_of_lt h_carry_lt]
      rw [Nat.mod_eq_of_lt h_carry_two]
      rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)]
      rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)]
      rw [h_cin_eq]
      split <;> norm_num
  · intro h_last
    by_cases h_pos : posIndOfIndex i.val = 1
    · simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, h_pos]
      split <;> norm_num
    · exfalso
      have h_pos_from_last : posIndOfIndex i.val = 1 := by
        simp [posIndOfIndex, h_block] at h_last ⊢
        split at h_last <;> omega
      exact h_pos h_pos_from_last

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_ADD {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_ADD (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_ADD i

open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_SUB (i : Fin tableSize) :
    wf_SUB (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_high : highByte i.val < 256 := by
    unfold highByte
    exact Nat.mod_lt _ (by norm_num)
  have h_cin : cinOfIndex i.val < 2 := by
    simp [cinOfIndex]
    split <;> try exact Nat.mod_lt _ (by norm_num)
    split <;> try omega
    split <;> try omega
    split <;> try omega
    split <;> try omega
    split <;> try omega
    split <;> omega
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  have h_cin_eq :
      cinOfIndex i.val = (if relativeIndex i.val < p2_17 then 0 else 1) := by
    simp [cinOfIndex, h_block]
  constructor
  · intro hge
    simp [cOfIndex, h_block] at hge ⊢
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at hge
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at hge
    have hbranch : cinOfIndex i.val + highByte i.val ≤ lowByte i.val := by
      by_cases hr : relativeIndex i.val < p2_17
      · simp [h_cin_eq, hr] at hge ⊢
        omega
      · simp [h_cin_eq, hr] at hge ⊢
        omega
    simp [hbranch]
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)]
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)]
    by_cases hr : relativeIndex i.val < p2_17
    · simp [h_cin_eq, hr]
      omega
    · simp [h_cin_eq, hr]
      omega
  constructor
  · intro hlt
    simp [cOfIndex, h_block] at hlt ⊢
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at hlt
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at hlt
    have hbranch : ¬ cinOfIndex i.val + highByte i.val ≤ lowByte i.val := by
      by_cases hr : relativeIndex i.val < p2_17
      · simp [h_cin_eq, hr] at hlt ⊢
        omega
      · simp [h_cin_eq, hr] at hlt ⊢
        omega
    simp [hbranch]
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)]
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)]
    by_cases hr : relativeIndex i.val < p2_17
    · simp [h_cin_eq, hr]
      omega
    · simp [h_cin_eq, hr]
      omega
  constructor
  · intro h_not_last
    by_cases h_pos : posIndOfIndex i.val = 1
    · exfalso
      exact h_not_last (by simp [h_pos])
    · constructor
      · intro hge
        simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, h_pos] at *
        rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at hge
        rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at hge
        have hnot : ¬ lowByte i.val < cinOfIndex i.val + highByte i.val := by
          by_cases hr : relativeIndex i.val < p2_17
          · simp [h_cin_eq, hr] at hge ⊢
            omega
          · simp [h_cin_eq, hr] at hge ⊢
            omega
        simp [hnot]
      · intro hlt
        simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
          cIsSignedOfIndex, h_pos] at *
        rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at hlt
        rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at hlt
        have hborrow : lowByte i.val < cinOfIndex i.val + highByte i.val := by
          by_cases hr : relativeIndex i.val < p2_17
          · simp [h_cin_eq, hr] at hlt ⊢
            omega
          · simp [h_cin_eq, hr] at hlt ⊢
            omega
        simp [hborrow]
  · intro h_last
    by_cases h_pos : posIndOfIndex i.val = 1
    · simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, h_pos]
      split <;> norm_num
    · exfalso
      have h_pos_from_last : posIndOfIndex i.val = 1 := by
        simp [posIndOfIndex, h_block] at h_last ⊢
        split at h_last <;> omega
      exact h_pos h_pos_from_last

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_SUB {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_SUB (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_SUB i

open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_LTU (i : Fin tableSize) :
    wf_LTU (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_high : highByte i.val < 256 := by
    unfold highByte
    exact Nat.mod_lt _ (by norm_num)
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  constructor
  · simp [cOfIndex, h_block]
  constructor
  · intro hlt
    simp at hlt
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at hlt
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at hlt
    simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
      cIsSignedOfIndex, coutLt, hlt]
  constructor
  · intro heq
    simp at heq
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at heq
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at heq
    simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
      cIsSignedOfIndex, coutLt, heq]
    split <;> norm_num
  · intro hgt
    simp at hgt
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at hgt
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at hgt
    simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
      cIsSignedOfIndex, coutLt]
    split <;> try omega
    split <;> omega

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_LTU {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_LTU (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_LTU i

open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_EQ (i : Fin tableSize) :
    wf_EQ (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_high : highByte i.val < 256 := by
    unfold highByte
    exact Nat.mod_lt _ (by norm_num)
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  constructor
  · simp [cOfIndex, h_block]
  constructor
  · intro h_nonfinal
    simp [posIndOfIndex, h_block] at h_nonfinal
    have hpos0 : relativeIndex i.val / p2_16 % 2 = 0 := by
      by_contra hpos
      apply h_nonfinal
      simp [hpos]
    constructor
    · intro h_eq
      rcases h_eq with ⟨hcin, hab⟩
      simp at hcin hab
      rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at hab
      rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at hab
      simp [h_block] at hcin
      simp [h_block, posIndOfIndex, cinOfIndex, flagsOfIndex, coutOfIndex,
        resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, hcin, hab, hpos0]
    · intro h_neq
      simp at h_neq
      rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at h_neq
      rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at h_neq
      simp [h_block] at h_neq
      simp [h_block, posIndOfIndex, cinOfIndex, flagsOfIndex, coutOfIndex,
        resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, hpos0]
      by_cases hcin0 : relativeIndex i.val < p2_17
      · simp [hcin0]
        by_cases hab' : lowByte i.val = highByte i.val
        · exact (h_neq hcin0 hab').elim
        · simp [hab']
      · simp [hcin0]
  · intro h_final
    simp [posIndOfIndex, h_block] at h_final
    have hpos1 : relativeIndex i.val / p2_16 % 2 = 1 := by
      have hlt : relativeIndex i.val / p2_16 % 2 < 2 := Nat.mod_lt _ (by norm_num)
      have hne : relativeIndex i.val / p2_16 % 2 ≠ 0 := by
        intro hzero
        have hfinal0 := h_final
        simp [hzero] at hfinal0
      omega
    constructor
    · intro h_eq
      rcases h_eq with ⟨hcin, hab⟩
      simp at hcin hab
      rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at hab
      rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at hab
      simp [h_block] at hcin
      simp [h_block, posIndOfIndex, cinOfIndex, flagsOfIndex, coutOfIndex,
        resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, hcin, hab, hpos1]
    · intro h_neq
      simp at h_neq
      rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at h_neq
      rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at h_neq
      simp [h_block] at h_neq
      simp [h_block, posIndOfIndex, cinOfIndex, flagsOfIndex, coutOfIndex,
        resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, hpos1]
      by_cases hcin0 : relativeIndex i.val < p2_17
      · simp [hcin0]
        by_cases hab' : lowByte i.val = highByte i.val
        · exact (h_neq hcin0 hab').elim
        · simp [hab']
      · simp [hcin0]

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_EQ {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_EQ (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_EQ i

open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_LT (i : Fin tableSize) :
    wf_LT (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_high : highByte i.val < 256 := by
    unfold highByte
    exact Nat.mod_lt _ (by norm_num)
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  constructor
  · simp [cOfIndex, h_block]
  constructor
  · intro h_chain
    constructor
    · intro hlt
      simp at hlt
      rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at hlt
      rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at hlt
      rcases h_chain with h_nonfinal | h_sign_eq
      · simp [posIndOfIndex, h_block] at h_nonfinal
        have hpos0 : relativeIndex i.val / p2_16 % 2 = 0 := by
          by_contra hpos
          apply h_nonfinal
          simp [hpos]
        simp [h_block, posIndOfIndex, flagsOfIndex, coutOfIndex, resultIsAOfIndex,
          useFirstByteOfIndex, cIsSignedOfIndex, coutLt, hlt, hpos0]
      · simp at h_sign_eq
        rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at h_sign_eq
        rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at h_sign_eq
        simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
          cIsSignedOfIndex, coutLt, hlt, h_sign_eq]
    constructor
    · intro heq
      simp at heq
      rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at heq
      rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at heq
      rcases h_chain with h_nonfinal | h_sign_eq
      · simp [posIndOfIndex, h_block] at h_nonfinal
        have hpos0 : relativeIndex i.val / p2_16 % 2 = 0 := by
          by_contra hpos
          apply h_nonfinal
          simp [hpos]
        simp [h_block, posIndOfIndex, cinOfIndex, flagsOfIndex, coutOfIndex, resultIsAOfIndex,
          useFirstByteOfIndex, cIsSignedOfIndex, coutLt, heq, hpos0]
        split <;> norm_num
      · simp at h_sign_eq
        rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at h_sign_eq
        rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at h_sign_eq
        simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
          cIsSignedOfIndex, coutLt, heq]
        split <;> norm_num
    · intro hgt
      simp at hgt
      rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at hgt
      rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at hgt
      rcases h_chain with h_nonfinal | h_sign_eq
      · simp [posIndOfIndex, h_block] at h_nonfinal
        have hpos0 : relativeIndex i.val / p2_16 % 2 = 0 := by
          by_contra hpos
          apply h_nonfinal
          simp [hpos]
        simp [h_block, posIndOfIndex, flagsOfIndex, coutOfIndex, resultIsAOfIndex,
          useFirstByteOfIndex, cIsSignedOfIndex, coutLt, hpos0]
        split <;> try omega
        split <;> omega
      · simp at h_sign_eq
        rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at h_sign_eq
        rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at h_sign_eq
        simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
          cIsSignedOfIndex, coutLt, h_sign_eq]
        split <;> try omega
        split <;> omega
  · intro h_final h_diff
    simp at h_final h_diff
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at h_diff
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at h_diff
    simp [h_block] at h_final
    have hpos1 : relativeIndex i.val / p2_16 % 2 = 1 := by
      have hlt : relativeIndex i.val / p2_16 % 2 < 2 := Nat.mod_lt _ (by norm_num)
      have hne : relativeIndex i.val / p2_16 % 2 ≠ 0 := by
        intro hzero
        have hfinal0 := h_final
        simp [hzero] at hfinal0
      omega
    simp [h_block, posIndOfIndex, flagsOfIndex, coutOfIndex, resultIsAOfIndex,
      useFirstByteOfIndex, cIsSignedOfIndex, signByte, hpos1, h_diff]
    simp [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)]
    split <;> norm_num

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_LT {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_LT (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_LT i

theorem cinOfIndex_lt_two (i : ℕ) : cinOfIndex i < 2 := by
  simp [cinOfIndex]
  split <;> try exact Nat.mod_lt _ (by norm_num)
  split <;> try omega
  split <;> try omega
  split <;> try omega
  split <;> try omega
  split <;> try omega
  split <;> omega

theorem coutOfIndex_abs_block_lt_two (i : ℕ)
    (h_block : blockOfIndex i = 4 ∨ blockOfIndex i = 5) :
    coutOfIndex i < 2 := by
  have hcin := cinOfIndex_lt_two i
  rcases h_block with h4 | h5
  · simp [coutOfIndex, h4]
    split <;> exact coutLt_lt_two hcin
  · simp [coutOfIndex, h5]
    split <;> exact coutLt_lt_two hcin

theorem flagsOfIndex_abs_mod_two_eq_cout (i : ℕ)
    (h_block : blockOfIndex i = 4 ∨ blockOfIndex i = 5) :
    flagsOfIndex i % 2 = coutOfIndex i := by
  have hcout := coutOfIndex_abs_block_lt_two i h_block
  have hcout_cases : coutOfIndex i = 0 ∨ coutOfIndex i = 1 := by omega
  rcases h_block with h4 | h5
  · rcases hcout_cases with hcout0 | hcout1
    · simp [flagsOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, h4, hcout0]
    · simp [flagsOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, h4, hcout1]
  · rcases hcout_cases with hcout0 | hcout1
    · simp [flagsOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, h5, hcout0]
    · simp [flagsOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, h5, hcout1]

set_option maxHeartbeats 800000 in
open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_LT_ABS_NP (i : Fin tableSize) :
    wf_LT_ABS_NP (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  change opOfBlock block % 18446744069414584321 = 80 at h_op
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  constructor
  · simp [cOfIndex, h_block]
  · have hflags := flagsOfIndex_abs_mod_two_eq_cout i.val (Or.inl h_block)
    have hflags_val :
        (BinaryTableMessage.toEntry (rowOfIndex i.val) 1).flags.val =
          flagsOfIndex i.val := by
      change ((flagsOfIndex i.val : FGL).val = flagsOfIndex i.val)
      apply Nat.mod_eq_of_lt
      have hcout := coutOfIndex_abs_block_lt_two i.val (Or.inl h_block)
      simp [flagsOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, h_block]
      omega
    rw [hflags_val, hflags]
    have hlow_mod :
        lowByte i.val % 18446744069414584321 = lowByte i.val := by
      apply Nat.mod_eq_of_lt
      unfold lowByte
      omega
    have hhigh_mod :
        highByte i.val % 18446744069414584321 = highByte i.val := by
      apply Nat.mod_eq_of_lt
      unfold highByte
      omega
    have hcin_mod :
        cinOfIndex i.val % 18446744069414584321 = cinOfIndex i.val := by
      apply Nat.mod_eq_of_lt
      have hcin := cinOfIndex_lt_two i.val
      omega
    dsimp [rowOfIndex, BinaryTableMessage.toEntry, coutOfIndex, posIndOfIndex]
    rw [h_block]
    simp [coutLt, hlow_mod, hhigh_mod, hcin_mod]
    aesop (config := { warnOnNonterminal := false })
    all_goals omega

set_option maxHeartbeats 800000 in
open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_LT_ABS_PN (i : Fin tableSize) :
    wf_LT_ABS_PN (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  change opOfBlock block % 18446744069414584321 = 81 at h_op
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  constructor
  · simp [cOfIndex, h_block]
  · have hflags := flagsOfIndex_abs_mod_two_eq_cout i.val (Or.inr h_block)
    have hflags_val :
        (BinaryTableMessage.toEntry (rowOfIndex i.val) 1).flags.val =
          flagsOfIndex i.val := by
      change ((flagsOfIndex i.val : FGL).val = flagsOfIndex i.val)
      apply Nat.mod_eq_of_lt
      have hcout := coutOfIndex_abs_block_lt_two i.val (Or.inr h_block)
      simp [flagsOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
        cIsSignedOfIndex, h_block]
      omega
    rw [hflags_val, hflags]
    have hlow_mod :
        lowByte i.val % 18446744069414584321 = lowByte i.val := by
      apply Nat.mod_eq_of_lt
      unfold lowByte
      omega
    have hhigh_mod :
        highByte i.val % 18446744069414584321 = highByte i.val := by
      apply Nat.mod_eq_of_lt
      unfold highByte
      omega
    have hcin_mod :
        cinOfIndex i.val % 18446744069414584321 = cinOfIndex i.val := by
      apply Nat.mod_eq_of_lt
      have hcin := cinOfIndex_lt_two i.val
      omega
    dsimp [rowOfIndex, BinaryTableMessage.toEntry, coutOfIndex, posIndOfIndex]
    rw [h_block]
    simp [coutLt, hlow_mod, hhigh_mod, hcin_mod]
    aesop (config := { warnOnNonterminal := false })
    all_goals omega

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_LT_ABS_NP {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_LT_ABS_NP (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_LT_ABS_NP i

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_LT_ABS_PN {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_LT_ABS_PN (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_LT_ABS_PN i

open ZiskFv.Airs.Tables.BinaryTable in
theorem rowOfIndex_wf_GT (i : Fin tableSize) :
    wf_GT (BinaryTableMessage.toEntry (rowOfIndex i.val) 1) := by
  intro h_op
  have h_low : lowByte i.val < 256 := by
    unfold lowByte
    exact Nat.mod_lt _ (by norm_num)
  have h_high : highByte i.val < 256 := by
    unfold highByte
    exact Nat.mod_lt _ (by norm_num)
  have h_block_lt : blockOfIndex i.val < 19 := blockOfIndex_lt_19 i
  simp only at h_op
  rw [Fin.val_natCast] at h_op
  unfold opOfIndex at h_op
  generalize h_block : blockOfIndex i.val = block at h_op
  have h_block_lt' : block < 19 := by
    rw [← h_block]
    exact h_block_lt
  interval_cases block <;> norm_num [opOfBlock, OP_AND, OP_OR, OP_XOR, OP_LTU,
    OP_LT, OP_GT, OP_EQ, OP_ADD, OP_SUB, OP_LEU, OP_LE, OP_SEXT_00, OP_SEXT_FF,
    OP_MINU, OP_MIN, OP_MAXU, OP_MAX, OP_LT_ABS_NP, OP_LT_ABS_PN] at h_op
  constructor
  · simp [cOfIndex, h_block]
  constructor
  · intro h_chain
    constructor
    · intro hgt
      simp at hgt
      rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at hgt
      rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at hgt
      rcases h_chain with h_nonfinal | h_sign_eq
      · simp [posIndOfIndex, h_block] at h_nonfinal
        have hpos0 : relativeIndex i.val / p2_16 % 2 = 0 := by
          by_contra hpos
          apply h_nonfinal
          simp [hpos]
        simp [h_block, posIndOfIndex, flagsOfIndex, coutOfIndex, resultIsAOfIndex,
          useFirstByteOfIndex, cIsSignedOfIndex, coutGt, hgt, hpos0]
      · simp at h_sign_eq
        rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at h_sign_eq
        rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at h_sign_eq
        simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
          cIsSignedOfIndex, coutGt, hgt, h_sign_eq]
    constructor
    · intro heq
      simp at heq
      rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at heq
      rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at heq
      rcases h_chain with h_nonfinal | h_sign_eq
      · simp [posIndOfIndex, h_block] at h_nonfinal
        have hpos0 : relativeIndex i.val / p2_16 % 2 = 0 := by
          by_contra hpos
          apply h_nonfinal
          simp [hpos]
        simp [h_block, posIndOfIndex, cinOfIndex, flagsOfIndex, coutOfIndex, resultIsAOfIndex,
          useFirstByteOfIndex, cIsSignedOfIndex, coutGt, heq, hpos0]
        split <;> norm_num
      · simp at h_sign_eq
        rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at h_sign_eq
        rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at h_sign_eq
        simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
          cIsSignedOfIndex, coutGt, heq]
        split <;> norm_num
    · intro hlt
      simp at hlt
      rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at hlt
      rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at hlt
      rcases h_chain with h_nonfinal | h_sign_eq
      · simp [posIndOfIndex, h_block] at h_nonfinal
        have hpos0 : relativeIndex i.val / p2_16 % 2 = 0 := by
          by_contra hpos
          apply h_nonfinal
          simp [hpos]
        simp [h_block, posIndOfIndex, flagsOfIndex, coutOfIndex, resultIsAOfIndex,
          useFirstByteOfIndex, cIsSignedOfIndex, coutGt, hpos0]
        split <;> try omega
        split <;> omega
      · simp at h_sign_eq
        rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at h_sign_eq
        rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at h_sign_eq
        simp [h_block, flagsOfIndex, coutOfIndex, resultIsAOfIndex, useFirstByteOfIndex,
          cIsSignedOfIndex, coutGt, h_sign_eq]
        split <;> try omega
        split <;> omega
  · intro h_final h_diff
    simp at h_final h_diff
    rw [Nat.mod_eq_of_lt (by omega : lowByte i.val < 18446744069414584321)] at h_diff
    rw [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)] at h_diff
    simp [h_block] at h_final
    have hpos1 : relativeIndex i.val / p2_16 % 2 = 1 := by
      have hlt : relativeIndex i.val / p2_16 % 2 < 2 := Nat.mod_lt _ (by norm_num)
      have hne : relativeIndex i.val / p2_16 % 2 ≠ 0 := by
        intro hzero
        have hfinal0 := h_final
        simp [hzero] at hfinal0
      omega
    simp [h_block, posIndOfIndex, flagsOfIndex, coutOfIndex, resultIsAOfIndex,
      useFirstByteOfIndex, cIsSignedOfIndex, signByte, hpos1, h_diff]
    simp [Nat.mod_eq_of_lt (by omega : highByte i.val < 18446744069414584321)]
    split <;> norm_num

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_GT {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_GT (BinaryTableMessage.toEntry t 1) := by
  rcases h with ⟨i, rfl⟩
  exact rowOfIndex_wf_GT i

open ZiskFv.Airs.Tables.BinaryTable in
theorem spec_wf_properties {t : BinaryTableMessage FGL}
    (h : binaryTable.Spec t) :
    wf_properties (BinaryTableMessage.toEntry t 1) := by
  exact ⟨ spec_range_conditions h
        , spec_wf_AND h
        , spec_wf_OR h
        , spec_wf_XOR h
        , spec_wf_LTU h
        , spec_wf_LT h
        , spec_wf_EQ h
        , spec_wf_ADD h
        , spec_wf_SUB h
        , spec_wf_SEXT_00 h
        , spec_wf_SEXT_FF h ⟩

end ZiskFv.AirsClean.BinaryTable
