//! Parser + emitter for the arith-table state-machine lookup table.
//!
//! The 74-row table lives upstream as a Rust `static ARITH_TABLE: [[u16; 4]; ROWS]`
//! constant in `state-machines/arith/src/arith_table_data.rs`. PIL generates
//! that file once via `arith_table.pil` with `generate_table = 1`; both
//! files share the same encoding:
//!
//! * Each row is `[opcode: u16, flags: u16, range_ab: u16, range_cd: u16]`.
//! * `flags` is a 12-bit packing in little-endian bit order:
//!     bit 0  m32        bit 6  sext
//!     bit 1  div        bit 7  div_by_zero
//!     bit 2  na         bit 8  div_overflow
//!     bit 3  nb         bit 9  main_mul
//!     bit 4  np         bit 10 main_div
//!     bit 5  nr         bit 11 signed
//!
//! The emitted Lean module mirrors what `ZiskFv/Extraction/ArithTable.lean`
//! used to declare by hand. It lives in the auto-extracted `Extraction`
//! lake-lib, which cannot depend on `ZiskFv.Trusted`, so opcode values are
//! emitted as raw `FGL` literals (`(176 : FGL)`) rather than the symbolic
//! `OP_MULU` names. The two are kernel-definitionally equal because each
//! `OP_*` is a `@[simp] def OP_X : FGL := <num>`.

use std::fmt::Write;
use std::path::Path;

use anyhow::{bail, Context, Result};
use regex::Regex;

const FIELD_NAMES: [&str; 12] = [
    "m32",
    "div",
    "na",
    "nb",
    "np",
    "nr",
    "sext",
    "div_by_zero",
    "div_overflow",
    "main_mul",
    "main_div",
    "signed",
];

/// Parse the upstream Rust source and emit a self-contained Lean module.
pub fn run(rust_source: &Path, output: Option<&Path>) -> Result<String> {
    let text = std::fs::read_to_string(rust_source)
        .with_context(|| format!("failed to read {}", rust_source.display()))?;
    let rows = parse_arith_table(&text)
        .with_context(|| format!("failed to parse ARITH_TABLE in {}", rust_source.display()))?;
    let lean = emit_lean(&rows);

    if let Some(path) = output {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).ok();
        }
        std::fs::write(path, &lean)
            .with_context(|| format!("failed to write {}", path.display()))?;
        tracing::info!(path = %path.display(), rows = rows.len(), "wrote arith-table extraction");
    }
    Ok(lean)
}

#[derive(Debug, Clone, Copy)]
struct RawRow {
    opcode: u16,
    flags: u16,
    range_ab: u16,
    range_cd: u16,
}

fn parse_arith_table(text: &str) -> Result<Vec<RawRow>> {
    // Locate the ARITH_TABLE block. The upstream file gates it under
    // `#[cfg(test)]`, but we don't care about cfg attributes — we only
    // need the literal data.
    let block_start = text
        .find("ARITH_TABLE:")
        .context("ARITH_TABLE declaration not found")?;
    // Restrict the regex to everything after the declaration to avoid
    // matching unrelated array literals (e.g. ARITH_TABLE_ROWS, which
    // is also an array literal but uses single-element rows).
    let tail = &text[block_start..];
    let row_re =
        Regex::new(r"\[\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\]").unwrap();
    let mut rows = Vec::new();
    for caps in row_re.captures_iter(tail) {
        let opcode: u16 = caps[1].parse().context("opcode parse")?;
        let flags: u16 = caps[2].parse().context("flags parse")?;
        let range_ab: u16 = caps[3].parse().context("range_ab parse")?;
        let range_cd: u16 = caps[4].parse().context("range_cd parse")?;
        rows.push(RawRow {
            opcode,
            flags,
            range_ab,
            range_cd,
        });
    }
    if rows.is_empty() {
        bail!("ARITH_TABLE block found but no rows parsed");
    }
    Ok(rows)
}

/// Emit the Lean module corresponding to the parsed rows. Output mirrors
/// the layout `ZiskFv/Extraction/ArithTable.lean` used to hand-maintain.
fn emit_lean(rows: &[RawRow]) -> String {
    let mut out = String::new();
    writeln!(out, "import Mathlib").unwrap();
    writeln!(out, "import ZiskFv.Fundamentals.Goldilocks").unwrap();
    out.push('\n');
    writeln!(out, "/-!").unwrap();
    writeln!(out, "# Extracted arith_table data.").unwrap();
    out.push('\n');
    writeln!(
        out,
        "Auto-generated by `pil-extract arith-table` from"
    )
    .unwrap();
    writeln!(
        out,
        "`zisk/state-machines/arith/src/arith_table_data.rs::ARITH_TABLE` ({} rows).",
        rows.len()
    )
    .unwrap();
    writeln!(
        out,
        "The Rust constant is itself emitted by PIL with `generate_table = 1`"
    )
    .unwrap();
    writeln!(
        out,
        "(`zisk/state-machines/arith/pil/arith_table.pil:228-253`)."
    )
    .unwrap();
    out.push('\n');
    writeln!(
        out,
        "FLAGS column decoded per `arith_table.pil:209-211`:"
    )
    .unwrap();
    writeln!(
        out,
        "  m32, div, na, nb, np, nr, sext, div_by_zero, div_overflow,"
    )
    .unwrap();
    writeln!(out, "  main_mul, main_div, signed.").unwrap();
    writeln!(out, "-/").unwrap();
    out.push('\n');
    writeln!(out, "namespace Extraction.ArithTable").unwrap();
    out.push('\n');
    writeln!(out, "open Goldilocks").unwrap();
    out.push('\n');
    writeln!(out, "/-- One row of `arith_table` — the structured form. -/").unwrap();
    writeln!(out, "structure ArithTableRow where").unwrap();
    writeln!(out, "  op : FGL").unwrap();
    for name in FIELD_NAMES {
        writeln!(out, "  {name} : Nat").unwrap();
    }
    writeln!(out, "  range_ab : Nat").unwrap();
    writeln!(out, "  range_cd : Nat").unwrap();
    writeln!(out, "  deriving DecidableEq").unwrap();
    out.push('\n');
    writeln!(
        out,
        "/-- The {}-row arith_table extracted from",
        rows.len()
    )
    .unwrap();
    writeln!(
        out,
        "    `zisk/state-machines/arith/src/arith_table_data.rs`. -/"
    )
    .unwrap();
    writeln!(out, "def arith_table : List ArithTableRow := [").unwrap();
    for (i, row) in rows.iter().enumerate() {
        let bits = decode_flags(row.flags);
        let comma = if i + 1 == rows.len() { "" } else { "," };
        writeln!(
            out,
            "  ⟨({} : FGL), {}, {}, {}⟩{}",
            row.opcode,
            bits
                .iter()
                .map(|b| b.to_string())
                .collect::<Vec<_>>()
                .join(", "),
            row.range_ab,
            row.range_cd,
            comma
        )
        .unwrap();
    }
    writeln!(out, "]").unwrap();
    out.push('\n');
    writeln!(out, "end Extraction.ArithTable").unwrap();
    out
}

fn decode_flags(flags: u16) -> [u8; 12] {
    let mut bits = [0u8; 12];
    for (i, bit) in bits.iter_mut().enumerate() {
        *bit = ((flags >> i) & 1) as u8;
    }
    bits
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decodes_known_flag_values() {
        // [180, 2560, 4, 1] → main_mul=1, signed=1, all others 0
        let bits = decode_flags(2560);
        assert_eq!(bits, [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1]);
        // [180, 2564, 7, 1] → na=1, main_mul=1, signed=1
        let bits = decode_flags(2564);
        assert_eq!(bits, [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1]);
        // [186, 3358, 8, 7] → div=1, na=1, nb=1, np=1, dbo=1, main_div=1, signed=1
        let bits = decode_flags(3358);
        assert_eq!(bits, [0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1]);
    }

    #[test]
    fn parses_minimal_table() {
        let src = r#"
            #[cfg(test)]
            pub static ARITH_TABLE: [[u16; 4]; ROWS] = [
                [176, 512, 0, 0],
                [177, 0, 0, 0],
            ];
        "#;
        let rows = parse_arith_table(src).unwrap();
        assert_eq!(rows.len(), 2);
        assert_eq!(rows[0].opcode, 176);
        assert_eq!(rows[0].flags, 512);
    }
}
