import ZiskFv.AirsClean.MemAlignReadByte.Spec
import Clean.Circuit.Basic
import ZiskFv.Channels.MemAlignBus

/-!
# MemAlignReadByte circuit operations (the `main` field of the Component)

The constraint emissions of ZisK's MemAlignReadByte AIR, expressed as a
Clean circuit do-block: one `assertZero` per F-only pilout constraint,
then the memory bus `MemAlignBusChannel.push`.

AUTO-GENERATED by `tools/pil-extract` (`clean-component` subcommand) —
do not hand-edit. The bus push is reconstructed from the proves-side
`gsum_debug_data` hint (`bus_emission_MemAlignReadByte_1`,
`MemoryBuses.lean:1842`) and is slot-for-slot faithful to the
hand-written reference.

The 4 F-typed constraints of ZisK's MemAlignReadByte AIR
(`build/extraction/Extraction/MemAlignReadByte.lean`):

1. `sel_high_4b * (1 - sel_high_4b) = 0`  (sel_high_4b boolean)
2. `sel_high_2b * (1 - sel_high_2b) = 0`  (sel_high_2b boolean)
3. `sel_high_b * (1 - sel_high_b) = 0`    (sel_high_b boolean)
4. `composed_value - (byte_value · b_factor + value_8b · v8_factor
                     + value_16b · v16_factor) = 0`
   (composed_value definitional identity)

The byte_value_factor / value_8b_factor / value_16b_factor are
inlined here because their FGL-typed definitions in `Spec.lean`
don't apply to `Expression FGL`-typed circuit terms.

## Trust note

No axioms.
-/

namespace ZiskFv.AirsClean.MemAlignReadByte

open Goldilocks
open Circuit (assertZero)
open ZiskFv.Channels.MemAlignBus (MemAlignBusChannel)

/-- The 4 MemAlignReadByte F-constraints and the memory bus push,
    taking the row's slot values as `Expression FGL`s. Returns `Unit`
    (MemAlignReadByte is a pure assertion — no fresh witnesses
    introduced inside the circuit). -/
@[circuit_norm]
def main (row : Var MemAlignReadByteRow FGL) : Circuit FGL Unit := do
  -- constraint 0 (mem/pil/mem_align_byte.pil:14)
  assertZero (row.sel_high_4b * (1 - row.sel_high_4b))
  -- constraint 1 (mem/pil/mem_align_byte.pil:15)
  assertZero (row.sel_high_2b * (1 - row.sel_high_2b))
  -- constraint 2 (mem/pil/mem_align_byte.pil:16)
  assertZero (row.sel_high_b * (1 - row.sel_high_b))
  -- constraint 3 (mem/pil/mem_align_byte.pil:57): composed_value
  --   definitional identity.
  -- byte_value_factor: 16777216·s2·sb + 65536·s2·(1-sb) + 256·(1-s2)·sb + (1-s2)·(1-sb)
  -- value_8b_factor:   16777216·s2·(1-sb) + 65536·s2·sb + 256·(1-s2)·(1-sb) + (1-s2)·sb
  -- value_16b_factor:  65536·(1-s2) + s2
  assertZero (row.composed_value
    - (row.byte_value *
        (16777216 * row.sel_high_2b * row.sel_high_b
         + 65536 * row.sel_high_2b * (1 - row.sel_high_b)
         + 256 * (1 - row.sel_high_2b) * row.sel_high_b
         + (1 - row.sel_high_2b) * (1 - row.sel_high_b))
       + row.value_8b *
        (16777216 * row.sel_high_2b * (1 - row.sel_high_b)
         + 65536 * row.sel_high_2b * row.sel_high_b
         + 256 * (1 - row.sel_high_2b) * (1 - row.sel_high_b)
         + (1 - row.sel_high_2b) * row.sel_high_b)
       + row.value_16b *
        (65536 * (1 - row.sel_high_2b) + row.sel_high_2b)))
  -- Bus emission: MemAlignReadByte pushes its proves-side tuple onto
  -- memory bus 10. Reconstructed from the proves-side `gsum_debug_data`
  -- hint (`bus_emission_MemAlignReadByte_1`); slot-for-slot faithful to
  -- the hand-written reference. Read-only AIR — `mem_op` is the literal
  -- `1` (MEMORY_LOAD_OP), `value_1` is the literal `0`.
  MemAlignBusChannel.push
    { mem_op := 1
      addr := ((row.addr_w * 8) + (((row.sel_high_4b * 4) + (row.sel_high_2b * 2)) + row.sel_high_b))
      step := row.step
      width := 1
      value_0 := row.byte_value
      value_1 := 0 }

/-- The elaborated circuit for MemAlignReadByte's `main` — 4 `assertZero`
    constraints + the bus push, no fresh witnesses (`localLength = 0`,
    `unit` output). Lives here (next to `main`) rather than in
    `Circuit.lean` so the completeness axiom (`Completeness.lean`, whose
    type mentions this) can be declared without an import cycle. -/
@[reducible] def memAlignReadByteElaborated :
    ElaboratedCircuit FGL MemAlignReadByteRow unit where
  name := "MemAlignReadByte"
  main := main
  localLength _ := 0
  output _ _ := ()
  channelsWithRequirements := [MemAlignBusChannel.toRaw]

end ZiskFv.AirsClean.MemAlignReadByte
