import ZiskFv.AirsClean.MemAlignReadByte.Spec
import ZiskFv.AirsClean.RangeTables
import Clean.Circuit.Basic
import ZiskFv.Channels.MemoryBus

/-!
# MemAlignReadByte circuit operations (the `main` field of the Component)

The constraint emissions of ZisK's MemAlignReadByte AIR, expressed as a Clean
circuit do-block: one `assertZero` per F-only pilout constraint,
then the unified memory bus `MemBusChannel.push`.

AUTO-GENERATED by `tools/pil-extract` (`clean-component` subcommand) —
do not hand-edit. The bus push is reconstructed from the
proves-side `gsum_debug_data` hint and is slot-for-slot faithful to
the hand-written reference.

## Trust note

No axioms. Pure operational declaration.
-/

namespace ZiskFv.AirsClean.MemAlignReadByte

open Goldilocks
open Circuit (assertZero lookup)
open ZiskFv.AirsClean.RangeTables
open ZiskFv.Channels.MemoryBus (MemBusChannel MemBusMessage)

@[reducible]
def memBusMessageExpr (row : Var MemAlignReadByteRow FGL) :
    MemBusMessage (Expression FGL) :=
  { mem_op := 1
    ptr := ((row.addr_w * 8) + (((row.sel_high_4b * 4) + (row.sel_high_2b * 2)) + row.sel_high_b))
    timestamp := row.step
    width := 1
    value_0 := row.byte_value
    value_1 := 0 }

/-- The 4 F-constraints and memory bus push, taking the row's slot
    values as `Expression FGL`s. Returns `Unit` (MemAlignReadByte is a pure
    assertion — no fresh witnesses introduced inside the circuit). -/
@[circuit_norm]
def main (row : Var MemAlignReadByteRow FGL) : Circuit FGL Unit := do
  -- range lookup for the byte value bits declaration
  lookup (Table.fromStatic rangeTable8) row.byte_value
  -- constraint 0 (mem/pil/mem_align_byte.pil:35)
  assertZero (row.sel_high_4b * (1 - row.sel_high_4b))
  -- constraint 1 (mem/pil/mem_align_byte.pil:36)
  assertZero (row.sel_high_2b * (1 - row.sel_high_2b))
  -- constraint 2 (mem/pil/mem_align_byte.pil:37)
  assertZero (row.sel_high_b * (1 - row.sel_high_b))
  -- constraint 3 (mem/pil/mem_align_byte.pil:59)
  assertZero (row.composed_value - (((row.byte_value * (((((16777216 * row.sel_high_2b) * row.sel_high_b) + ((65536 * row.sel_high_2b) * (1 - row.sel_high_b))) + ((256 * (1 - row.sel_high_2b)) * row.sel_high_b)) + ((1 - row.sel_high_2b) * (1 - row.sel_high_b)))) + (row.value_8b * (((((16777216 * row.sel_high_2b) * (1 - row.sel_high_b)) + ((65536 * row.sel_high_2b) * row.sel_high_b)) + ((256 * (1 - row.sel_high_2b)) * (1 - row.sel_high_b))) + ((1 - row.sel_high_2b) * row.sel_high_b)))) + (row.value_16b * ((65536 * (1 - row.sel_high_2b)) + row.sel_high_2b))))
  -- Bus emission: MemAlignReadByte pushes its proves-side tuple onto memory bus 10.
  -- Reconstructed from the proves-side `gsum_debug_data` hint;
  -- slot-for-slot faithful to the hand-written reference.
  MemBusChannel.push (memBusMessageExpr row)

/-- The elaborated circuit for MemAlignReadByte's `main` — 4 `assertZero`
    constraints + the bus push, no fresh witnesses (`localLength = 0`,
    `unit` output). Lives here (next to `main`) rather than in
    `Circuit.lean` so the conditional completeness proof can name it
    without an import cycle. -/
@[reducible] def memAlignReadByteElaborated : ElaboratedCircuit FGL MemAlignReadByteRow unit where
  name := "MemAlignReadByte"
  main := main
  localLength _ := 0
  output _ _ := ()
  channelsWithRequirements := [MemBusChannel.toRaw]
  exposedChannels row _ :=
    expose MemBusChannel [MemBusChannel.pushed (memBusMessageExpr row)]
  channelsLawful := by
    simp only [circuit_norm, main, memBusMessageExpr, MemBusChannel]

end ZiskFv.AirsClean.MemAlignReadByte
