import Clean.Circuit.Channel
import Clean.Circuit.Provable
import Clean.Utils.Tactics.ProvableStructDeriving
import ZiskFv.Field.Goldilocks

/-!
# MemAlignReadByte row type (Clean ProvableStruct)

The stage-1 witness row layout for ZisK's MemAlignReadByte AIR, expressed as a
`ProvableStruct` for consumption by a Clean `GeneralFormalCircuit`.

AUTO-GENERATED by `tools/pil-extract` (`clean-component` subcommand)
from `build/zisk.pilout` — do not hand-edit.

Stage-1 columns (one struct field each):

* `sel_high_4b` — pilout column 0 (`sel_high_4b`)
* `sel_high_2b` — pilout column 1 (`sel_high_2b`)
* `sel_high_b` — pilout column 2 (`sel_high_b`)
* `direct_value` — pilout column 3 (`direct_value`)
* `composed_value` — pilout column 4 (`composed_value`)
* `value_16b` — pilout column 5 (`value_16b`)
* `value_8b` — pilout column 6 (`value_8b`)
* `byte_value` — pilout column 7 (`byte_value`)
* `addr_w` — pilout column 8 (`addr_w`)
* `step` — pilout column 9 (`step`)

Stage-2 columns (`gsum`, `im_cluster`, `im_single`) are omitted: they are the permutation
accumulators / intermediates, which Clean's channel-balance
machinery subsumes. The row here is the witness-only slice the
Clean Component constrains directly.

## Trust note

No axiom added — this is a pure data definition.
-/

namespace ZiskFv.AirsClean.MemAlignReadByte

open Goldilocks

/-- The 10-column stage-1 witness row for MemAlignReadByte. -/
structure MemAlignReadByteRow (F : Type) where
  sel_high_4b : F
  sel_high_2b : F
  sel_high_b : F
  direct_value : F
  composed_value : F
  value_16b : F
  value_8b : F
  byte_value : F
  addr_w : F
  step : F
deriving ProvableStruct

end ZiskFv.AirsClean.MemAlignReadByte
