-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zisk_core]
import Aeneas.Std.Primitives
import Aeneas.Std.Array
import Aeneas.Std.Core.Default
import Aeneas.Std.Scalar
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace zisk_core

/-- [zisk_core::rv64im_transpiler::OP_FLAG]
    Source: 'core/src/rv64im_transpiler.rs', lines 13:0-13:26 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_FLAG : Std.U64 := 0#u64

/-- [zisk_core::rv64im_transpiler::OP_COPYB]
    Source: 'core/src/rv64im_transpiler.rs', lines 14:0-14:27 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_COPYB : Std.U64 := 1#u64

/-- [zisk_core::rv64im_transpiler::OP_LTU]
    Source: 'core/src/rv64im_transpiler.rs', lines 15:0-15:25 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_LTU : Std.U64 := 6#u64

/-- [zisk_core::rv64im_transpiler::OP_LT]
    Source: 'core/src/rv64im_transpiler.rs', lines 16:0-16:24 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_LT : Std.U64 := 7#u64

/-- [zisk_core::rv64im_transpiler::OP_EQ]
    Source: 'core/src/rv64im_transpiler.rs', lines 17:0-17:24 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_EQ : Std.U64 := 9#u64

/-- [zisk_core::rv64im_transpiler::OP_ADD]
    Source: 'core/src/rv64im_transpiler.rs', lines 18:0-18:25 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_ADD : Std.U64 := 10#u64

/-- [zisk_core::rv64im_transpiler::OP_SUB]
    Source: 'core/src/rv64im_transpiler.rs', lines 19:0-19:25 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_SUB : Std.U64 := 11#u64

/-- [zisk_core::rv64im_transpiler::OP_AND]
    Source: 'core/src/rv64im_transpiler.rs', lines 20:0-20:25 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_AND : Std.U64 := 14#u64

/-- [zisk_core::rv64im_transpiler::OP_OR]
    Source: 'core/src/rv64im_transpiler.rs', lines 21:0-21:24 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_OR : Std.U64 := 15#u64

/-- [zisk_core::rv64im_transpiler::OP_XOR]
    Source: 'core/src/rv64im_transpiler.rs', lines 22:0-22:25 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_XOR : Std.U64 := 16#u64

/-- [zisk_core::rv64im_transpiler::OP_ADD_W]
    Source: 'core/src/rv64im_transpiler.rs', lines 23:0-23:27 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_ADD_W : Std.U64 := 26#u64

/-- [zisk_core::rv64im_transpiler::OP_SUB_W]
    Source: 'core/src/rv64im_transpiler.rs', lines 24:0-24:27 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_SUB_W : Std.U64 := 27#u64

/-- [zisk_core::rv64im_transpiler::OP_SLL]
    Source: 'core/src/rv64im_transpiler.rs', lines 25:0-25:25 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_SLL : Std.U64 := 33#u64

/-- [zisk_core::rv64im_transpiler::OP_SRL]
    Source: 'core/src/rv64im_transpiler.rs', lines 26:0-26:25 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_SRL : Std.U64 := 34#u64

/-- [zisk_core::rv64im_transpiler::OP_SRA]
    Source: 'core/src/rv64im_transpiler.rs', lines 27:0-27:25 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_SRA : Std.U64 := 35#u64

/-- [zisk_core::rv64im_transpiler::OP_SLL_W]
    Source: 'core/src/rv64im_transpiler.rs', lines 28:0-28:27 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_SLL_W : Std.U64 := 36#u64

/-- [zisk_core::rv64im_transpiler::OP_SRL_W]
    Source: 'core/src/rv64im_transpiler.rs', lines 29:0-29:27 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_SRL_W : Std.U64 := 37#u64

/-- [zisk_core::rv64im_transpiler::OP_SRA_W]
    Source: 'core/src/rv64im_transpiler.rs', lines 30:0-30:27 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_SRA_W : Std.U64 := 38#u64

/-- [zisk_core::rv64im_transpiler::OP_SIGNEXT_B]
    Source: 'core/src/rv64im_transpiler.rs', lines 31:0-31:31 -/
@[global_simps, irreducible]
def rv64im_transpiler.OP_SIGNEXT_B : Std.U64 := 39#u64

/-- [zisk_core::rv64im_transpiler::OP_SIGNEXT_H]
    Source: 'core/src/rv64im_transpiler.rs', lines 32:0-32:31 -/
@[global_simps, irreducible]
def rv64im_transpiler.OP_SIGNEXT_H : Std.U64 := 40#u64

/-- [zisk_core::rv64im_transpiler::OP_SIGNEXT_W]
    Source: 'core/src/rv64im_transpiler.rs', lines 33:0-33:31 -/
@[global_simps, irreducible]
def rv64im_transpiler.OP_SIGNEXT_W : Std.U64 := 41#u64

/-- [zisk_core::rv64im_transpiler::OP_MULHU]
    Source: 'core/src/rv64im_transpiler.rs', lines 34:0-34:27 -/
@[global_simps, irreducible]
def rv64im_transpiler.OP_MULHU : Std.U64 := 177#u64

/-- [zisk_core::rv64im_transpiler::OP_MULHSU]
    Source: 'core/src/rv64im_transpiler.rs', lines 35:0-35:28 -/
@[global_simps, irreducible]
def rv64im_transpiler.OP_MULHSU : Std.U64 := 179#u64

/-- [zisk_core::rv64im_transpiler::OP_MUL]
    Source: 'core/src/rv64im_transpiler.rs', lines 36:0-36:25 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_MUL : Std.U64 := 180#u64

/-- [zisk_core::rv64im_transpiler::OP_MULH]
    Source: 'core/src/rv64im_transpiler.rs', lines 37:0-37:26 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_MULH : Std.U64 := 181#u64

/-- [zisk_core::rv64im_transpiler::OP_MUL_W]
    Source: 'core/src/rv64im_transpiler.rs', lines 38:0-38:27 -/
@[global_simps, irreducible]
def rv64im_transpiler.OP_MUL_W : Std.U64 := 182#u64

/-- [zisk_core::rv64im_transpiler::OP_DIVU]
    Source: 'core/src/rv64im_transpiler.rs', lines 39:0-39:26 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_DIVU : Std.U64 := 184#u64

/-- [zisk_core::rv64im_transpiler::OP_REMU]
    Source: 'core/src/rv64im_transpiler.rs', lines 40:0-40:26 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_REMU : Std.U64 := 185#u64

/-- [zisk_core::rv64im_transpiler::OP_DIV]
    Source: 'core/src/rv64im_transpiler.rs', lines 41:0-41:25 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_DIV : Std.U64 := 186#u64

/-- [zisk_core::rv64im_transpiler::OP_REM]
    Source: 'core/src/rv64im_transpiler.rs', lines 42:0-42:25 -/
@[global_simps, irreducible] def rv64im_transpiler.OP_REM : Std.U64 := 187#u64

/-- [zisk_core::rv64im_transpiler::OP_DIVU_W]
    Source: 'core/src/rv64im_transpiler.rs', lines 43:0-43:28 -/
@[global_simps, irreducible]
def rv64im_transpiler.OP_DIVU_W : Std.U64 := 188#u64

/-- [zisk_core::rv64im_transpiler::OP_REMU_W]
    Source: 'core/src/rv64im_transpiler.rs', lines 44:0-44:28 -/
@[global_simps, irreducible]
def rv64im_transpiler.OP_REMU_W : Std.U64 := 189#u64

/-- [zisk_core::rv64im_transpiler::OP_DIV_W]
    Source: 'core/src/rv64im_transpiler.rs', lines 45:0-45:27 -/
@[global_simps, irreducible]
def rv64im_transpiler.OP_DIV_W : Std.U64 := 190#u64

/-- [zisk_core::rv64im_transpiler::OP_REM_W]
    Source: 'core/src/rv64im_transpiler.rs', lines 46:0-46:27 -/
@[global_simps, irreducible]
def rv64im_transpiler.OP_REM_W : Std.U64 := 191#u64

/-- [zisk_core::rv64im_transpiler::Rv64imOp]
    Source: 'core/src/rv64im_transpiler.rs', lines 49:0-113:1
    Visibility: public -/
inductive rv64im_transpiler.Rv64imOp where
| Add : rv64im_transpiler.Rv64imOp
| Sub : rv64im_transpiler.Rv64imOp
| Sll : rv64im_transpiler.Rv64imOp
| Slt : rv64im_transpiler.Rv64imOp
| Sltu : rv64im_transpiler.Rv64imOp
| Xor : rv64im_transpiler.Rv64imOp
| Srl : rv64im_transpiler.Rv64imOp
| Sra : rv64im_transpiler.Rv64imOp
| Or : rv64im_transpiler.Rv64imOp
| And : rv64im_transpiler.Rv64imOp
| Addw : rv64im_transpiler.Rv64imOp
| Subw : rv64im_transpiler.Rv64imOp
| Sllw : rv64im_transpiler.Rv64imOp
| Srlw : rv64im_transpiler.Rv64imOp
| Sraw : rv64im_transpiler.Rv64imOp
| Addi : rv64im_transpiler.Rv64imOp
| Slli : rv64im_transpiler.Rv64imOp
| Slti : rv64im_transpiler.Rv64imOp
| Sltiu : rv64im_transpiler.Rv64imOp
| Xori : rv64im_transpiler.Rv64imOp
| Srli : rv64im_transpiler.Rv64imOp
| Srai : rv64im_transpiler.Rv64imOp
| Ori : rv64im_transpiler.Rv64imOp
| Andi : rv64im_transpiler.Rv64imOp
| Addiw : rv64im_transpiler.Rv64imOp
| Slliw : rv64im_transpiler.Rv64imOp
| Srliw : rv64im_transpiler.Rv64imOp
| Sraiw : rv64im_transpiler.Rv64imOp
| Beq : rv64im_transpiler.Rv64imOp
| Bne : rv64im_transpiler.Rv64imOp
| Blt : rv64im_transpiler.Rv64imOp
| Bge : rv64im_transpiler.Rv64imOp
| Bltu : rv64im_transpiler.Rv64imOp
| Bgeu : rv64im_transpiler.Rv64imOp
| Lb : rv64im_transpiler.Rv64imOp
| Lbu : rv64im_transpiler.Rv64imOp
| Lh : rv64im_transpiler.Rv64imOp
| Lhu : rv64im_transpiler.Rv64imOp
| Lw : rv64im_transpiler.Rv64imOp
| Lwu : rv64im_transpiler.Rv64imOp
| Ld : rv64im_transpiler.Rv64imOp
| Sb : rv64im_transpiler.Rv64imOp
| Sh : rv64im_transpiler.Rv64imOp
| Sw : rv64im_transpiler.Rv64imOp
| Sd : rv64im_transpiler.Rv64imOp
| Lui : rv64im_transpiler.Rv64imOp
| Auipc : rv64im_transpiler.Rv64imOp
| Jal : rv64im_transpiler.Rv64imOp
| Jalr : rv64im_transpiler.Rv64imOp
| Fence : rv64im_transpiler.Rv64imOp
| Mul : rv64im_transpiler.Rv64imOp
| Mulh : rv64im_transpiler.Rv64imOp
| Mulhsu : rv64im_transpiler.Rv64imOp
| Mulhu : rv64im_transpiler.Rv64imOp
| Mulw : rv64im_transpiler.Rv64imOp
| Div : rv64im_transpiler.Rv64imOp
| Divu : rv64im_transpiler.Rv64imOp
| Divw : rv64im_transpiler.Rv64imOp
| Divuw : rv64im_transpiler.Rv64imOp
| Rem : rv64im_transpiler.Rv64imOp
| Remu : rv64im_transpiler.Rv64imOp
| Remw : rv64im_transpiler.Rv64imOp
| Remuw : rv64im_transpiler.Rv64imOp

/-- [zisk_core::rv64im_transpiler::Rv64imInst]
    Source: 'core/src/rv64im_transpiler.rs', lines 116:0-123:1
    Visibility: public -/
structure rv64im_transpiler.Rv64imInst where
  paddr : Std.U64
  op : rv64im_transpiler.Rv64imOp
  rd : Std.U32
  rs1 : Std.U32
  rs2 : Std.U32
  imm : Std.I32

/-- [zisk_core::rv64im_transpiler::StaticRow]
    Source: 'core/src/rv64im_transpiler.rs', lines 126:0-144:1
    Visibility: public -/
structure rv64im_transpiler.StaticRow where
  paddr : Std.U64
  op : Std.U64
  a_src : Std.U64
  a_use_sp_imm1 : Std.U64
  a_offset_imm0 : Std.U64
  b_src : Std.U64
  b_use_sp_imm1 : Std.U64
  b_offset_imm0 : Std.U64
  store : Std.U64
  store_offset : Std.I64
  store_pc : Bool
  set_pc : Bool
  ind_width : Std.U64
  jmp_offset1 : Std.I64
  jmp_offset2 : Std.I64
  is_external_op : Bool
  m32 : Bool

/-- [zisk_core::rv64im_transpiler::{impl core::default::Default for zisk_core::rv64im_transpiler::StaticRow}::default]:
    Source: 'core/src/rv64im_transpiler.rs', lines 125:29-125:36
    Visibility: public -/
def rv64im_transpiler.StaticRow.Insts.CoreDefaultDefault.default
  : Result rv64im_transpiler.StaticRow := do
  let b ← core.default.DefaultBool.default
  ok
    {
      paddr := (core.default.DefaultU64.default),
      op := (core.default.DefaultU64.default),
      a_src := (core.default.DefaultU64.default),
      a_use_sp_imm1 := (core.default.DefaultU64.default),
      a_offset_imm0 := (core.default.DefaultU64.default),
      b_src := (core.default.DefaultU64.default),
      b_use_sp_imm1 := (core.default.DefaultU64.default),
      b_offset_imm0 := (core.default.DefaultU64.default),
      store := (core.default.DefaultU64.default),
      store_offset := (core.default.DefaultI64.default),
      store_pc := b,
      set_pc := b,
      ind_width := (core.default.DefaultU64.default),
      jmp_offset1 := (core.default.DefaultI64.default),
      jmp_offset2 := (core.default.DefaultI64.default),
      is_external_op := b,
      m32 := b
    }

/-- [zisk_core::rv64im_transpiler::StaticRows]
    Source: 'core/src/rv64im_transpiler.rs', lines 147:0-150:1
    Visibility: public -/
structure rv64im_transpiler.StaticRows where
  rows : Array rv64im_transpiler.StaticRow 2#usize
  len : Std.Usize

/-- [zisk_core::rv64im_transpiler::{zisk_core::rv64im_transpiler::StaticRows}::one]:
    Source: 'core/src/rv64im_transpiler.rs', lines 153:4-155:5 -/
def rv64im_transpiler.StaticRows.one
  (row : rv64im_transpiler.StaticRow) :
  Result rv64im_transpiler.StaticRows
  := do
  let sr ← rv64im_transpiler.StaticRow.Insts.CoreDefaultDefault.default
  ok { rows := (Array.make 2#usize [ row, sr ]), len := 1#usize }

/-- [zisk_core::rv64im_transpiler::{zisk_core::rv64im_transpiler::StaticRows}::two]:
    Source: 'core/src/rv64im_transpiler.rs', lines 157:4-159:5 -/
def rv64im_transpiler.StaticRows.two
  (first : rv64im_transpiler.StaticRow) (second : rv64im_transpiler.StaticRow)
  :
  Result rv64im_transpiler.StaticRows
  := do
  ok { rows := (Array.make 2#usize [ first, second ]), len := 2#usize }

/-- [zisk_core::rv64im_transpiler::decoded_registers]:
    Source: 'core/src/rv64im_transpiler.rs', lines 544:0-581:1 -/
def rv64im_transpiler.decoded_registers
  (op : rv64im_transpiler.Rv64imOp) (rd : Std.U32) (rs1 : Std.U32)
  (rs2 : Std.U32) :
  Result (Std.U32 × Std.U32 × Std.U32)
  := do
  match op with
  | rv64im_transpiler.Rv64imOp.Add => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Sub => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Sll => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Slt => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Sltu => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Xor => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Srl => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Sra => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Or => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.And => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Addw => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Subw => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Sllw => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Srlw => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Sraw => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Addi => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Slli => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Slti => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Sltiu => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Xori => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Srli => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Srai => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Ori => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Andi => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Addiw => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Slliw => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Srliw => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Sraiw => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Beq => ok (0#u32, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Bne => ok (0#u32, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Blt => ok (0#u32, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Bge => ok (0#u32, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Bltu => ok (0#u32, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Bgeu => ok (0#u32, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Lb => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Lbu => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Lh => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Lhu => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Lw => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Lwu => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Ld => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Sb => ok (0#u32, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Sh => ok (0#u32, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Sw => ok (0#u32, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Sd => ok (0#u32, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Lui => ok (rd, 0#u32, 0#u32)
  | rv64im_transpiler.Rv64imOp.Auipc => ok (rd, 0#u32, 0#u32)
  | rv64im_transpiler.Rv64imOp.Jal => ok (rd, 0#u32, 0#u32)
  | rv64im_transpiler.Rv64imOp.Jalr => ok (rd, rs1, 0#u32)
  | rv64im_transpiler.Rv64imOp.Fence => ok (0#u32, 0#u32, 0#u32)
  | rv64im_transpiler.Rv64imOp.Mul => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Mulh => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Mulhsu => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Mulhu => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Mulw => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Div => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Divu => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Divw => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Divuw => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Rem => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Remu => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Remw => ok (rd, rs1, rs2)
  | rv64im_transpiler.Rv64imOp.Remuw => ok (rd, rs1, rs2)

/-- [zisk_core::rv64im_transpiler::signext]:
    Source: 'core/src/rv64im_transpiler.rs', lines 583:0-591:1 -/
def rv64im_transpiler.signext
  (v : Std.U32) (size : Std.U32) : Result Std.I32 := do
  let i ← size - 1#u32
  let sign_bit ← 1#u32 <<< i
  let max_value ← 1#u32 <<< size
  let i1 ← lift (sign_bit &&& v)
  if i1 != 0#u32
  then
    let i2 ← lift (UScalar.hcast .I32 v)
    let i3 ← lift (UScalar.hcast .I32 max_value)
    i2 - i3
  else ok (UScalar.hcast .I32 v)

/-- [zisk_core::rv64im_transpiler::decode_imm]:
    Source: 'core/src/rv64im_transpiler.rs', lines 496:0-542:1 -/
def rv64im_transpiler.decode_imm
  (word : Std.U32) (op : rv64im_transpiler.Rv64imOp) : Result Std.I32 := do
  match op with
  | rv64im_transpiler.Rv64imOp.Add => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Sub => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Sll => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Slt => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Sltu => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Xor => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Srl => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Sra => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Or => ok 0#i32
  | rv64im_transpiler.Rv64imOp.And => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Addw => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Subw => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Sllw => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Srlw => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Sraw => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Addi =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Slli =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 63#u32)
    ok (UScalar.hcast .I32 i1)
  | rv64im_transpiler.Rv64imOp.Slti =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Sltiu =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Xori =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Srli =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 63#u32)
    ok (UScalar.hcast .I32 i1)
  | rv64im_transpiler.Rv64imOp.Srai =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 63#u32)
    ok (UScalar.hcast .I32 i1)
  | rv64im_transpiler.Rv64imOp.Ori =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Andi =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Addiw =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Slliw =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 31#u32)
    ok (UScalar.hcast .I32 i1)
  | rv64im_transpiler.Rv64imOp.Srliw =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 31#u32)
    ok (UScalar.hcast .I32 i1)
  | rv64im_transpiler.Rv64imOp.Sraiw =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 31#u32)
    ok (UScalar.hcast .I32 i1)
  | rv64im_transpiler.Rv64imOp.Beq =>
    let i ← word >>> 7#i32
    let imm11 ← lift (i &&& 1#u32)
    let i1 ← word >>> 8#i32
    let imm4_1 ← lift (i1 &&& 15#u32)
    let i2 ← word >>> 25#i32
    let imm10_5 ← lift (i2 &&& 63#u32)
    let i3 ← word >>> 31#i32
    let imm12 ← lift (i3 &&& 1#u32)
    let i4 ← imm12 <<< 12#i32
    let i5 ← imm11 <<< 11#i32
    let i6 ← lift (i4 ||| i5)
    let i7 ← imm10_5 <<< 5#i32
    let i8 ← lift (i6 ||| i7)
    let i9 ← imm4_1 <<< 1#i32
    let i10 ← lift (i8 ||| i9)
    rv64im_transpiler.signext i10 13#u32
  | rv64im_transpiler.Rv64imOp.Bne =>
    let i ← word >>> 7#i32
    let imm11 ← lift (i &&& 1#u32)
    let i1 ← word >>> 8#i32
    let imm4_1 ← lift (i1 &&& 15#u32)
    let i2 ← word >>> 25#i32
    let imm10_5 ← lift (i2 &&& 63#u32)
    let i3 ← word >>> 31#i32
    let imm12 ← lift (i3 &&& 1#u32)
    let i4 ← imm12 <<< 12#i32
    let i5 ← imm11 <<< 11#i32
    let i6 ← lift (i4 ||| i5)
    let i7 ← imm10_5 <<< 5#i32
    let i8 ← lift (i6 ||| i7)
    let i9 ← imm4_1 <<< 1#i32
    let i10 ← lift (i8 ||| i9)
    rv64im_transpiler.signext i10 13#u32
  | rv64im_transpiler.Rv64imOp.Blt =>
    let i ← word >>> 7#i32
    let imm11 ← lift (i &&& 1#u32)
    let i1 ← word >>> 8#i32
    let imm4_1 ← lift (i1 &&& 15#u32)
    let i2 ← word >>> 25#i32
    let imm10_5 ← lift (i2 &&& 63#u32)
    let i3 ← word >>> 31#i32
    let imm12 ← lift (i3 &&& 1#u32)
    let i4 ← imm12 <<< 12#i32
    let i5 ← imm11 <<< 11#i32
    let i6 ← lift (i4 ||| i5)
    let i7 ← imm10_5 <<< 5#i32
    let i8 ← lift (i6 ||| i7)
    let i9 ← imm4_1 <<< 1#i32
    let i10 ← lift (i8 ||| i9)
    rv64im_transpiler.signext i10 13#u32
  | rv64im_transpiler.Rv64imOp.Bge =>
    let i ← word >>> 7#i32
    let imm11 ← lift (i &&& 1#u32)
    let i1 ← word >>> 8#i32
    let imm4_1 ← lift (i1 &&& 15#u32)
    let i2 ← word >>> 25#i32
    let imm10_5 ← lift (i2 &&& 63#u32)
    let i3 ← word >>> 31#i32
    let imm12 ← lift (i3 &&& 1#u32)
    let i4 ← imm12 <<< 12#i32
    let i5 ← imm11 <<< 11#i32
    let i6 ← lift (i4 ||| i5)
    let i7 ← imm10_5 <<< 5#i32
    let i8 ← lift (i6 ||| i7)
    let i9 ← imm4_1 <<< 1#i32
    let i10 ← lift (i8 ||| i9)
    rv64im_transpiler.signext i10 13#u32
  | rv64im_transpiler.Rv64imOp.Bltu =>
    let i ← word >>> 7#i32
    let imm11 ← lift (i &&& 1#u32)
    let i1 ← word >>> 8#i32
    let imm4_1 ← lift (i1 &&& 15#u32)
    let i2 ← word >>> 25#i32
    let imm10_5 ← lift (i2 &&& 63#u32)
    let i3 ← word >>> 31#i32
    let imm12 ← lift (i3 &&& 1#u32)
    let i4 ← imm12 <<< 12#i32
    let i5 ← imm11 <<< 11#i32
    let i6 ← lift (i4 ||| i5)
    let i7 ← imm10_5 <<< 5#i32
    let i8 ← lift (i6 ||| i7)
    let i9 ← imm4_1 <<< 1#i32
    let i10 ← lift (i8 ||| i9)
    rv64im_transpiler.signext i10 13#u32
  | rv64im_transpiler.Rv64imOp.Bgeu =>
    let i ← word >>> 7#i32
    let imm11 ← lift (i &&& 1#u32)
    let i1 ← word >>> 8#i32
    let imm4_1 ← lift (i1 &&& 15#u32)
    let i2 ← word >>> 25#i32
    let imm10_5 ← lift (i2 &&& 63#u32)
    let i3 ← word >>> 31#i32
    let imm12 ← lift (i3 &&& 1#u32)
    let i4 ← imm12 <<< 12#i32
    let i5 ← imm11 <<< 11#i32
    let i6 ← lift (i4 ||| i5)
    let i7 ← imm10_5 <<< 5#i32
    let i8 ← lift (i6 ||| i7)
    let i9 ← imm4_1 <<< 1#i32
    let i10 ← lift (i8 ||| i9)
    rv64im_transpiler.signext i10 13#u32
  | rv64im_transpiler.Rv64imOp.Lb =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Lbu =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Lh =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Lhu =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Lw =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Lwu =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Ld =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Sb =>
    let i ← word >>> 7#i32
    let imm4_0 ← lift (i &&& 31#u32)
    let i1 ← word >>> 25#i32
    let imm11_5 ← lift (i1 &&& 127#u32)
    let i2 ← imm11_5 <<< 5#i32
    let i3 ← lift (i2 ||| imm4_0)
    rv64im_transpiler.signext i3 12#u32
  | rv64im_transpiler.Rv64imOp.Sh =>
    let i ← word >>> 7#i32
    let imm4_0 ← lift (i &&& 31#u32)
    let i1 ← word >>> 25#i32
    let imm11_5 ← lift (i1 &&& 127#u32)
    let i2 ← imm11_5 <<< 5#i32
    let i3 ← lift (i2 ||| imm4_0)
    rv64im_transpiler.signext i3 12#u32
  | rv64im_transpiler.Rv64imOp.Sw =>
    let i ← word >>> 7#i32
    let imm4_0 ← lift (i &&& 31#u32)
    let i1 ← word >>> 25#i32
    let imm11_5 ← lift (i1 &&& 127#u32)
    let i2 ← imm11_5 <<< 5#i32
    let i3 ← lift (i2 ||| imm4_0)
    rv64im_transpiler.signext i3 12#u32
  | rv64im_transpiler.Rv64imOp.Sd =>
    let i ← word >>> 7#i32
    let imm4_0 ← lift (i &&& 31#u32)
    let i1 ← word >>> 25#i32
    let imm11_5 ← lift (i1 &&& 127#u32)
    let i2 ← imm11_5 <<< 5#i32
    let i3 ← lift (i2 ||| imm4_0)
    rv64im_transpiler.signext i3 12#u32
  | rv64im_transpiler.Rv64imOp.Lui =>
    let i ← lift (word &&& 4294963200#u32)
    ok (UScalar.hcast .I32 i)
  | rv64im_transpiler.Rv64imOp.Auipc =>
    let i ← lift (word &&& 4294963200#u32)
    ok (UScalar.hcast .I32 i)
  | rv64im_transpiler.Rv64imOp.Jal =>
    let i ← word >>> 31#i32
    let imm20 ← lift (i &&& 1#u32)
    let i1 ← word >>> 21#i32
    let imm10_1 ← lift (i1 &&& 1023#u32)
    let i2 ← word >>> 20#i32
    let imm11 ← lift (i2 &&& 1#u32)
    let i3 ← word >>> 12#i32
    let imm19_12 ← lift (i3 &&& 255#u32)
    let i4 ← imm20 <<< 20#i32
    let i5 ← imm19_12 <<< 12#i32
    let i6 ← lift (i4 ||| i5)
    let i7 ← imm11 <<< 11#i32
    let i8 ← lift (i6 ||| i7)
    let i9 ← imm10_1 <<< 1#i32
    let i10 ← lift (i8 ||| i9)
    rv64im_transpiler.signext i10 21#u32
  | rv64im_transpiler.Rv64imOp.Jalr =>
    let i ← word >>> 20#i32
    let i1 ← lift (i &&& 4095#u32)
    rv64im_transpiler.signext i1 12#u32
  | rv64im_transpiler.Rv64imOp.Fence => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Mul => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Mulh => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Mulhsu => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Mulhu => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Mulw => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Div => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Divu => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Divw => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Divuw => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Rem => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Remu => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Remw => ok 0#i32
  | rv64im_transpiler.Rv64imOp.Remuw => ok 0#i32

/-- [zisk_core::rv64im_transpiler::decode_rv64im32]:
    Source: 'core/src/rv64im_transpiler.rs', lines 166:0-265:1
    Visibility: public -/
def rv64im_transpiler.decode_rv64im32
  (word : Std.U32) (paddr : Std.U64) :
  Result (Option rv64im_transpiler.Rv64imInst)
  := do
  let opcode ← lift (word &&& 127#u32)
  let i ← word >>> 12#i32
  let funct3 ← lift (i &&& 7#u32)
  let i1 ← word >>> 25#i32
  let funct7 ← lift (i1 &&& 127#u32)
  let i2 ← word >>> 7#i32
  let rd ← lift (i2 &&& 31#u32)
  let i3 ← word >>> 15#i32
  let rs1 ← lift (i3 &&& 31#u32)
  let i4 ← word >>> 20#i32
  let rs2 ← lift (i4 &&& 31#u32)
  match opcode with
  | 3#uscalar =>
    match funct3 with
    | 0#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Lb rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Lb
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Lb,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 1#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Lh rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Lh
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Lh,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 2#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Lw rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Lw
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Lw,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 3#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Ld rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Ld
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Ld,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 4#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Lbu rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Lbu
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Lbu,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 5#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Lhu rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Lhu
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Lhu,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 6#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Lwu rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Lwu
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Lwu,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | _ => ok none
  | 15#uscalar =>
    match funct3 with
    | 0#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Fence rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Fence
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Fence,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | _ => ok none
  | 19#uscalar =>
    match funct3 with
    | 0#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Addi rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Addi
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Addi,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 1#uscalar =>
      let i5 ← word >>> 26#i32
      let i6 ← lift (i5 &&& 63#u32)
      if i6 = 0#u32
      then
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Slli
            rd rs1 rs2
        let i7 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Slli
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Slli,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i7
          })
      else ok none
    | 2#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Slti rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Slti
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Slti,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 3#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Sltiu rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Sltiu
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Sltiu,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 4#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Xori rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Xori
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Xori,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 5#uscalar =>
      let i5 ← word >>> 26#i32
      let i6 ← lift (i5 &&& 63#u32)
      if i6 = 0#u32
      then
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Srli
            rd rs1 rs2
        let i7 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Srli
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Srli,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i7
          })
      else
        let i7 ← lift (i5 &&& 63#u32)
        if i7 = 16#u32
        then
          let (rd1, rs11, rs21) ←
            rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Srai
              rd rs1 rs2
          let i8 ←
            rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Srai
          ok (some
            {
              paddr,
              op := rv64im_transpiler.Rv64imOp.Srai,
              rd := rd1,
              rs1 := rs11,
              rs2 := rs21,
              imm := i8
            })
        else ok none
    | 6#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Ori rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Ori
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Ori,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 7#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Andi rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Andi
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Andi,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | _ => ok none
  | 23#uscalar =>
    let (rd1, rs11, rs21) ←
      rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Auipc rd
        rs1 rs2
    let i5 ←
      rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Auipc
    ok (some
      {
        paddr,
        op := rv64im_transpiler.Rv64imOp.Auipc,
        rd := rd1,
        rs1 := rs11,
        rs2 := rs21,
        imm := i5
      })
  | 27#uscalar =>
    match funct3 with
    | 0#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Addiw rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Addiw
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Addiw,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 1#uscalar =>
      if funct7 = 0#u32
      then
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Slliw
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Slliw
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Slliw,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      else ok none
    | 5#uscalar =>
      if funct7 = 0#u32
      then
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Srliw
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Srliw
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Srliw,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      else
        if funct7 = 32#u32
        then
          let (rd1, rs11, rs21) ←
            rv64im_transpiler.decoded_registers
              rv64im_transpiler.Rv64imOp.Sraiw rd rs1 rs2
          let i5 ←
            rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Sraiw
          ok (some
            {
              paddr,
              op := rv64im_transpiler.Rv64imOp.Sraiw,
              rd := rd1,
              rs1 := rs11,
              rs2 := rs21,
              imm := i5
            })
        else ok none
    | _ => ok none
  | 35#uscalar =>
    match funct3 with
    | 0#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Sb rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Sb
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Sb,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 1#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Sh rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Sh
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Sh,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 2#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Sw rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Sw
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Sw,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 3#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Sd rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Sd
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Sd,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | _ => ok none
  | 51#uscalar =>
    match funct3 with
    | 0#uscalar =>
      match funct7 with
      | 0#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Add rd
            rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Add
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Add,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Mul rd
            rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Mul
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Mul,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 32#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Sub rd
            rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Sub
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Sub,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | 1#uscalar =>
      match funct7 with
      | 0#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Sll rd
            rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Sll
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Sll,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Mulh
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Mulh
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Mulh,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | 2#uscalar =>
      match funct7 with
      | 0#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Slt rd
            rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Slt
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Slt,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Mulhsu
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Mulhsu
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Mulhsu,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | 3#uscalar =>
      match funct7 with
      | 0#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Sltu
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Sltu
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Sltu,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Mulhu
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Mulhu
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Mulhu,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | 4#uscalar =>
      match funct7 with
      | 0#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Xor rd
            rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Xor
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Xor,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Div rd
            rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Div
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Div,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | 5#uscalar =>
      match funct7 with
      | 0#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Srl rd
            rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Srl
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Srl,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Divu
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Divu
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Divu,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 32#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Sra rd
            rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Sra
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Sra,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | 6#uscalar =>
      match funct7 with
      | 0#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Or rd
            rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Or
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Or,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Rem rd
            rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Rem
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Rem,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | 7#uscalar =>
      match funct7 with
      | 0#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.And rd
            rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.And
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.And,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Remu
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Remu
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Remu,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | _ => ok none
  | 55#uscalar =>
    let (rd1, rs11, rs21) ←
      rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Lui rd rs1
        rs2
    let i5 ← rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Lui
    ok (some
      {
        paddr,
        op := rv64im_transpiler.Rv64imOp.Lui,
        rd := rd1,
        rs1 := rs11,
        rs2 := rs21,
        imm := i5
      })
  | 59#uscalar =>
    match funct3 with
    | 0#uscalar =>
      match funct7 with
      | 0#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Addw
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Addw
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Addw,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Mulw
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Mulw
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Mulw,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 32#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Subw
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Subw
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Subw,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | 1#uscalar =>
      match funct7 with
      | 0#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Sllw
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Sllw
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Sllw,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | 4#uscalar =>
      match funct7 with
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Divw
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Divw
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Divw,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | 5#uscalar =>
      match funct7 with
      | 0#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Srlw
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Srlw
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Srlw,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Divuw
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Divuw
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Divuw,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | 32#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Sraw
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Sraw
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Sraw,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | 6#uscalar =>
      match funct7 with
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Remw
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Remw
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Remw,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | 7#uscalar =>
      match funct7 with
      | 1#uscalar =>
        let (rd1, rs11, rs21) ←
          rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Remuw
            rd rs1 rs2
        let i5 ←
          rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Remuw
        ok (some
          {
            paddr,
            op := rv64im_transpiler.Rv64imOp.Remuw,
            rd := rd1,
            rs1 := rs11,
            rs2 := rs21,
            imm := i5
          })
      | _ => ok none
    | _ => ok none
  | 99#uscalar =>
    match funct3 with
    | 0#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Beq rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Beq
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Beq,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 1#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Bne rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Bne
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Bne,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 4#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Blt rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Blt
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Blt,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 5#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Bge rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Bge
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Bge,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 6#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Bltu rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Bltu
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Bltu,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | 7#uscalar =>
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Bgeu rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Bgeu
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Bgeu,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    | _ => ok none
  | 103#uscalar =>
    if funct3 = 0#u32
    then
      let (rd1, rs11, rs21) ←
        rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Jalr rd
          rs1 rs2
      let i5 ←
        rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Jalr
      ok (some
        {
          paddr,
          op := rv64im_transpiler.Rv64imOp.Jalr,
          rd := rd1,
          rs1 := rs11,
          rs2 := rs21,
          imm := i5
        })
    else ok none
  | 111#uscalar =>
    let (rd1, rs11, rs21) ←
      rv64im_transpiler.decoded_registers rv64im_transpiler.Rv64imOp.Jal rd rs1
        rs2
    let i5 ← rv64im_transpiler.decode_imm word rv64im_transpiler.Rv64imOp.Jal
    ok (some
      {
        paddr,
        op := rv64im_transpiler.Rv64imOp.Jal,
        rd := rd1,
        rs1 := rs11,
        rs2 := rs21,
        imm := i5
      })
  | _ => ok none

/-- [zisk_core::rv64im_transpiler::set_j]:
    Source: 'core/src/rv64im_transpiler.rs', lines 661:0-665:1 -/
def rv64im_transpiler.set_j
  (r : rv64im_transpiler.StaticRow) (j1 : Std.I64) (j2 : Std.I64) :
  Result rv64im_transpiler.StaticRow
  := do
  ok { r with jmp_offset1 := j1, jmp_offset2 := j2 }

/-- [zisk_core::rv64im_transpiler::set_b]:
    Source: 'core/src/rv64im_transpiler.rs', lines 647:0-652:1 -/
def rv64im_transpiler.set_b
  (r : rv64im_transpiler.StaticRow) (source : (Std.U64 × Std.U64 × Std.U64))
  :
  Result rv64im_transpiler.StaticRow
  := do
  let (i, i1, i2) := source
  ok { r with b_src := i, b_use_sp_imm1 := i1, b_offset_imm0 := i2 }

/-- [zisk_core::rv64im_transpiler::set_a]:
    Source: 'core/src/rv64im_transpiler.rs', lines 640:0-645:1 -/
def rv64im_transpiler.set_a
  (r : rv64im_transpiler.StaticRow) (source : (Std.U64 × Std.U64 × Std.U64))
  :
  Result rv64im_transpiler.StaticRow
  := do
  let (i, i1, i2) := source
  ok { r with a_src := i, a_use_sp_imm1 := i1, a_offset_imm0 := i2 }

/-- [zisk_core::zisk_inst::SRC_IMM]
    Source: 'core/src/zisk_inst.rs', lines 45:0-45:27
    Visibility: public -/
@[global_simps, irreducible] def zisk_inst.SRC_IMM : Std.U64 := 2#u64

/-- [zisk_core::rv64im_transpiler::source_imm]:
    Source: 'core/src/rv64im_transpiler.rs', lines 624:0-626:1 -/
def rv64im_transpiler.source_imm
  (v : Std.U64) : Result (Std.U64 × Std.U64 × Std.U64) := do
  let i ← v >>> 32#i32
  let i1 ← lift (i &&& 4294967295#u64)
  let i2 ← lift (v &&& 4294967295#u64)
  ok (zisk_inst.SRC_IMM, i1, i2)

/-- [zisk_core::rv64im_transpiler::row]:
    Source: 'core/src/rv64im_transpiler.rs', lines 593:0-614:1 -/
def rv64im_transpiler.row
  (paddr : Std.U64) (op : Std.U64) : Result rv64im_transpiler.StaticRow := do
  let b ←
    if op != rv64im_transpiler.OP_FLAG
    then ok (op != rv64im_transpiler.OP_COPYB)
    else ok false
  let b1 ←
    match op with
    | 26#uscalar => ok true
    | 27#uscalar => ok true
    | 36#uscalar => ok true
    | 37#uscalar => ok true
    | 38#uscalar => ok true
    | 41#uscalar => ok true
    | 182#uscalar => ok true
    | 188#uscalar => ok true
    | 189#uscalar => ok true
    | 190#uscalar => ok true
    | 191#uscalar => ok true
    | _ => ok false
  let sr ← rv64im_transpiler.StaticRow.Insts.CoreDefaultDefault.default
  ok { sr with paddr, op, is_external_op := b, m32 := b1 }

/-- [zisk_core::rv64im_transpiler::nop]:
    Source: 'core/src/rv64im_transpiler.rs', lines 838:0-841:1 -/
def rv64im_transpiler.nop
  (inst : rv64im_transpiler.Rv64imInst) :
  Result rv64im_transpiler.StaticRows
  := do
  let sr ← rv64im_transpiler.row inst.paddr rv64im_transpiler.OP_FLAG
  let t ← rv64im_transpiler.source_imm 0#u64
  let sr1 ← rv64im_transpiler.set_a sr t
  let sr2 ← rv64im_transpiler.set_b sr1 t
  let r ← rv64im_transpiler.set_j sr2 4#i64 4#i64
  rv64im_transpiler.StaticRows.one r

/-- [zisk_core::zisk_inst::SRC_REG]
    Source: 'core/src/zisk_inst.rs', lines 53:0-53:27
    Visibility: public -/
@[global_simps, irreducible] def zisk_inst.SRC_REG : Std.U64 := 6#u64

/-- [zisk_core::rv64im_transpiler::source_reg]:
    Source: 'core/src/rv64im_transpiler.rs', lines 616:0-622:1 -/
def rv64im_transpiler.source_reg
  (r : Std.U32) : Result (Std.U64 × Std.U64 × Std.U64) := do
  if r = 0#u32
  then ok (zisk_inst.SRC_IMM, 0#u64, 0#u64)
  else let i ← lift (UScalar.cast .U64 r)
       ok (zisk_inst.SRC_REG, 0#u64, i)

/-- [zisk_core::rv64im_transpiler::hint]:
    Source: 'core/src/rv64im_transpiler.rs', lines 829:0-836:1 -/
def rv64im_transpiler.hint
  (inst : rv64im_transpiler.Rv64imInst) :
  Result rv64im_transpiler.StaticRows
  := do
  let sr ← rv64im_transpiler.row inst.paddr rv64im_transpiler.OP_FLAG
  let t ← rv64im_transpiler.source_reg inst.rs1
  let sr1 ← rv64im_transpiler.set_a sr t
  let i ← lift (IScalar.hcast .U64 inst.imm)
  let t1 ← rv64im_transpiler.source_imm i
  let sr2 ← rv64im_transpiler.set_b sr1 t1
  let r ← rv64im_transpiler.set_j sr2 4#i64 4#i64
  rv64im_transpiler.StaticRows.one r

/-- [zisk_core::zisk_inst::SRC_C]
    Source: 'core/src/zisk_inst.rs', lines 41:0-41:25
    Visibility: public -/
@[global_simps, irreducible] def zisk_inst.SRC_C : Std.U64 := 0#u64

/-- [zisk_core::rv64im_transpiler::jalr::JALR_MASK]
    Source: 'core/src/rv64im_transpiler.rs', lines 795:4-795:49 -/
@[global_simps, irreducible]
def rv64im_transpiler.jalr.JALR_MASK : Std.U64 := 18446744073709551614#u64

/-- [zisk_core::rv64im_transpiler::set_store]:
    Source: 'core/src/rv64im_transpiler.rs', lines 654:0-659:1 -/
def rv64im_transpiler.set_store
  (r : rv64im_transpiler.StaticRow) (store : (Std.U64 × Std.I64 × Bool)) :
  Result rv64im_transpiler.StaticRow
  := do
  let (i, i1, b) := store
  ok { r with store := i, store_offset := i1, store_pc := b }

/-- [zisk_core::zisk_inst::STORE_REG]
    Source: 'core/src/zisk_inst.rs', lines 62:0-62:29
    Visibility: public -/
@[global_simps, irreducible] def zisk_inst.STORE_REG : Std.U64 := 3#u64

/-- [zisk_core::zisk_inst::STORE_NONE]
    Source: 'core/src/zisk_inst.rs', lines 56:0-56:30
    Visibility: public -/
@[global_simps, irreducible] def zisk_inst.STORE_NONE : Std.U64 := 0#u64

/-- [zisk_core::rv64im_transpiler::store_reg]:
    Source: 'core/src/rv64im_transpiler.rs', lines 632:0-638:1 -/
def rv64im_transpiler.store_reg
  (r : Std.U32) (store_pc : Bool) : Result (Std.U64 × Std.I64 × Bool) := do
  if r = 0#u32
  then ok (zisk_inst.STORE_NONE, 0#i64, false)
  else
    let i ← lift (UScalar.hcast .I64 r)
    ok (zisk_inst.STORE_REG, i, store_pc)

/-- [zisk_core::rv64im_transpiler::jalr]:
    Source: 'core/src/rv64im_transpiler.rs', lines 794:0-827:1 -/
def rv64im_transpiler.jalr
  (inst : rv64im_transpiler.Rv64imInst) :
  Result rv64im_transpiler.StaticRows
  := do
  let i ← inst.imm % 4#i32
  if i = 0#i32
  then
    let sr ← rv64im_transpiler.row inst.paddr rv64im_transpiler.OP_AND
    let t ← rv64im_transpiler.source_imm rv64im_transpiler.jalr.JALR_MASK
    let sr1 ← rv64im_transpiler.set_a sr t
    let t1 ← rv64im_transpiler.source_reg inst.rs1
    let sr2 ← rv64im_transpiler.set_b sr1 t1
    let t2 ← rv64im_transpiler.store_reg inst.rd true
    let sr3 ← rv64im_transpiler.set_store sr2 t2
    let i1 ← lift (IScalar.cast .I64 inst.imm)
    let r ← rv64im_transpiler.set_j sr3 i1 4#i64
    rv64im_transpiler.StaticRows.one { r with set_pc := true }
  else
    let sr ← rv64im_transpiler.row inst.paddr rv64im_transpiler.OP_ADD
    let i1 ← lift (IScalar.hcast .U64 inst.imm)
    let t ← rv64im_transpiler.source_imm i1
    let sr1 ← rv64im_transpiler.set_a sr t
    let t1 ← rv64im_transpiler.source_reg inst.rs1
    let sr2 ← rv64im_transpiler.set_b sr1 t1
    let first ← rv64im_transpiler.set_j sr2 1#i64 1#i64
    let i2 ← inst.paddr + 1#u64
    let sr3 ← rv64im_transpiler.row i2 rv64im_transpiler.OP_AND
    let t2 ← rv64im_transpiler.source_imm rv64im_transpiler.jalr.JALR_MASK
    let sr4 ← rv64im_transpiler.set_a sr3 t2
    let sr5 ← rv64im_transpiler.set_b sr4 (zisk_inst.SRC_C, 0#u64, 0#u64)
    let t3 ← rv64im_transpiler.store_reg inst.rd true
    let sr6 ← rv64im_transpiler.set_store sr5 t3
    let second ← rv64im_transpiler.set_j sr6 0#i64 3#i64
    rv64im_transpiler.StaticRows.two first { second with set_pc := true }

/-- [zisk_core::rv64im_transpiler::jal]:
    Source: 'core/src/rv64im_transpiler.rs', lines 782:0-792:1 -/
def rv64im_transpiler.jal
  (inst : rv64im_transpiler.Rv64imInst) :
  Result rv64im_transpiler.StaticRows
  := do
  let sr ← rv64im_transpiler.row inst.paddr rv64im_transpiler.OP_FLAG
  let t ← rv64im_transpiler.source_imm 0#u64
  let sr1 ← rv64im_transpiler.set_a sr t
  let sr2 ← rv64im_transpiler.set_b sr1 t
  let t1 ← rv64im_transpiler.store_reg inst.rd true
  let sr3 ← rv64im_transpiler.set_store sr2 t1
  let i ← lift (IScalar.cast .I64 inst.imm)
  let r ← rv64im_transpiler.set_j sr3 i 4#i64
  rv64im_transpiler.StaticRows.one r

/-- [zisk_core::rv64im_transpiler::auipc]:
    Source: 'core/src/rv64im_transpiler.rs', lines 770:0-780:1 -/
def rv64im_transpiler.auipc
  (inst : rv64im_transpiler.Rv64imInst) :
  Result rv64im_transpiler.StaticRows
  := do
  let sr ← rv64im_transpiler.row inst.paddr rv64im_transpiler.OP_FLAG
  let t ← rv64im_transpiler.source_imm 0#u64
  let sr1 ← rv64im_transpiler.set_a sr t
  let sr2 ← rv64im_transpiler.set_b sr1 t
  let t1 ← rv64im_transpiler.store_reg inst.rd true
  let sr3 ← rv64im_transpiler.set_store sr2 t1
  let i ← lift (IScalar.cast .I64 inst.imm)
  let r ← rv64im_transpiler.set_j sr3 4#i64 i
  rv64im_transpiler.StaticRows.one r

/-- [zisk_core::rv64im_transpiler::lui]:
    Source: 'core/src/rv64im_transpiler.rs', lines 758:0-768:1 -/
def rv64im_transpiler.lui
  (inst : rv64im_transpiler.Rv64imInst) :
  Result rv64im_transpiler.StaticRows
  := do
  let sr ← rv64im_transpiler.row inst.paddr rv64im_transpiler.OP_COPYB
  let t ← rv64im_transpiler.source_imm 0#u64
  let sr1 ← rv64im_transpiler.set_a sr t
  let i ← lift (IScalar.hcast .U64 inst.imm)
  let t1 ← rv64im_transpiler.source_imm i
  let sr2 ← rv64im_transpiler.set_b sr1 t1
  let t2 ← rv64im_transpiler.store_reg inst.rd false
  let sr3 ← rv64im_transpiler.set_store sr2 t2
  let r ← rv64im_transpiler.set_j sr3 4#i64 4#i64
  rv64im_transpiler.StaticRows.one r

/-- [zisk_core::zisk_inst::STORE_IND]
    Source: 'core/src/zisk_inst.rs', lines 60:0-60:29
    Visibility: public -/
@[global_simps, irreducible] def zisk_inst.STORE_IND : Std.U64 := 2#u64

/-- [zisk_core::rv64im_transpiler::store_op]:
    Source: 'core/src/rv64im_transpiler.rs', lines 745:0-756:1 -/
def rv64im_transpiler.store_op
  (inst : rv64im_transpiler.Rv64imInst) (width : Std.U64) :
  Result rv64im_transpiler.StaticRows
  := do
  let sr ← rv64im_transpiler.row inst.paddr rv64im_transpiler.OP_COPYB
  let t ← rv64im_transpiler.source_reg inst.rs1
  let sr1 ← rv64im_transpiler.set_a sr t
  let t1 ← rv64im_transpiler.source_reg inst.rs2
  let sr2 ← rv64im_transpiler.set_b sr1 t1
  let i ← lift (IScalar.cast .I64 inst.imm)
  let sr3 ← rv64im_transpiler.set_store sr2 (zisk_inst.STORE_IND, i, false)
  let r ← rv64im_transpiler.set_j sr3 4#i64 4#i64
  rv64im_transpiler.StaticRows.one { r with ind_width := width }

/-- [zisk_core::zisk_inst::SRC_IND]
    Source: 'core/src/zisk_inst.rs', lines 51:0-51:27
    Visibility: public -/
@[global_simps, irreducible] def zisk_inst.SRC_IND : Std.U64 := 5#u64

/-- [zisk_core::rv64im_transpiler::source_ind]:
    Source: 'core/src/rv64im_transpiler.rs', lines 628:0-630:1 -/
def rv64im_transpiler.source_ind
  (offset : Std.I32) : Result (Std.U64 × Std.U64 × Std.U64) := do
  let i ← lift (IScalar.hcast .U64 offset)
  ok (zisk_inst.SRC_IND, 0#u64, i)

/-- [zisk_core::rv64im_transpiler::load_op]:
    Source: 'core/src/rv64im_transpiler.rs', lines 732:0-743:1 -/
def rv64im_transpiler.load_op
  (inst : rv64im_transpiler.Rv64imInst) (op : Std.U64) (width : Std.U64) :
  Result rv64im_transpiler.StaticRows
  := do
  let sr ← rv64im_transpiler.row inst.paddr op
  let t ← rv64im_transpiler.source_reg inst.rs1
  let sr1 ← rv64im_transpiler.set_a sr t
  let t1 ← rv64im_transpiler.source_ind inst.imm
  let sr2 ← rv64im_transpiler.set_b sr1 t1
  let t2 ← rv64im_transpiler.store_reg inst.rd false
  let sr3 ← rv64im_transpiler.set_store sr2 t2
  let r ← rv64im_transpiler.set_j sr3 4#i64 4#i64
  rv64im_transpiler.StaticRows.one { r with ind_width := width }

/-- [zisk_core::rv64im_transpiler::branch_op]:
    Source: 'core/src/rv64im_transpiler.rs', lines 722:0-730:1 -/
def rv64im_transpiler.branch_op
  (inst : rv64im_transpiler.Rv64imInst) (op : Std.U64) (neg : Bool) :
  Result rv64im_transpiler.StaticRows
  := do
  let (j1, j2) ←
    if neg
    then do
         let i ← lift (IScalar.cast .I64 inst.imm)
         ok (4#i64, i)
    else do
         let i ← lift (IScalar.cast .I64 inst.imm)
         ok (i, 4#i64)
  let sr ← rv64im_transpiler.row inst.paddr op
  let t ← rv64im_transpiler.source_reg inst.rs1
  let sr1 ← rv64im_transpiler.set_a sr t
  let t1 ← rv64im_transpiler.source_reg inst.rs2
  let sr2 ← rv64im_transpiler.set_b sr1 t1
  let r ← rv64im_transpiler.set_j sr2 j1 j2
  rv64im_transpiler.StaticRows.one r

/-- [zisk_core::rv64im_transpiler::copyb_from_reg]:
    Source: 'core/src/rv64im_transpiler.rs', lines 710:0-720:1 -/
def rv64im_transpiler.copyb_from_reg
  (inst : rv64im_transpiler.Rv64imInst) (rs : Std.U32) :
  Result rv64im_transpiler.StaticRows
  := do
  let sr ← rv64im_transpiler.row inst.paddr rv64im_transpiler.OP_COPYB
  let t ← rv64im_transpiler.source_imm 0#u64
  let sr1 ← rv64im_transpiler.set_a sr t
  let t1 ← rv64im_transpiler.source_reg rs
  let sr2 ← rv64im_transpiler.set_b sr1 t1
  let t2 ← rv64im_transpiler.store_reg inst.rd false
  let sr3 ← rv64im_transpiler.set_store sr2 t2
  let r ← rv64im_transpiler.set_j sr3 4#i64 4#i64
  rv64im_transpiler.StaticRows.one r

/-- [zisk_core::rv64im_transpiler::immediate_op]:
    Source: 'core/src/rv64im_transpiler.rs', lines 679:0-689:1 -/
def rv64im_transpiler.immediate_op
  (inst : rv64im_transpiler.Rv64imInst) (op : Std.U64) :
  Result rv64im_transpiler.StaticRows
  := do
  let sr ← rv64im_transpiler.row inst.paddr op
  let t ← rv64im_transpiler.source_reg inst.rs1
  let sr1 ← rv64im_transpiler.set_a sr t
  let i ← lift (IScalar.hcast .U64 inst.imm)
  let t1 ← rv64im_transpiler.source_imm i
  let sr2 ← rv64im_transpiler.set_b sr1 t1
  let t2 ← rv64im_transpiler.store_reg inst.rd false
  let sr3 ← rv64im_transpiler.set_store sr2 t2
  let r ← rv64im_transpiler.set_j sr3 4#i64 4#i64
  rv64im_transpiler.StaticRows.one r

/-- [zisk_core::rv64im_transpiler::immediate_op_or_x0_copyb]:
    Source: 'core/src/rv64im_transpiler.rs', lines 691:0-708:1 -/
def rv64im_transpiler.immediate_op_or_x0_copyb
  (inst : rv64im_transpiler.Rv64imInst) (op : Std.U64) :
  Result rv64im_transpiler.StaticRows
  := do
  if inst.rs1 = 0#u32
  then
    let sr ← rv64im_transpiler.row inst.paddr rv64im_transpiler.OP_COPYB
    let t ← rv64im_transpiler.source_reg inst.rs1
    let sr1 ← rv64im_transpiler.set_a sr t
    let i ← lift (IScalar.hcast .U64 inst.imm)
    let t1 ← rv64im_transpiler.source_imm i
    let sr2 ← rv64im_transpiler.set_b sr1 t1
    let t2 ← rv64im_transpiler.store_reg inst.rd false
    let sr3 ← rv64im_transpiler.set_store sr2 t2
    let r ← rv64im_transpiler.set_j sr3 4#i64 4#i64
    rv64im_transpiler.StaticRows.one r
  else rv64im_transpiler.immediate_op inst op

/-- [zisk_core::rv64im_transpiler::register_op]:
    Source: 'core/src/rv64im_transpiler.rs', lines 667:0-677:1 -/
def rv64im_transpiler.register_op
  (inst : rv64im_transpiler.Rv64imInst) (op : Std.U64) :
  Result rv64im_transpiler.StaticRows
  := do
  let sr ← rv64im_transpiler.row inst.paddr op
  let t ← rv64im_transpiler.source_reg inst.rs1
  let sr1 ← rv64im_transpiler.set_a sr t
  let t1 ← rv64im_transpiler.source_reg inst.rs2
  let sr2 ← rv64im_transpiler.set_b sr1 t1
  let t2 ← rv64im_transpiler.store_reg inst.rd false
  let sr3 ← rv64im_transpiler.set_store sr2 t2
  let r ← rv64im_transpiler.set_j sr3 4#i64 4#i64
  rv64im_transpiler.StaticRows.one r

/-- [zisk_core::rv64im_transpiler::lower_rv64im32]:
    Source: 'core/src/rv64im_transpiler.rs', lines 267:0-367:1
    Visibility: public -/
def rv64im_transpiler.lower_rv64im32
  (inst : rv64im_transpiler.Rv64imInst) :
  Result rv64im_transpiler.StaticRows
  := do
  match inst.op with
  | rv64im_transpiler.Rv64imOp.Add =>
    if inst.rs1 = 0#u32
    then rv64im_transpiler.copyb_from_reg inst inst.rs2
    else
      if inst.rs2 = 0#u32
      then rv64im_transpiler.copyb_from_reg inst inst.rs1
      else rv64im_transpiler.register_op inst rv64im_transpiler.OP_ADD
  | rv64im_transpiler.Rv64imOp.Sub =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_SUB
  | rv64im_transpiler.Rv64imOp.Sll =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_SLL
  | rv64im_transpiler.Rv64imOp.Slt =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_LT
  | rv64im_transpiler.Rv64imOp.Sltu =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_LTU
  | rv64im_transpiler.Rv64imOp.Xor =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_XOR
  | rv64im_transpiler.Rv64imOp.Srl =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_SRL
  | rv64im_transpiler.Rv64imOp.Sra =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_SRA
  | rv64im_transpiler.Rv64imOp.Or =>
    if inst.rs1 = 0#u32
    then rv64im_transpiler.copyb_from_reg inst inst.rs2
    else
      if inst.rs2 = 0#u32
      then rv64im_transpiler.copyb_from_reg inst inst.rs1
      else rv64im_transpiler.register_op inst rv64im_transpiler.OP_OR
  | rv64im_transpiler.Rv64imOp.And =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_AND
  | rv64im_transpiler.Rv64imOp.Addw =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_ADD_W
  | rv64im_transpiler.Rv64imOp.Subw =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_SUB_W
  | rv64im_transpiler.Rv64imOp.Sllw =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_SLL_W
  | rv64im_transpiler.Rv64imOp.Srlw =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_SRL_W
  | rv64im_transpiler.Rv64imOp.Sraw =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_SRA_W
  | rv64im_transpiler.Rv64imOp.Addi =>
    if inst.rd = 0#u32
    then
      if inst.rs1 = 0#u32
      then rv64im_transpiler.nop inst
      else rv64im_transpiler.hint inst
    else
      if inst.imm = 0#i32
      then
        if inst.rs1 != 0#u32
        then rv64im_transpiler.copyb_from_reg inst inst.rs1
        else
          rv64im_transpiler.immediate_op_or_x0_copyb inst
            rv64im_transpiler.OP_ADD
      else
        rv64im_transpiler.immediate_op_or_x0_copyb inst
          rv64im_transpiler.OP_ADD
  | rv64im_transpiler.Rv64imOp.Slli =>
    rv64im_transpiler.immediate_op inst rv64im_transpiler.OP_SLL
  | rv64im_transpiler.Rv64imOp.Slti =>
    rv64im_transpiler.immediate_op inst rv64im_transpiler.OP_LT
  | rv64im_transpiler.Rv64imOp.Sltiu =>
    rv64im_transpiler.immediate_op inst rv64im_transpiler.OP_LTU
  | rv64im_transpiler.Rv64imOp.Xori =>
    rv64im_transpiler.immediate_op_or_x0_copyb inst rv64im_transpiler.OP_XOR
  | rv64im_transpiler.Rv64imOp.Srli =>
    rv64im_transpiler.immediate_op inst rv64im_transpiler.OP_SRL
  | rv64im_transpiler.Rv64imOp.Srai =>
    rv64im_transpiler.immediate_op inst rv64im_transpiler.OP_SRA
  | rv64im_transpiler.Rv64imOp.Ori =>
    rv64im_transpiler.immediate_op_or_x0_copyb inst rv64im_transpiler.OP_OR
  | rv64im_transpiler.Rv64imOp.Andi =>
    rv64im_transpiler.immediate_op inst rv64im_transpiler.OP_AND
  | rv64im_transpiler.Rv64imOp.Addiw =>
    if inst.rd = 0#u32
    then
      if inst.rs1 = 0#u32
      then
        if inst.imm = 0#i32
        then rv64im_transpiler.nop inst
        else rv64im_transpiler.immediate_op inst rv64im_transpiler.OP_ADD_W
      else rv64im_transpiler.immediate_op inst rv64im_transpiler.OP_ADD_W
    else rv64im_transpiler.immediate_op inst rv64im_transpiler.OP_ADD_W
  | rv64im_transpiler.Rv64imOp.Slliw =>
    rv64im_transpiler.immediate_op inst rv64im_transpiler.OP_SLL_W
  | rv64im_transpiler.Rv64imOp.Srliw =>
    rv64im_transpiler.immediate_op inst rv64im_transpiler.OP_SRL_W
  | rv64im_transpiler.Rv64imOp.Sraiw =>
    rv64im_transpiler.immediate_op inst rv64im_transpiler.OP_SRA_W
  | rv64im_transpiler.Rv64imOp.Beq =>
    rv64im_transpiler.branch_op inst rv64im_transpiler.OP_EQ false
  | rv64im_transpiler.Rv64imOp.Bne =>
    rv64im_transpiler.branch_op inst rv64im_transpiler.OP_EQ true
  | rv64im_transpiler.Rv64imOp.Blt =>
    rv64im_transpiler.branch_op inst rv64im_transpiler.OP_LT false
  | rv64im_transpiler.Rv64imOp.Bge =>
    rv64im_transpiler.branch_op inst rv64im_transpiler.OP_LT true
  | rv64im_transpiler.Rv64imOp.Bltu =>
    rv64im_transpiler.branch_op inst rv64im_transpiler.OP_LTU false
  | rv64im_transpiler.Rv64imOp.Bgeu =>
    rv64im_transpiler.branch_op inst rv64im_transpiler.OP_LTU true
  | rv64im_transpiler.Rv64imOp.Lb =>
    rv64im_transpiler.load_op inst rv64im_transpiler.OP_SIGNEXT_B 1#u64
  | rv64im_transpiler.Rv64imOp.Lbu =>
    rv64im_transpiler.load_op inst rv64im_transpiler.OP_COPYB 1#u64
  | rv64im_transpiler.Rv64imOp.Lh =>
    rv64im_transpiler.load_op inst rv64im_transpiler.OP_SIGNEXT_H 2#u64
  | rv64im_transpiler.Rv64imOp.Lhu =>
    rv64im_transpiler.load_op inst rv64im_transpiler.OP_COPYB 2#u64
  | rv64im_transpiler.Rv64imOp.Lw =>
    rv64im_transpiler.load_op inst rv64im_transpiler.OP_SIGNEXT_W 4#u64
  | rv64im_transpiler.Rv64imOp.Lwu =>
    rv64im_transpiler.load_op inst rv64im_transpiler.OP_COPYB 4#u64
  | rv64im_transpiler.Rv64imOp.Ld =>
    rv64im_transpiler.load_op inst rv64im_transpiler.OP_COPYB 8#u64
  | rv64im_transpiler.Rv64imOp.Sb => rv64im_transpiler.store_op inst 1#u64
  | rv64im_transpiler.Rv64imOp.Sh => rv64im_transpiler.store_op inst 2#u64
  | rv64im_transpiler.Rv64imOp.Sw => rv64im_transpiler.store_op inst 4#u64
  | rv64im_transpiler.Rv64imOp.Sd => rv64im_transpiler.store_op inst 8#u64
  | rv64im_transpiler.Rv64imOp.Lui => rv64im_transpiler.lui inst
  | rv64im_transpiler.Rv64imOp.Auipc => rv64im_transpiler.auipc inst
  | rv64im_transpiler.Rv64imOp.Jal => rv64im_transpiler.jal inst
  | rv64im_transpiler.Rv64imOp.Jalr => rv64im_transpiler.jalr inst
  | rv64im_transpiler.Rv64imOp.Fence => rv64im_transpiler.nop inst
  | rv64im_transpiler.Rv64imOp.Mul =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_MUL
  | rv64im_transpiler.Rv64imOp.Mulh =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_MULH
  | rv64im_transpiler.Rv64imOp.Mulhsu =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_MULHSU
  | rv64im_transpiler.Rv64imOp.Mulhu =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_MULHU
  | rv64im_transpiler.Rv64imOp.Mulw =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_MUL_W
  | rv64im_transpiler.Rv64imOp.Div =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_DIV
  | rv64im_transpiler.Rv64imOp.Divu =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_DIVU
  | rv64im_transpiler.Rv64imOp.Divw =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_DIV_W
  | rv64im_transpiler.Rv64imOp.Divuw =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_DIVU_W
  | rv64im_transpiler.Rv64imOp.Rem =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_REM
  | rv64im_transpiler.Rv64imOp.Remu =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_REMU
  | rv64im_transpiler.Rv64imOp.Remw =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_REM_W
  | rv64im_transpiler.Rv64imOp.Remuw =>
    rv64im_transpiler.register_op inst rv64im_transpiler.OP_REMU_W

/-- [zisk_core::rv64im_transpiler::decode_and_lower_rv64im32]:
    Source: 'core/src/rv64im_transpiler.rs', lines 369:0-374:1
    Visibility: public -/
def rv64im_transpiler.decode_and_lower_rv64im32
  (word : Std.U32) (paddr : Std.U64) :
  Result (Option rv64im_transpiler.StaticRows)
  := do
  let o ← rv64im_transpiler.decode_rv64im32 word paddr
  match o with
  | none => ok none
  | some inst => let sr ← rv64im_transpiler.lower_rv64im32 inst
                 ok (some sr)

end zisk_core
