import Mathlib

import ZiskFv.Fundamentals.Goldilocks
import ZiskFv.Spec.Add

/-!
Phase 1 golden-trace fixture: canonical 64-bit ADD `3 + 5 = 8`.

Generated by `tools/golden-traces` from hardcoded values; Phase 1.5
replaces this with `ProverClient::get_instance_trace` output. The shape
matches what a real ZisK Main row + BinaryAdd row would produce for the
RISC-V instruction sequence:

```asm
addi x1, x0, 3
addi x2, x0, 5
add  x3, x1, x2  -- this row's witness is captured below
```
-/

namespace ZiskFv.GoldenTraces.Add

open Goldilocks

-- 32-bit lane decomposition (Main AIR columns).
@[simp] def add_a_lo : FGL := 3
@[simp] def add_a_hi : FGL := 0
@[simp] def add_b_lo : FGL := 5
@[simp] def add_b_hi : FGL := 0
@[simp] def add_c_lo : FGL := 8
@[simp] def add_c_hi : FGL := 0

-- 16-bit chunk decomposition (BinaryAdd AIR columns).
@[simp] def chunk_a0 : FGL := 3
@[simp] def chunk_a1 : FGL := 0
@[simp] def chunk_c0 : FGL := 8
@[simp] def chunk_c1 : FGL := 0
@[simp] def chunk_c2 : FGL := 0
@[simp] def chunk_c3 : FGL := 0

-- Carry-out cells.
@[simp] def cout_0 : FGL := 0
@[simp] def cout_1 : FGL := 0

/-- The packed `c`-value (32-bit lane recombination) matches `3 + 5 = 8`. -/
example : add_c_lo + add_c_hi * 4294967296 = (8 : FGL) := by decide

/-- BinaryAdd's chunk reassembly produces the same packed value. -/
example :
    (chunk_c1 * 65536 + chunk_c0) + (chunk_c3 * 65536 + chunk_c2) * 4294967296
      = (8 : FGL) := by decide

/-- Low-lane carry chain (BinaryAdd `carry_chain_0`):
    a_lo + b_lo = cout_0 * 2^32 + chunk_c1 * 2^16 + chunk_c0. -/
example :
    add_a_lo + add_b_lo
      = cout_0 * 4294967296 + chunk_c1 * 65536 + chunk_c0 := by decide

/-- High-lane carry chain (BinaryAdd `carry_chain_1`):
    a_hi + b_hi + cout_0 = cout_1 * 2^32 + chunk_c3 * 2^16 + chunk_c2. -/
example :
    add_a_hi + add_b_hi + cout_0
      = cout_1 * 4294967296 + chunk_c3 * 65536 + chunk_c2 := by decide

-- Phase 4 T-FIX: additional edge-case fixtures.

namespace ZeroResult

-- Edge case: `0 + 0 = 0` (zero-register sum, no carry).
@[simp] def add_a_lo : FGL := 0
@[simp] def add_a_hi : FGL := 0
@[simp] def add_b_lo : FGL := 0
@[simp] def add_b_hi : FGL := 0
@[simp] def add_c_lo : FGL := 0
@[simp] def add_c_hi : FGL := 0
@[simp] def cout_0 : FGL := 0
@[simp] def cout_1 : FGL := 0

example : add_c_lo + add_c_hi * 4294967296 = (0 : FGL) := by decide
example : add_a_lo + add_b_lo = cout_0 * 4294967296 + add_c_lo := by decide

end ZeroResult

namespace HighLaneOverflow

-- Edge case: `2^63 + 2^63 = 2^64 = 0 mod 2^64` (carry out of high lane).
-- a = 0x8000_0000_0000_0000, b = 0x8000_0000_0000_0000, c = 0, cout_1 = 1.
@[simp] def add_a_lo : FGL := 0
@[simp] def add_a_hi : FGL := 2147483648       -- 0x8000_0000
@[simp] def add_b_lo : FGL := 0
@[simp] def add_b_hi : FGL := 2147483648
@[simp] def add_c_lo : FGL := 0
@[simp] def add_c_hi : FGL := 0
@[simp] def cout_0 : FGL := 0
@[simp] def cout_1 : FGL := 1

example : add_c_lo + add_c_hi * 4294967296 = (0 : FGL) := by decide
example :
    add_a_hi + add_b_hi + cout_0
      = cout_1 * 4294967296 + add_c_hi := by decide

end HighLaneOverflow

end ZiskFv.GoldenTraces.Add
