import Mathlib

import ZiskFv.Fundamentals.Goldilocks
import ZiskFv.Spec.Sub

/-!
Phase 3C T-RT0 golden-trace fixture: canonical 64-bit SUB `5 - 3 = 2`.

Generated by hand (bus-passthrough fixture; the Binary-SM secondary
rows are outside Phase 3C's scope per `ALURTypeArchetype` — see
`ZiskFv/Tactics/ALURTypeArchetype.lean` docstring).

All `example`s are closed by `decide`.
-/

namespace ZiskFv.GoldenTraces.SUB

open Goldilocks
open ZiskFv.Trusted

-- Main AIR row: SUB `rd, rs1, rs2` with `rs1 = 5`, `rs2 = 3`,
-- expected `rd = 2`.
@[simp] def sub_pc : FGL := 100
@[simp] def sub_a_lo : FGL := 5
@[simp] def sub_a_hi : FGL := 0
@[simp] def sub_b_lo : FGL := 3
@[simp] def sub_b_hi : FGL := 0
@[simp] def sub_c_lo : FGL := 2
@[simp] def sub_c_hi : FGL := 0
@[simp] def sub_flag : FGL := 0
@[simp] def sub_set_pc : FGL := 0
@[simp] def sub_store_pc : FGL := 0
@[simp] def sub_jmp_offset1 : FGL := 4
@[simp] def sub_jmp_offset2 : FGL := 4
@[simp] def sub_is_external_op : FGL := 1
@[simp] def sub_op : FGL := 11                 -- OP_SUB
@[simp] def sub_m32 : FGL := 0

/-- Packed Main `c` matches `5 - 3 = 2`. -/
example : sub_c_lo + sub_c_hi * 4294967296 = (2 : FGL) := by decide

/-- Bus `a_hi` passthrough under `m32 = 0`: `(1 - 0) * a_hi = a_hi`. -/
example : (1 - sub_m32) * sub_a_hi = sub_a_hi := by decide

/-- Bus `b_hi` passthrough. -/
example : (1 - sub_m32) * sub_b_hi = sub_b_hi := by decide

/-- Opcode-literal consistency. -/
example : sub_op = OP_SUB := by decide

/-- Booleans: `is_external_op`, `flag`, `m32` are boolean; flag
    disjoint from set_pc. -/
example :
    sub_is_external_op * (1 - sub_is_external_op) = (0 : FGL) ∧
    sub_flag * (1 - sub_flag) = (0 : FGL) ∧
    sub_m32 * (1 - sub_m32) = (0 : FGL) ∧
    sub_flag * sub_set_pc = (0 : FGL) := by decide

-- Phase 4 T-FIX: additional edge-case fixtures.

namespace Identity

-- Edge case: `x - x = 0` (self-subtraction, any x).
@[simp] def sub_a_lo : FGL := 42
@[simp] def sub_a_hi : FGL := 0
@[simp] def sub_b_lo : FGL := 42
@[simp] def sub_b_hi : FGL := 0
@[simp] def sub_c_lo : FGL := 0
@[simp] def sub_c_hi : FGL := 0

example : sub_c_lo + sub_c_hi * 4294967296 = (0 : FGL) := by decide

end Identity

namespace Underflow

-- Edge case: `0 - 1 = 2^64 - 1` (full underflow; two's complement).
-- Low lane: 0 - 1 = 0xFFFFFFFF with borrow.
-- High lane: 0 - 0 - 1(borrow) = 0xFFFFFFFF.
@[simp] def sub_a_lo : FGL := 0
@[simp] def sub_a_hi : FGL := 0
@[simp] def sub_b_lo : FGL := 1
@[simp] def sub_b_hi : FGL := 0
@[simp] def sub_c_lo : FGL := 4294967295      -- 0xFFFFFFFF
@[simp] def sub_c_hi : FGL := 4294967295

-- 2^64 - 1 as a Goldilocks element.
example :
    sub_c_lo + sub_c_hi * 4294967296
      = (18446744073709551615 : FGL) := by decide

end Underflow

end ZiskFv.GoldenTraces.SUB
